### ISSUE TITLE
[Bug] Dependency name is too long / file not found

### ISSUE THREAD

**Issue by eg-tan** [dbt-labs/dbt-core#10653]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We've faced some too-long file paths in dbt project - looks like DBT core incorrectly handled it. The full path with the following prefix should not exceed 260 symbols.

Example 

```
C:\Users\<USER>\AppData\Local\Temp\dbt-downloads-qdbfjp57\5578bf4e628e11aeddd9aca27cc791fce\tests\telescope\skill_link\skills\skills_by_applicant_id\sources\test_sl_applicant_skill_from_skill_update_flat\test_sl_applicant_skill_from_skill_update_flat__applicant_sources.sql
```

In this case dbt raise `FileNotFoundError`

### Expected Behavior

The long file path is handled correctly within dbt without the need to shorten the file name.

### Steps To Reproduce

1. Create a full file path with a length of more than 260 characters within the dbt project.
2.  Run dbt compile 

In our case, we created dbt unit test and during `dbt test`, we got an error  `FileNotFoundError`

### Relevant log output

```shell
[0m20:09:06.573317 [error] [MainThread]: Encountered an error:
[WinError 3] The system cannot find the path specified: 'C:\\Users\\SIARHE~1\\AppData\\Local\\Temp\\dbt-downloads-aonydoz4\\5578bf4e628e11aedd9aca27cc791fce\\tests\\telescope\\skill_link\\skills\\skills_by_applicant_id\\sources\\test_sl_applicant_skill_from_skill_update_flat\\test_sl_applicant_skill_from_skill_update_flat__applicant_sources.sql'
[0m20:09:06.576334 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Soft\Python311\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\SIARHE~1\\AppData\\Local\\Temp\\dbt-downloads-aonydoz4\\5578bf4e628e11aedd9aca27cc791fce\\tests\\telescope\\skill_link\\skills\\skills_by_applicant_id\\sources\\test_sl_applicant_skill_from_skill_update_flat\\test_sl_applicant_skill_from_skill_update_flat__applicant_sources.sql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Soft\Python311\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\Python311\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\Python311\Lib\site-packages\dbt\cli\requires.py", line 201, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\Python311\Lib\site-packages\dbt\cli\requires.py", line 247, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\Python311\Lib\site-packages\dbt\cli\main.py", line 447, in deps
    results = task.run()
              ^^^^^^^^^^
  File "C:\Soft\Python311\Lib\site-packages\dbt\task\deps.py", line 217, in run
    self.lock()
  File "C:\Soft\Python311\Lib\site-packages\dbt\task\deps.py", line 193, in lock
    with downloads_directory():
  File "C:\Soft\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Soft\Python311\Lib\site-packages\dbt\deps\base.py", line 43, in downloads_directory
    system.rmtree(DOWNLOADS_PATH)
  File "C:\Soft\Python311\Lib\site-packages\dbt_common\clients\system.py", line 698, in rmtree
    return shutil.rmtree(path, onerror=chmod_and_retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soft\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Soft\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Soft\Python311\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 5 more times]
  File "C:\Soft\Python311\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Soft\Python311\Lib\site-packages\dbt_common\clients\system.py", line 642, in chmod_and_retry
    os.chmod(path, stat.S_IREAD | stat.S_IWRITE)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\SIARHE~1\\AppData\\Local\\Temp\\dbt-downloads-aonydoz4\\5578bf4e628e11aedd9aca27cc791fce\\tests\\telescope\\skill_link\\skills\\skills_by_applicant_id\\sources\\test_sl_applicant_skill_from_skill_update_flat\\test_sl_applicant_skill_from_skill_update_flat__applicant_sources.sql'

[0m20:09:06.578314 [debug] [MainThread]: Command `dbt deps` failed at 20:09:06.578314 after 40.41 seconds
```

### Environment

```markdown
- OS: Windows
- Python: 3.11
- dbt: 1.8
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

![FileNotFoundError](https://github.com/user-attachments/assets/9c569e30-a5e4-4923-a241-8a4e6b28c832)

Adapter dbt-athena

**Comment by dbeatty10** [comment]
Thanks for reaching out @eg-tan !

Which version of Windows are you using? Are you using [LongPathsEnabled](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html) registry setting, by any chance?

From [digging into this](https://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows) a little more, it sounds like Windows has traditionally enforced a MAX_PATH limit of 260 characters for file paths. But starting with Windows 10 and Windows Server 2016, it became possible to remove this limitation by changing the system settings. Specifically, by enabling the "LongPathsEnabled" registry setting or modifying the [Enable NTFS long paths](https://stackoverflow.com/a/40305489) group policy setting.

**Comment by eg-tan** [comment]
Got it, thanks. 
`New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force` from admin worked for me
