### ISSUE TITLE
[Bug] `dbt retry` does not work for `dbt docs generate`

### ISSUE THREAD

**Issue by jordivandooren** [dbt-labs/dbt-core#10741]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running `dbt retry` after `dbt docs generate`, raises an error:

```
click.exceptions.NoSuchOption: No such option: --no-empty-catalog
```

or

```
click.exceptions.NoSuchOption: No such option: --no-static
```

### Expected Behavior

The absence of the `static` flag should not be translated into the (non-existent) `--no-static`. It should be treated as absent.

The same goes for `empty_catalog`.

### Steps To Reproduce

1. In a default starter project (e.g. using `dbt-postgres`)
2. After running `dbt docs generate` (without `--static` or `--empty_catalog` flags)
3. Running `dbt retry` returns in a `NoSuchOptions` error relating to the non-existent `--no-static` or `--no-empty-catalog` flag.

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.11
- dbt: v1.8.6
```

**Comment by dbeatty10** [comment]
Thanks for reporting this and raising the associated PR @jordivandooren !

### Reprex

Create these files:

`models/my_model.sql`

```sql
select 1 as id
```

Run these commands:

```shell
dbt docs generate
dbt retry
```

💥 Get this stacktrace containing the error:

```
$ dbt retry        
20:17:59  Running with dbt=1.8.6
20:17:59  Encountered an error:
No such option: --no-static
20:17:59  Traceback (most recent call last):
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/requires.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/requires.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/requires.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/main.py", line 594, in retry
    task = RetryTask(
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/task/retry.py", line 107, in __init__
    retry_flags = Flags.from_dict(cli_command, combined_args)  # type: ignore
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/flags.py", line 356, in from_dict
    ctx = args_to_context(command_arg_list)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/dbt/cli/flags.py", line 79, in args_to_context
    sub_command_ctx = sub_command.make_context(sub_command_name, args)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/click/core.py", line 1405, in parse_args
    opts, args, param_order = parser.parse_args(args=args)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/click/parser.py", line 337, in parse_args
    self._process_args_for_options(state)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/click/parser.py", line 364, in _process_args_for_options
    self._process_opts(arg, state)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/click/parser.py", line 514, in _process_opts
    self._match_long_opt(norm_long_opt, explicit_value, state)
  File "/Users/dbeatty/projects/environments/dbt_1.8/lib/python3.10/site-packages/click/parser.py", line 398, in _match_long_opt
    raise NoSuchOption(opt, possibilities=possibilities, ctx=self.ctx)
click.exceptions.NoSuchOption: No such option: --no-static
```

✅ Running these same commands against https://github.com/dbt-labs/dbt-core/pull/10742 worked
