### ISSUE TITLE
FileNotFoundError while running dbt deps for private package

### ISSUE THREAD

**Issue by NireshGopalakrishnan-Moodys** [dbt-labs/dbt-core#11035]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Trying to download a dbt private package from JFrog Artifactory. The gz file is named data-etl-dbt-shared-utils.tar.gz and the dbt folder is named dbt-shared-utils that contains macros and models to be shared across other project. 

While running dbt deps, the gz file is getting downloaded but the file is getting downloaded in the name dbt-shared-utils without an extension. 

for there, tarball.py is trying create untarred file and process is failing with error below
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3p/r9f6r8zj6lb29704xvydp63hfv15rv/T/dbt-downloads-fw5t_39q/dbt-shared-utils_untarred/dbt-shared-utils'
```

Here is full error:
```
dbt % dbt deps
14:01:32  Running with dbt=1.8.0
14:01:34  Encountered an error:
[Errno 2] No such file or directory: '/var/folders/3p/r9f6r8zj6lb29704xvydp63hfv15rv/T/dbt-downloads-fw5t_39q/dbt_shared_utils_untarred/dbt_shared_utils'
14:01:34  Traceback (most recent call last):
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3p/r9f6r8zj6lb29704xvydp63hfv15rv/T/dbt-downloads-fw5t_39q/dbt_shared_utils_untarred/dbt_shared_utils' -> '/var/folders/3p/r9f6r8zj6lb29704xvydp63hfv15rv/T/dbt-downloads-fw5t_39q/dbt_shared_utils_untarred/dbt_shared_utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/cli/requires.py", line 201, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/cli/requires.py", line 247, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/cli/main.py", line 446, in deps
    results = task.run()
              ^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/task/deps.py", line 225, in run
    self.lock()
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/task/deps.py", line 194, in lock
    resolved_deps = resolve_packages(packages, self.project, self.cli_vars)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/deps/resolver.py", line 128, in resolve_packages
    target = final[package].resolved().fetch_metadata(project, renderer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/deps/base.py", line 93, in fetch_metadata
    self._cached_metadata = self._fetch_metadata(project, renderer)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/deps/tarball.py", line 62, in _fetch_metadata
    connection_exception_retry(download_untar_fn, 5)
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt_common/utils/connection.py", line 21, in connection_exception_retry
    return fn()
           ^^^^
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt/deps/base.py", line 133, in download_and_untar
    system.untar_package(tar_path, deps_path, package_name)
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt_common/clients/system.py", line 646, in untar_package
    dbt_common.clients.system.rename(downloaded_path, desired_path, force=True)
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/site-packages/dbt_common/clients/system.py", line 609, in rename
    shutil.move(from_path, to_path)
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/user_name/.pyenv/versions/3.11.7/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3p/r9f6r8zj6lb29704xvydp63hfv15rv/T/dbt-downloads-fw5t_39q/dbt_shared_utils_untarred/dbt_shared_utils'
```

### Expected Behavior

Expected behavior is have the tarball files untarred and dbt project extracted out of it. 

### Steps To Reproduce

1. Create a dbt project
2. Create a tar and push it to JFrog Artifactory 
3. In a project where we want to refer the private package, create pacakges.yml and refer the tar file from JFrog
4. Run dbt deps

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by NireshGopalakrishnan-Moodys** [comment]
Upon making this tweak in the packages.yml, i was able to get the private package in the dbt project:
  - tarball: https://{user}:{token}@{myorg}.jfrog.io/artifactory/generic/dbt/data-etl-dbt-shared-utils/data-etl-dbt-shared-utils.tar.gz
    name: 'dbt_shared_utils.gz'

What i did is I added ".gz" as a extension in the name of the package. The issue still is the package is coming out as dbt_shared_utils.gz instead of expected "dbt_shared_utils"

This needs to be fixed in the process of downloading and extracting the tarball file.

**Comment by dbeatty10** [comment]
Serving a file locally and creating a `packages.yml` file like the following worked for me:

```yaml
packages:
  - tarball: http://localhost:8000/archive_name.tar.gz
    name: 'dbt_utils_w_packages_yml'
```

```
$ dbt deps

01:22:00  Running with dbt=1.8.8
01:22:01  Updating lock file in file path: /Users/dbeatty/projects/copier-templates/duckdb-core-8621/package-lock.yml
01:22:01  Installing dbt_utils_w_packages_yml
01:22:01  Installed from tarball (url: http://localhost:8000/archive_name.tar.gz)
01:22:01  Installing calogica/dbt_date
01:22:01  Installed from version 0.9.1
01:22:01  Updated version available: 0.10.1
01:22:01  
01:22:01  Updates available for packages: ['calogica/dbt_date']                 
Update your versions in packages.yml, then run dbt deps
```

What type of content did you try in your `packages.yml` file that didn't work?

**Comment by ahaugerud** [comment]
I am getting the same error whenever the "name" key matches the package name in the tarball url

OS  info (running in WSL):
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble
```

`dbt --version`
```bash
Core:
  - installed: 1.10.4
  - latest:    1.10.4 - Up to date!

Plugins:
```

This causes the FileNotFoundError
```yaml
packages:
  - tarball: https://my_package_1.0.0.tar.gz
     name: my_package
```

This works
```yaml
packages:
  - tarball: https://my_package_1.0.0.tar.gz
     name: not_my_package
```

Haven't looked into what is causing this though, but changing the name key under `tarball` to something else than the name of the tarball  got rid of the error

From very quick inspection of the files produced in `/tmp/<downloads directory>` it looks like target subdirectory for the extraction isn't being created when the name key matches the tarball package name for some reason


Might look more into this soon.

**Comment by ahaugerud** [comment]
Had to work through this again now and dove a bit deeper, the issue in my case seems to be caused whenever the `system.untar_package` method from `dbt-common` tries to rename the package to itself, im guessing whenever the project name from `dbt_project.yml` for the target package to be installed is equal to the `name:` key in `packages.yml`.

From further testing this is an upstream issue in `dbt-common` so don't thing it needs to be fixed in `dbt-core` 

To be exact there seems to be an unhandled edge-case in `dbt-common` in the `system` clients `rename` method that fails when `from_path` == `to_path` and `force = true`

```python
def rename(from_path: str, to_path: str, force: bool = False) -> None:
    from_path = convert_path(from_path)
    to_path = convert_path(to_path)
    is_symlink = path_is_symlink(to_path)

    if os.path.exists(to_path) and force: # <--- will delete the source folder before it can be moved
        if is_symlink:
            remove_file(to_path)
        else:
            rmdir(to_path) # <--- also deletes the source folder with contents

    shutil.move(from_path, to_path) # <---- nothing to move
```

https://github.com/dbt-labs/dbt-common/blob/f4c69bdd253a1c876800fd7fb3ff7af89909860e/dbt_common/clients/system.py#L598 

The fix should be fairly straight forward, creating a new issue in [`dbt-common`](https://github.com/dbt-labs/dbt-common) and cross-referencing


There is also room to improve the logging here, took some time to understand why it was failing as i had some issues with the source as well returning non gz tarballs and giving similar error messages with little to no context, might add a pr for this later

**Comment by ahaugerud** [comment]
Should be solved now with dbt-common 1.30.0

**Comment by dbeatty10** [comment]
@ahaugerud Thanks for all your research + handing this in https://github.com/dbt-labs/dbt-common/issues/307 and https://github.com/dbt-labs/dbt-common/issues/308 👑

Closing as covered in those.
