### ISSUE TITLE
Enabling Multithreading causes instability in Postgres

### ISSUE THREAD

**Issue by AndrewStoffelMerrill** [dbt-labs/dbt-core#2311]
### Describe the bug
While building some models we've encountered an issue where models throw errors if the build is done with multiple threads. If the process is changed to run in a single thread the build is successful.
 
It throws an error that permission was denied for one of the tables in the select statement.
The dbt user has access to the table. The dbt user is the owner of the table. The compiled sql can be taken and executed, as the dbt user and without issue, using psql or pgadmin.
 
 
### Steps To Reproduce
To reproduce the bug set "threads" in "profiles.yml" to a value greater than 1.
 
### Expected behavior
The model builds successfully using more than one thread.
 
### Screenshots and log output
##Stack, Unsuccessful Run, Thread-2
 
```
2020-04-09 14:49:33.696479 (Thread-2): Using postgres connection "model.postgres_dev.qa_events".
2020-04-09 14:49:33.696739 (Thread-2): On model.postgres_dev.qa_events: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "ds1postgres", "target_name": "dev", "node_id": "model.postgres_dev.qa_events"} */
2020-04-09 14:49:34.675785 (Thread-2): Postgres error: permission denied for table projects_details
2020-04-09 14:49:34.677145 (Thread-2): Database Error in model qa_events (models/tables/qa_events.sql)
  permission denied for table projects_details
  compiled SQL at target/compiled/postgres_dev/tables/qa_events.sql
Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/adapters/postgres/connections.py", line 46, in exception_handler
    yield
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/adapters/sql/connections.py", line 74, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.InsufficientPrivilege: permission denied for table projects_details
 
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/node_runners.py", line 223, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/node_runners.py", line 166, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/node_runners.py", line 268, in run
    return self.execute(compiled_node, manifest)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/node_runners.py", line 450, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 231, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 161, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 109, in macro
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 231, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 161, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 33, in macro
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 231, in __call__
    return self.call_macro(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 161, in call_macro
    return macro(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 220, in execute
    fetch=fetch
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/adapters/sql/connections.py", line 116, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/adapters/sql/connections.py", line 82, in add_query
    return connection, cursor
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/dbt/0.16.0_1/libexec/lib/python3.7/site-packages/dbt/adapters/postgres/connections.py", line 58, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error in model qa_events (models/tables/qa_events.sql)
  permission denied for table projects_details
  compiled SQL at target/compiled/postgres_dev/tables/qa_events.sql
2020-04-09 14:49:34.681098 (Thread-2): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '9943fa61-f7eb-4579-8086-d541d2c5df97', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10545d5d0>]}
2020-04-09 14:49:34.681362 (Thread-2): 09:49:34 | 2 of 2 ERROR creating incremental model dbt.qa_events................ [ERROR in 1.20s]
2020-04-09 14:49:34.681502 (Thread-2): Finished running node model.postgres_dev.qa_events
 ```

### System information
**Which database are you using dbt with?**
PostgreSQL 11.6
 
 
 
**The output of `dbt --version`:**
```
installed version: 0.16.0
   latest version: 0.16.0
 
Up to date!
```
 
**The operating system you're using:**
os info: Darwin-18.6.0-x86_64-i386-64bit
 
 
**The output of `python --version`:**
python version: 3.7.7
 
 
### Additional context
##Debug Info
```
[localhost~/gitsrc/postgres-models]>dbt debug
Running with dbt=0.16.0
dbt version: 0.16.0
python version: 3.7.7
python path: /usr/local/Cellar/dbt/0.16.0_1/libexec/bin/python3.7
os info: Darwin-18.6.0-x86_64-i386-64bit
Using profiles.yml file at ~/.dbt/profiles.yml
Using dbt_project.yml file at ~/gitsrc/postgres-models/dbt_project.yml
 
Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]
 
Required dependencies:
- git [OK found]
 
Connection:
  host: {snip}
  port: {snip}
  user: {snip}
  database: {snip}
  schema: dbt
  search_path: dbt
  keepalives_idle: 0
  sslmode: require
  Connection test: OK connection ok
 ```
 
##Example Multi Thread Run
```
[localhost~/gitsrc/postgres-models]>dbt run --models qa_events qa_activity
Running with dbt=0.16.0
Found 19 models, 0 tests, 0 snapshots, 0 analyses, 127 macros, 0 operations, 0 seed files, 0 sources
 
09:49:33 | Concurrency: 8 threads (target='dev')
09:49:33 |
09:49:33 | 1 of 2 START incremental model dbt.qa_activity....................... [RUN]
09:49:33 | 2 of 2 START incremental model dbt.qa_events......................... [RUN]
09:49:34 | 1 of 2 OK created incremental model dbt.qa_activity.................. [INSERT 0 1000 in 0.91s]
09:49:34 | 2 of 2 ERROR creating incremental model dbt.qa_events................ [ERROR in 1.20s]
09:49:34 |
09:49:34 | Finished running 2 incremental models in 4.67s.
 
Completed with 1 error and 0 warnings:
 
Database Error in model qa_events (models/tables/qa_events.sql)
  permission denied for table projects_details
  compiled SQL at target/compiled/postgres_dev/tables/qa_events.sql
 
Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
 ```
 
##Example Single Thread Run
```
[localhost~/gitsrc/postgres-models]>dbt run --models qa_events qa_activity
Running with dbt=0.16.0
Found 19 models, 0 tests, 0 snapshots, 0 analyses, 127 macros, 0 operations, 0 seed files, 0 sources
 
09:50:58 | Concurrency: 1 threads (target='dev')
09:50:58 |
09:50:58 | 1 of 2 START incremental model dbt.qa_activity....................... [RUN]
09:50:59 | 1 of 2 OK created incremental model dbt.qa_activity.................. [INSERT 0 1000 in 0.82s]
09:50:59 | 2 of 2 START incremental model dbt.qa_events......................... [RUN]
09:51:01 | 2 of 2 OK created incremental model dbt.qa_events.................... [INSERT 0 1000 in 2.08s]
09:51:01 |
09:51:01 | Finished running 2 incremental models in 6.48s.
 
Completed successfully
 
Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
 ```

##Error Message in dbt.log
```
2020-04-09 14:08:22.652688 (Thread-2): Postgres error: permission denied for table projects_details
2020-04-09 14:08:22.653014 (Thread-2): finished collecting timing info
2020-04-09 14:08:22.653627 (Thread-2): Database Error in model qa_events (models/tables/qa_events.sql)
  permission denied for table projects_details
```

**Comment by drewbanin** [comment]
Hi @AndrewStoffelMerrill - are you able to share the query that results in this error being raised? It looks like you scrubbed this information from your logs, but insight into those queries is the only way we can know what's going wrong here!

Please follow up below with the lines of SQL that dbt runs when this error is raised:
```
2020-04-09 14:49:33.696479 (Thread-2): Using postgres connection "model.postgres_dev.qa_events".
2020-04-09 14:49:33.696739 (Thread-2): On model.postgres_dev.qa_events: /* {"app": "dbt", "dbt_version": "0.16.0", "profile_name": "ds1postgres", "target_name": "dev", "node_id": "model.postgres_dev.qa_events"} */
< SQL would be here ! >
2020-04-09 14:49:34.675785 (Thread-2): Postgres error: permission denied for table projects_details
2020-04-09 14:49:34.677145 (Thread-2): Database Error in model qa_events (models/tables/qa_events.sql)
  permission denied for table projects_details
  compiled SQL at target/compiled/postgres_dev/tables/qa_events.sql
```

**Comment by drewbanin** [comment]
also, can you tell me if you are using the `ref` function to refer to one model from the other? The more information you're able to share here, the more helpful we can be :)

**Comment by AndrewStoffelMerrill** [comment]
Yes, it does ref two other models. Though I can reproduce it on two models with out any refs as well.

 I'm limited it what I can post in public.  If the email address in your profile is correct I can email you the logs/queries directly. If that doesn't work I would be happy to discuss a way to submit the issue and all relevant logs on a non-public forum.


While trying work arounds we've encountered a different error message that seems related:

```
2020-04-11 03:45:55.798812 (Thread-2): Database Error in model project_details (models/tables/mongo/project_details.sql)
  must be owner of table project details
```

Here is DBT creating the table in a previous run:
```
2020-04-11 03:45:34.184093 (Thread-1): 22:45:34 | 1 of 1 OK created table model dbt.project_details......... [SELECT 51001 in 1.70s]```

**Comment by drewbanin** [comment]
This is so strange! I have never seen an error like `must be owner of table ....` before associated with concurrency!

I am _definitely_ curious what the SQL is that results in this error. If it's a `create table as` statement, then boy... I really don't know what the issue could be! If it's something else, like a `grant` statement in a `pre-hook` or `post-hook` (or similar) then a permissions error would make a whole lot more sense.

If you're unable to share the exact logs publicly, that's a-ok, but you probably shouldn't send them to my email either. Can you share a fuzzed version of the type of query that runs which results in this error? If you really cannot do that, then sure, shoot me an email with the info you can share :)

**Comment by drewbanin** [comment]
hey @AndrewStoffelMerrill - thanks for sending through the logs offline. I did take a look at them, and it appears that the issue is with a query like:

```
alter table "<database>"."<schema>"."<table>" rename to "<table>__dbt_backup"
```

dbt runs this query in order to move the existing table out of the way to make room for the _new_ table. The high-level flow should look like:

```
create table "<database>"."<schema>"."<table>__dbt_tmp" as (
 select ...
);

-- this is the query that fails
alter table "<database>"."<schema>"."<table>" rename to "<table>__dbt_backup";

alter table "<database>"."<schema>"."<table>__dbt_tmp" rename to"<table>";
```

I can't think of any good reason why using a different number of threads would have any impact on the success or failure of the query that appears to fail here!

In your reproduction scenario outlined above, you noted that you can reproduce this error by changing the number of threads in your target. Can you try something for me:

1. Set the number of threads in your target to `1`
2. Do a `dbt run` and check to see if this permissions error occurs
3. Do a `dbt run --threads 8` and check to see if this permissions error occurs

Can you let me know what happens when you do those three things?

**Comment by AndrewStoffelMerrill** [comment]
I've sent the logs, any update?

**Comment by AndrewStoffelMerrill** [comment]
I've managed to play around with this and create an additional error. If I add all 20+ models and set the threads to 8 then I can get the following error:

```
2020-05-01 23:15:02.933294 (Thread-6): Postgres error: current transaction is aborted, commands ignored until end of transaction block
```
This happens after an earlier model on the same thread failed. It doesn't look like the transactions are being properly ended. So far as I can tell the starting error is always in the rename_relation macro.

**Comment by drewbanin** [comment]
hey @AndrewStoffelMerrill - we're still pretty stumped here. Here's what would be _incredibly_ helpful for us:

Can you create a minimal reproduction of this error in a bare-bones dbt project? If you could create a new public repo, along with the some models that result in this error (plus the commands you're running), then we could give things a spin on our end too.

At present:
 - I can't reproduce the behavior you're describing at all
 - I have never heard of such a thing happening before
 - The failure mode does not make any sense to me (permission denied?? how??)

So, a good way to proceed would be to remove as many variables from the equation as possible. Let me know if that's something you're able to do, and if there's any other direction I can provide. If this is a bug in dbt, then it's a pretty nasty one, so I'd love to get to the bottom of it!

**Comment by AndrewStoffelMerrill** [comment]
Working with Drew we were able to identify the issue. In the profiles we had put the role the DBT user was a part of in the config. Removing that line fixed the problems.

**Comment by drewbanin** [comment]
right on @AndrewStoffelMerrill - glad you got it working! 

For reference, the issue is an undetermined bug with the `role` config. dbt sets the role for a connection by executing `set role {role}` when connections are opened. Somehow, dbt is not setting this role correctly in the `alter table` statements that fail! This is tough to diagnose because the pg dbt plugin does not log the query lines (they go directly to `adapter.execute`).

Let's:
 - Make sure we log the SQL that calls `set role`
 - Try to figure out how and why these connections are not being set up with the correct role

**Comment by mjuszczak** [comment]
FYI, we are also encountering this issue after rolling out a forced SET ROLE= policy to ensure proper object ownership. Nothing to add other than that we're also encountering the bug.
