### ISSUE TITLE
CLI vars not available in dbt_project.yml in dependent packages

### ISSUE THREAD

**Issue by dstuck** [dbt-labs/dbt-core#2769]
### Describe the bug
Variables in dbt_project.yml must be passed in via `--vars` flag in cli, but variables past in this way are not included in Configuration when parsing the package: `Vars supplied to <Configuration> = {}`

### Steps To Reproduce
In the package dbt_project.yml include a variable, i.e. set the schema:
```
models:
  testing:
    +materialized: view
    +schema: '{{ var("project_name") }}_SOURCES'
```

### Expected behavior
Running the above example with `dbt run --vars '{project_name: SAMPLE}' should set the schema for the testing model to SAMPLE_SOURCES

### Screenshots and log output
Here's the stack trace:
```
  Could not render {{ var("project_name") }}_SOURCES: Required var 'project_name' not found in config:
  Vars supplied to <Configuration> = {}
2020-09-17 19:06:48.946543 (MainThread): Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/renderer.py", line 41, in render_value
    return get_rendered(value, self.context, native=True)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 530, in get_rendered
    return render_template(template, ctx, node)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 481, in render_template
    return template.render(ctx)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 156, in render
    return self.environment.handle_exception()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/clients/jinja.py", line 119, in quoted_native_concat
    head = list(islice(nodes, 2))
  File "<template>", line 1, in top-level template code
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/context/base.py", line 148, in __call__
    return self.get_missing_var(var_name)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/context/base.py", line 129, in get_missing_var
    raise_compiler_error(msg, self.node)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/exceptions.py", line 392, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error
  Required var 'project_name' not found in config:
  Vars supplied to <Configuration> = {}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/main.py", line 81, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/main.py", line 159, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/main.py", line 212, in run_from_args
    results = task.run()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/task/runnable.py", line 389, in run
    self._runtime_initialize()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/task/runnable.py", line 103, in _runtime_initialize
    super()._runtime_initialize()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/task/runnable.py", line 71, in _runtime_initialize
    self.load_manifest()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/task/runnable.py", line 60, in load_manifest
    self.manifest = get_full_manifest(self.config)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/perf_utils.py", line 23, in get_full_manifest
    return load_manifest(config, internal, set_header)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/parser/manifest.py", line 641, in load_manifest
    return ManifestLoader.load_all(config, internal_manifest, macro_hook)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/parser/manifest.py", line 345, in load_all
    projects = root_config.load_dependencies()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/runtime.py", line 329, in load_dependencies
    for project_name, project in self.load_projects(project_paths):
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/runtime.py", line 346, in load_projects
    project = self.new_project(str(path))
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/runtime.py", line 126, in new_project
    project = Project.from_project_root(project_root, renderer)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/project.py", line 609, in from_project_root
    return partial.render(renderer)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/project.py", line 218, in render
    renderer,
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/project.py", line 573, in render_from_dict
    rendered_project = renderer.render_data(project_dict)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/renderer.py", line 127, in render_data
    return deep_map(self.render_entry, data)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 226, in deep_map
    return _deep_map(func, value, ())
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in _deep_map
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in <dictcomp>
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in _deep_map
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in <dictcomp>
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in _deep_map
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in <dictcomp>
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in _deep_map
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 191, in <dictcomp>
    for k, v in value.items()
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/utils.py", line 194, in _deep_map
    ret = func(value, keypath)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/renderer.py", line 30, in render_entry
    return self.render_value(value, keypath)
  File "/usr/local/Cellar/dbt/0.17.0_1/libexec/lib/python3.7/site-packages/dbt/config/renderer.py", line 44, in render_value
    raise CompilationException(msg) from exc
dbt.exceptions.CompilationException: Compilation Error
  Could not render {{ var("project_name") }}_SOURCES: Required var 'project_name' not found in config:
  Vars supplied to <Configuration> = {}
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.18.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0
```

**The operating system you're using:**
OSX 10.15.3

**The output of `python --version`:**
Python 3.5.6 :: Anaconda, Inc.

### Additional context
When I pull the variable reference into the sql in a config block, it looks like the jinja is not being processed and it's failing when it runs something like `create schema if not exists TESTING_DEID.{{ var("project_name") }}_SOURCES`. It's likely this is user error and I'll create a separate issue after further testing, but figured it might be relevant to debugging this issue so just giving a heads up.

**Comment by beckjake** [comment]
context: We intentionally do not pass cli vars to dependencies (I even wrote a [comment](https://github.com/fishtown-analytics/dbt/blob/daff0badc82362d805bce0a2cc8a59701ab1fefb/core/dbt/config/runtime.py#L138) about it so I'd know it was intentional)!

At first I was certain that this is one of those cases where the docs are correct and what dbt does is absolutely wrong, but I'm having second thoughts. Fixing this (and I think we probably ought to) could be a breaking change for users who have a dependency using default vars:

Imagine this dependency:
```
name: my_dep
version: 1.0
config-version: 2

models:
  my_dep:
    tags: "{{ var('some_var', 'other_value') }}"
```

And this main project:
```
name: my_project
version: 1.0
config-version: 2

models:
  my-dep:
    tags: "{{ var('some_var', 'other_value') }}"
```

With the current behavior, `dbt run --vars "{some_var: my_tag}"` will result in the `my_dep` models having 2 tags: `"default_value"` and `"my_tag"`. Making vars available like the docs suggest would change that, now they would have just `"my_tag"`.

While this would be a small breaking change, maybe the general idea that CLI vars can't set vars in dependencies is correct. If that's the case, should a parent project's `vars` block be consulted before evaluating the dbt_project.yml for its dependencies, and the appropriate values passed along? Should it parse its own `vars` block first and apply those to the rest of the file?

**Comment by jtcohen6** [comment]
> If that's the case, should a parent project's `vars` block be consulted before evaluating the dbt_project.yml for its dependencies, and the appropriate values passed along? Should it parse its own `vars` block first and apply those to the rest of the file?

This is what feels right to me. The user will always have the greatest control over the parent project. Given the established convention of using `vars` for configurable project-level behavior, I think the parent `dbt_project.yml` should be a fully operational control center, able to override the default values of its dependencies.

When developing packages, we already try to namespace variables to avoid the risk of accidental overrides (a same-named variable operating differently across installed packages). Even then, it's still possible to set different values of that `var` for each package in the parent `dbt_project.yml`.

At first, I confused this issue for a different one, which is that installed packages cannot define their own values of `vars` in `dbt_project.yml` and have those values "pass up" when run by a parent package. That tripped me up [a few months ago](https://github.com/kristeligt-dagblad/dbt_ml/pull/1#issuecomment-643459355).
