### ISSUE TITLE
Installed Package Yields Unhandled Error due to Potentially Conflicting dbt_project.yml

### ISSUE THREAD

**Issue by curanaj** [dbt-labs/dbt-core#3190]
### Describe the bug
`dbt run -m dbt_artifacts` produces an unhandled error `'NoneType' has no attribute 'lower,'` which can not be traced back to any project-specific issue, but rather what seems to be an internal dbt error.

### Steps To Reproduce

1. Install [**dbt_artifacts**](https://hub.getdbt.com/tailsdotcom/dbt_artifacts/0.4.0/) with the default variables.
2. Run `dbt run-operation create_artifact_resources` to create the source tables.
3. Run/test any model locally to produce artifacts.
4. Populate the source tables locally by running `dbt run-operation upload_dbt_artifacts --args '{filenames: [run_results]}'` or through Airflow, either of which will dump the JSON contents.
5. Build the artifact models using the source tables by running `dbt run -m dbt_artifacts`.

### Expected behavior
`fct_dbt_run_results` and any other `fct_` tables should be produced as a result.

### Screenshots and log output
``` 
2021-03-23 19:22:11.008165 (Thread-1): Began running node model.dbt_artifacts.fct_dbt__run_results
2021-03-23 19:22:11.019692 (Thread-1): Acquiring new snowflake connection "model.dbt_artifacts.fct_dbt__run_results".
2021-03-23 19:22:11.050563 (Thread-1): Compiling model.dbt_artifacts.fct_dbt__run_results
2021-03-23 19:22:11.067615 (Thread-1): Finished collecting timing info
2021-03-23 19:22:11.068679 (Thread-1): Unhandled error while executing model.dbt_artifacts.fct_dbt__run_results
'NoneType' object has no attribute 'lower'
2021-03-23 19:22:11.069126 (Thread-1): 
Traceback (most recent call last):
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/task/base.py", line 344, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/task/base.py", line 281, in compile_and_execute
    ctx.node = self.compile(manifest)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/task/compile.py", line 32, in compile
    return compiler.compile_node(self.node, manifest, {})
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/compilation.py", line 502, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/compilation.py", line 407, in _compile_node
    node,
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 577, in get_rendered
    return render_template(template, ctx, node)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 528, in render_template
    return template.render(ctx)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 327, in __call__
    return self.call_macro(*args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 9, in template
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 734, in get_relation
    relations_list = self.list_relations(database, schema)
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 673, in list_relations
    if self._schema_is_cached(database, schema):
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/adapters/base/impl.py", line 295, in _schema_is_cached
    elif (database, schema) not in self.cache:
  File ".../.pyenv/versions/3.7.1/envs/tp-dbt/lib/python3.7/site-packages/dbt/adapters/cache.py", line 224, in __contains__
    return (lowercase(db), schema.lower()) in self.schemas
AttributeError: 'NoneType' object has no attribute 'lower'
2021-03-23 19:22:11.106215 (Thread-1): Finished running node model.dbt_artifacts.fct_dbt__run_results
 ```

### System information
**Which database are you using dbt with?**
- [X] snowflake

**The output of `dbt --version`:**
```
0.19.0
```

**The operating system you're using:**
```
macOS Catalina, Version 10.15.7
```

**The output of `python --version`:**
```
Python 3.7.1
```

**Comment by jtcohen6** [comment]
Hey @curanaj, I wasn't able to reproduce this error exactly, but I think I may have a start:

1. The `fct_dbt__run_results` model (where your error crops up) in the `dbt_artifacts` package dynamically grabs the set of environment variables from another model, via `dbt_utils.get_column_values()`, [here](https://github.com/tailsdotcom/dbt_artifacts/blob/40c90cecfc071fbaa0fc3f600c1cefcceadc4767/models/incremental/fct_dbt__run_results.sql#L3).
2. The `dbt_utils.get_column_values()` macro checks the relation cache / database to see whether the supplied `table` argument indeed exists, via `adapter.get_relation()`, [here](https://github.com/fishtown-analytics/dbt-utils/blob/ceb28497769c642cae7e3d5d18f1fe6bb253ef59/macros/sql/get_column_values.sql#L25-L27).
3. Under the hood, the `get_relation()` method calls `list_relation`, which calls `_schema_is_cached`, and so on. If the `get_relation()` method is passed `schema=None`, it returns the error you're seeing above:
```
Runtime Error
  'NoneType' object has no attribute 'lower'
```
Specifically, the `__contains__` instance method of the `RelationsCache` here:
https://github.com/fishtown-analytics/dbt/blob/77c10713a325d2bee91d1822951ce5d91ccc3278/core/dbt/adapters/cache.py#L217-L224

Now, why is yours an `AttributeError` rather than a `RuntimeError`? Why aren't you seeing the much nicer error that usually crops up when `get_column_values()` misses its target table?

```
Encountered an error:
Runtime Error
  Compilation Error in model fct_dbt__run_results (models/incremental/fct_dbt__run_results.sql)
    In get_column_values(): relation my_database.my_schema.stg_dbt__run_results_env_keys does not exist and no default value was provided.
```

I'm not sure!

To debug this further, could you share your full relevant config in `dbt_project.yml`, both the `vars` and `models` relating to `dbt_artifacts`?
