### ISSUE TITLE
ModuleNotFoundError: No module named 'dbt.context.manifest'

### ISSUE THREAD

**Issue by johnpkennedy** [dbt-labs/dbt-core#3531]
### Describe the bug
All dbt commands fail with this error:

```
% dbt --version
Traceback (most recent call last):
  File "/usr/local/bin/dbt", line 33, in <module>
    sys.exit(load_entry_point('dbt-core==0.19.2', 'console_scripts', 'dbt')())
  File "/usr/local/bin/dbt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 13, in <module>
    import dbt.task.run as run_task
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/compile.py", line 2, in <module>
    from .runnable import GraphRunnableTask
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 16, in <module>
    from dbt.task.base import ConfiguredTask
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/base.py", line 22, in <module>
    from dbt.adapters.factory import register_adapter
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/factory.py", line 20, in <module>
    from dbt.adapters.base.plugin import AdapterPlugin
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/base/__init__.py", line 6, in <module>
    from dbt.adapters.base.connections import BaseConnectionManager  # noqa
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/base/connections.py", line 18, in <module>
    from dbt.adapters.base.query_headers import (
  File "/usr/local/Cellar/dbt@0.19.2/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/base/query_headers.py", line 6, in <module>
    from dbt.context.manifest import generate_query_header_context
ModuleNotFoundError: No module named 'dbt.context.manifest'
```

### Steps To Reproduce

1. brew tap fishtown-analytics/dbt
2. brew install fishtown-analytics/dbt/dbt@0.19.2
3. dbt --version

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Traceback (most recent call last):
  File "/usr/local/bin/dbt", line 33, in <module>
    sys.exit(load_entry_point('dbt-core==0.19.2', 'console_scripts', 'dbt')())
  File "/usr/local/bin/dbt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 13, in <module>
    import dbt.task.run as run_task
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/compile.py", line 2, in <module>
    from .runnable import GraphRunnableTask
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/runnable.py", line 16, in <module>
    from dbt.task.base import ConfiguredTask
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/task/base.py", line 22, in <module>
    from dbt.adapters.factory import register_adapter
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/factory.py", line 20, in <module>
    from dbt.adapters.base.plugin import AdapterPlugin
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/base/__init__.py", line 6, in <module>
    from dbt.adapters.base.connections import BaseConnectionManager  # noqa
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/base/connections.py", line 18, in <module>
    from dbt.adapters.base.query_headers import (
  File "/usr/local/Cellar/dbt/0.19.2_1/libexec/lib/python3.8/site-packages/dbt/adapters/base/query_headers.py", line 6, in <module>
    from dbt.context.manifest import generate_query_header_context
ModuleNotFoundError: No module named 'dbt.context.manifest'
```

**The operating system you're using:**
macOS Big Sur 11.4

**The output of `python --version`:**

```
% python --version
Python 2.7.16
% python3 --version
Python 3.9.6
```

### Additional context

Brew has both `python@3.8` and `python@3.9` installed.

**Comment by jtcohen6** [comment]
@johnpkennedy It definitely sounds like something went awry while installing dbt.

Could you try:
1. Reinstalling with brew:
```
brew untap fishtown-analytics/dbt --force
brew tap dbt-labs/dbt
brew reinstall dbt
```
2. Installing in a virtual environment with pip:
```
python3 -m venv env
source env/bin/activate
pip install dbt-redshift
```

**Comment by johnpkennedy** [comment]
Hi @jtcohen6 - Thanks for responding. 

Over the weekend, I tried a number of combinations to get this working. I did try the steps you suggested and encountered the same problem.

I suspect this is related to Python 3.9. I have two other brew packages (ansible and awscli) that now depend on python@3.9

I was able to get this working by doing this:
1) Temporarily uninstalling python@3.9 via brew
2) Set up a virtual environment with pip. This guaranteed I was used python 3.8.
3) Reinstalled python@3.9 so my other packages would work.

Note that until now, I've successfully installed and used dbt via brew multiple times for approx 2 years. This is the first time, I've encountered something like this.

**Comment by jtcohen6** [comment]
@johnpkennedy It's possible this is related to py39. There are dependencies of `dbt-snowflake==0.19.2` that are incompatible with py39, but `dbt-core==0.19.2` is perfectly compatible with it, and that's where you seem to be getting an import error. We've seen many issues about py39 compatibility, but never with a `ModuleNotFoundError ` error like you're experiencing.
