### ISSUE TITLE
[Bug] dbt errors should include traceback

### ISSUE THREAD

**Issue by thomasaarholt** [dbt-labs/dbt-core#4522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The errors produced by dbt aren't very useful on their own. It would be great if we got the full traceback. As an example, here is the output after bumping some versions in packages.yml:
```
❯ dbt deps
15:26:54  Running with dbt=1.0.0
15:27:39  Encountered an error:
argument of type 'NoneType' is not iterable
```

### Expected Behavior

```
❯ dbt deps
15:26:54  Running with dbt=1.0.0
15:27:39  Encountered an error:
***
Full python traceback
argument of type 'NoneType' is not iterable
***
```

### Environment

```markdown
- OS: macOS 12.0.1
- Python: 3.9.9
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by gshank** [comment]
This happens for Python errors, which may happen in a codepath in which we are not catching errors. It would definitely be better to catch errors at a top level and provide more information. I'll do some more investigation into this.

**Comment by gshank** [comment]
This is definitely worth doing.

**Comment by thomasaarholt** [comment]
I did a bit of reading. It looks like you should easily be able to output the full traceback using `print(traceback.format_exc())`. Here's an example:

```python
import traceback

def func3():
    raise ValueError("First Error here")

def func2():
    return func3()

def func1():
    return func2()

try:
    func1()
except ValueError as e:
    try:
        raise AttributeError("Second Error here")
    except AttributeError as f:
        print("Printing just `e`")
        print(e)
        print("\n\n")
        print("Printing just `f`")
        print(f)
        print("\n\n")
        print("Printing full traceback")
        print(traceback.format_exc())

------------------
Printing just `e`
First Error here



Printing just `f`
Second Error here



Printing full traceback
Traceback (most recent call last):
  File "/var/folders/yt/z22_f0896l74f8gs3_20vc_00000gn/T/ipykernel_65046/227585551.py", line 13, in <module>
    func1()
  File "/var/folders/yt/z22_f0896l74f8gs3_20vc_00000gn/T/ipykernel_65046/227585551.py", line 10, in func1
    return func2()
  File "/var/folders/yt/z22_f0896l74f8gs3_20vc_00000gn/T/ipykernel_65046/227585551.py", line 7, in func2
    return func3()
  File "/var/folders/yt/z22_f0896l74f8gs3_20vc_00000gn/T/ipykernel_65046/227585551.py", line 4, in func3
    raise ValueError("First Error here")
ValueError: First Error here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/yt/z22_f0896l74f8gs3_20vc_00000gn/T/ipykernel_65046/227585551.py", line 16, in <module>
    raise AttributeError("Second Error here")
AttributeError: Second Error here
```

**Comment by nathaniel-may** [comment]
First discussion:
- Will likely need to add multiple try-catch blocks early in the process to catch everything and report them.
- Will need to decide when tracebacks are written to the log and how that interacts with current flags i.e. DEBUG. <- this is a discussion ahead of the work
- May require a change to RPC code, and core task initialization
- Because this work might be cross team, we should split RPC work into a followup ticket, so that this ticket only encompasses core work.

Related Issue: #4844

**Comment by iknox-fa** [comment]
@nathaniel-may , @jtcohen6, @leahwicz 
This ticket was part of our BLG meeting today and there's quite a bit at play here (logbook, threading(?), flags, etc).
Because of the uncertainty of exactly what a doing-it-the-right-way solution might be we're converting this to a spike.

**Comment by iknox-fa** [comment]
@nathaniel-may I was under the impression that logbook is part of the conditions that cause these errors to appear without tracebacks.  Specifically uncaught python errors that occur in non-main threads only go to logbook, and this is the result.

That said I may be way off base (I haven't looked at this stuff in ages).  Do you have any further context?

**Comment by nathaniel-may** [comment]
@iknox-fa since 1.0.0 core never uses logbook unless you opt into it with an environment variable. Cloud does this for legacy integration reasons though. Since this ticket isn't for getting these tracebacks in cloud, I don't think we should bother investigating logbook errors.

**Comment by thomasaarholt** [comment]
Remain open.
