### ISSUE TITLE
[CT-49] [Bug] dbt deps does not handle/retry on a malformed response from hub

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt-core#4577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If in the process of running `dbt deps` dbt receives a malformed response from `hub.getdbt.com` deps will fail:

```
Traceback (most recent call last):
  File "/usr/src/app/sinter/clients/dbt.py", line 1200, in call
    dbt_main.handle(command + extra_args)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 152, in handle
    res, success = handle_and_check(args)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 192, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 246, in run_from_args
    results = task.run()
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/deps.py", line 56, in run
    final_deps = resolve_packages(packages, self.config)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/resolver.py", line 135, in resolve_packages
    target = final[package].resolved().fetch_metadata(config, renderer)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/registry.py", line 121, in resolved
    self._check_in_index()
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/registry.py", line 92, in _check_in_index
    if self.package not in index:
TypeError: argument of type 'NoneType' is not iterable
```

while attempting to parse the JSON response which, presumably, is bad.

### Expected Behavior

- Log the bad JSON so that we know what hub sent
- Retry similar to how retry happens for failures to connect and for empty responses

**Comment by emmyoop** [comment]
@barberscott thanks again for the detailed issue!  This is a result of a big of a bug associated with our retry logic.

We should be checking here if `resp.json()` is `None` not just the `resp` object.

https://github.com/dbt-labs/dbt-core/blob/7798f932a09a12f1993ea9cb781a20707383df96/core/dbt/clients/registry.py#L36-L39

If it is `None` we should retry.

This issue is part of our next release (1.0.2) and I'm actively working on it!  Similar to #4579 I'm going to need to think a bit more on what, if anything, should be logged in this case.  Possibly the entire response?

**Comment by leahwicz** [comment]
Backport here: #4649
