### ISSUE TITLE
[Bug] <title>AssertionError: too many messages received before initilization

### ISSUE THREAD

**Issue by sireeshachowdam11** [dbt-labs/dbt-core#4706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141
Traceback (most recent call last):
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\handlers.py", line 216, in handle
    self.emit(record)
  File "C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\logger.py", line 472, in emit
    assert len(self._msg_buffer) < self._bufmax, \
AssertionError: too many messages received before initilization!
Logged from file C:\Users\Chowdam Sireesha.WINDOWS-INSTANC\AppData\Local\Programs\Python\Python310\lib\site-packages\logbook\concurrency.py, line 141

2022-02-10 06:51:15.802568 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.812333 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.820140 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.822100 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.826008 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.829910 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.831870 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.835777 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.838700 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.848470 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.907075 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.909987 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.911933 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.915840 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.917794 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.918791 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.937339 (MainThread): getName() is deprecated, get the name attribute instead
2022-02-10 06:51:15.950011 (MainThread): currentThread() is deprecated, use current_thread() instead
2022-02-10 06:51:15.956857 (MainThread): getName() is deprecated, get the name attribute instead

### Environment

```markdown
- OS: using on Windows VM
- Python:
- dbt:
C:\Users\Chowdam Sireesha.WINDOWS-INSTANC>dbt --version
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 1.0.0
  - sqlserver: 1.0.0
  - synapse: 1.0.1

C:\Users\Chowdam Sireesha.WINDOWS-INSTANC>python --version
Python 3.10.2
```

### What database are you using dbt with?

snowflake

### Additional Context

when giving the dbt run command getting an errors like above.

**Comment by jtcohen6** [comment]
Thanks for the report @sireeshachowdam11! This is due to the fact that `dbt-core` does not yet officially support python 3.10:
https://github.com/dbt-labs/dbt-core/blob/72ecd1ce74641ea0675399f251564cc7f7fbf974/core/setup.py#L84-L86

We're planning to add that support for the next minor version (https://github.com/dbt-labs/dbt-core/issues/4562). In the meantime, I'd ask you to use Python 3.9 in your local environment instead. I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/4537 (+ https://github.com/dbt-labs/dbt-core/issues/4576).
