### ISSUE TITLE
[Bug] dbt fails with the only error message being `Encountered an error:` 

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-core#4844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When doing a `dbt run` the following message is displayed in the CLI:
```
Running with dbt=1.0.1
Encountered an error:
```
There is no additional detail on what the problem is.
Running dbt with `--debug` shows additional errors (attached below)

After having seen some messages in the debug log about partial parsing, we did a `dbt clean` which then showed us an error with a model being referenced but not found in the project. After the error was fixed `dbt run` worked as expected.

### Expected Behavior

dbt should return an actual error to guide the user on how to solve the issue

### Relevant log output

```shell
10:15:55.231752 [info ] [MainThread]: Running with dbt=1.0.1
10:15:55.231752 [debug] [MainThread]: running dbt with arguments {'debug': True, 'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse':
True, 'static_parser': True, 'profiles_dir': 'C:\\user_path\\.dbt', 'send_anonymous_usage_stats': True, 'event_buffer_size': 100000, 'quiet': False, 'which': 'run', 'rpc_method':
'run', 'indirect_selection': 'eager'}
10:15:55.231752 [debug] [MainThread]: Tracking: tracking
10:15:55.231752 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x057FDCB8>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x057FDCE8>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x057FDD18>]}
10:15:55.316961 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 1 files added, 1 files changed.
10:15:55.317958 [debug] [MainThread]: Partial parsing: added file: data_warehouse://models\DW_folder\fact1.sql
10:15:55.318959 [debug] [MainThread]: Partial parsing: updated file: data_warehouse://models\DW_folder\dim1.sql
10:15:55.337955 [debug] [MainThread]: 1699: static parser successfully parsed DW_folder\fact1.sql
10:15:55.355972 [debug] [MainThread]: 1603: static parser failed on DW_folder\dim1.sql
10:15:55.366508 [debug] [MainThread]: Flushing usage events
10:15:55.807349 [error] [MainThread]: Encountered an error:
10:15:55.807349 [debug] [MainThread]: Traceback (most recent call last):
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\main.py", line 187, in handle_and_check
    task, res = run_from_args(parsed)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\main.py", line 234, in run_from_args
    results = task.run()
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\task\runnable.py", line 433, in run
    self._runtime_initialize()
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\task\runnable.py", line 150, in _runtime_initialize
    super()._runtime_initialize()
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\task\runnable.py", line 90, in _runtime_initialize
    self.load_manifest()
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\task\runnable.py", line 79, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\manifest.py", line 218, in get_full_manifest
    manifest = loader.load()
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\manifest.py", line 348, in load
    self.parse_project(
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\manifest.py", line 469, in parse_project
    parser.parse_file(block)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\base.py", line 391, in parse_file
    self.parse_node(file_block)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\base.py", line 365, in parse_node
    self.render_update(node, config)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\models.py", line 147, in render_update
    super().render_update(node, config)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\base.py", line 340, in render_update
    context = self.render_with_context(node, config)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\parser\base.py", line 237, in render_with_context
    get_rendered(parsed_node.raw_sql, context, parsed_node, capture_macros=True)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\clients\jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\clients\jinja.py", line 526, in render_template
    return template.render(ctx)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\jinja2\environment.py", line 1088, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "<template>", line 53, in root
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\jinja2\sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\jinja2\runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "c:\user_path\documents\dbt-project\dbt-env\lib\site-packages\dbt\context\base.py", line 358, in _return
    raise MacroReturn(data)
dbt.exceptions.MacroReturn
```

### Environment

```markdown
- OS: Windows-2012ServerR2
- Python: 3.8.5
- dbt: 1.0.1
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Usign the community adapter sql-server

**Comment by emmyoop** [comment]
This is definitely not the experience we want @b-per.  Thank you for taking the time to write up your experience.  Over in #4522 there's a similar issue where we're working to bubble up the actual errors to give more useful information when there is an issue.

I'm going to close this issue as a duplicate of #4522 to keep the conversation over there.  Feel free to leave a comment over there if you have any more to add!
