### ISSUE TITLE
[CT-432] [Bug] tarfile.open() not working properly

### ISSUE THREAD

**Issue by itz-vp** [dbt-labs/dbt-core#4966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

f = tarfile.open("/model.tar.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/veera/anaconda3/envs/zspeech_repo/lib/python3.8/tarfile.py", line 1608, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

### Expected Behavior

Read successfully.

### Environment

```markdown
- OS: ubuntu
- Python: 3.8
- dbt:
```

**Comment by itz-vp** [comment]
File exists. Verified.

**Comment by jtcohen6** [comment]
@itz-vp Did you run into this error when running `dbt deps`? Could you provide any more lines from the error message / traceback?

**Comment by itz-vp** [comment]
(zspeech_libri) veera@gpu56:/mnt/veera/zspeech_libri/zspeech$ pip install webrtcvad
Collecting webrtcvad
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 1105, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 1049, in frombuf
    raise InvalidHeaderError("bad checksum")
tarfile.InvalidHeaderError: bad checksum

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 140, in __bool__
    return any(self)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
    super().__init__(
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 249, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py", line 256, in unpack_file
    untar_file(filename, location)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py", line 181, in untar_file
    tar = tarfile.open(filename, mode, encoding="utf-8")
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 1674, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 1651, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/home/veera/anaconda3/envs/zspeech_libri/lib/python3.8/tarfile.py", line 2330, in next
    raise ReadError(str(e))
tarfile.ReadError: bad checksum

**Comment by jtcohen6** [comment]
@itz-vp I'm a bit confused — I don't see anything in that trace related to dbt. Did you mean to open this issue in https://github.com/wiseman/py-webrtcvad, by any chance?
