### ISSUE TITLE
[CT-526] [Bug] New version of snowflake docker image is broken

### ISSUE THREAD

**Issue by alexrosenfeld10** [dbt-labs/dbt-core#5122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I target `ghcr.io/dbt-labs/dbt-snowflake:1.0.latest`. I ran a new build today and I get this in an infinite loop in my CICD job:

```text
2022-04-20T22:45:35.206Z] [91mTraceback (most recent call last):
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 216, in handle
[2022-04-20T22:45:35.206Z]     self.emit(record)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/dbt/logger.py", line 467, in emit
[2022-04-20T22:45:35.206Z]     super().emit(record)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 836, in emit
[2022-04-20T22:45:35.206Z]     msg = self.format(record)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/dbt/logger.py", line 454, in format
[2022-04-20T22:45:35.206Z]     msg = super().format(record)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 195, in format
[2022-04-20T22:45:35.206Z]     return self.formatter(record, self)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 387, in __call__
[2022-04-20T22:45:35.206Z]     line = self.format_record(record, handler)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 371, in format_record
[2022-04-20T22:45:35.206Z]     return self._formatter.format(record=record, handler=handler)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/helpers.py", line 283, in __get__
[2022-04-20T22:45:35.206Z]     value = self.func(obj)
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/base.py", line 675, in thread_name
[2022-04-20T22:45:35.206Z]     return thread_get_name()
[2022-04-20T22:45:35.206Z]   File "/usr/local/lib/python3.10/site-packages/logbook/concurrency.py", line 141, in thread_get_name
[2022-04-20T22:45:35.207Z]     return currentThread().getName()
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/threading.py", line 1442, in currentThread
[2022-04-20T22:45:35.207Z]     warnings.warn('currentThread() is deprecated, use current_thread() instead',
[2022-04-20T22:45:35.207Z] RecursionError: maximum recursion depth exceeded
[2022-04-20T22:45:35.207Z] [0m[91m
[2022-04-20T22:45:35.207Z] During handling of the above exception, another exception occurred:
[2022-04-20T22:45:35.207Z] 
[2022-04-20T22:45:35.207Z] [0m[91mTraceback (most recent call last):
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 216, in handle
[2022-04-20T22:45:35.207Z]     self.emit(record)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/dbt/logger.py", line 467, in emit
[2022-04-20T22:45:35.207Z]     super().emit(record)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 836, in emit
[2022-04-20T22:45:35.207Z]     msg = self.format(record)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/dbt/logger.py", line 454, in format
[2022-04-20T22:45:35.207Z]     msg = super().format(record)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 195, in format
[2022-04-20T22:45:35.207Z]     return self.formatter(record, self)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 387, in __call__
[2022-04-20T22:45:35.207Z]     line = self.format_record(record, handler)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 371, in format_record
[2022-04-20T22:45:35.207Z]     return self._formatter.format(record=record, handler=handler)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/helpers.py", line 283, in __get__
[2022-04-20T22:45:35.207Z]     value = self.func(obj)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/base.py", line 675, in thread_name
[2022-04-20T22:45:35.207Z]     return thread_get_name()
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/site-packages/logbook/concurrency.py", line 141, in thread_get_name
[2022-04-20T22:45:35.207Z]     return currentThread().getName()
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/threading.py", line 1442, in currentThread
[2022-04-20T22:45:35.207Z]     warnings.warn('currentThread() is deprecated, use current_thread() instead',
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/warnings.py", line 109, in _showwarnmsg
[2022-04-20T22:45:35.207Z]     sw(msg.message, msg.category, msg.filename, msg.lineno,
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/compat.py", line 288, in showwarning
[2022-04-20T22:45:35.207Z]     logbook.dispatch_record(record)
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/site-packages/logbook/base.py", line 1122, in dispatch_record
[2022-04-20T22:45:35.207Z]     _default_dispatcher.call_handlers(record)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/base.py", line 999, in call_handlers
[2022-04-20T22:45:35.207Z]     if handler.handle(record) and not handler.bubble:
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 218, in handle
[2022-04-20T22:45:35.207Z]     self.handle_error(record, sys.exc_info())
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 297, in handle_error
[2022-04-20T22:45:35.207Z]     traceback.print_exception(*(exc_info + (None, sys.stderr)))
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/traceback.py", line 119, in print_exception
[2022-04-20T22:45:35.207Z]     te = TracebackException(type(value), value, tb, limit=limit, compact=True)
[2022-04-20T22:45:35.207Z]   File "/usr/local/lib/python3.10/traceback.py", line 502, in __init__
[2022-04-20T22:45:35.207Z]     self.stack = StackSummary.extract(
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/traceback.py", line 383, in extract
[2022-04-20T22:45:35.207Z]     f.line
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/traceback.py", line 306, in line
[2022-04-20T22:45:35.207Z]     self._line = linecache.getline(self.filename, self.lineno)
[2022-04-20T22:45:35.207Z] [0m[91m  File "/usr/local/lib/python3.10/linecache.py", line 30, in getline
```

### Expected Behavior

Things work without error. Targeting `ghcr.io/dbt-labs/dbt-snowflake:1.0.0` resolves the issue.

### Environment

```markdown
- OS: ghcr.io/dbt-labs/dbt-snowflake:1.0.latest
- Python:
- dbt:
```

**Comment by alexrosenfeld10** [comment]
cc @trunyan

**Comment by ChenyuLInx** [comment]
@alexrosenfeld10  sorry to hear that and thanks for opening the issue! It might have to do with a base docker image update we did previously. We are taking a look at it.
Some question to help me understand the situation more:
- Are you using the docker image to run a `dbt build`?
- Have you always been using python 3.10

**Comment by alexrosenfeld10** [comment]
Here's my dockerfile:

```Docker
# There is an issue with dbt-snowflake:1.0.1 that breaks deployments
# dbt-snowflake:1.0.0 is the last known good version until 1.0.1 is investigated 
FROM ghcr.io/dbt-labs/dbt-snowflake:1.0.0

# We have to move out of the default dir because of https://github.com/dbt-labs/dbt-core/issues/4784
WORKDIR /usr/disc-dbt
COPY . .
RUN dbt deps

# warnings as errors - https://docs.getdbt.com/reference/global-configs#warnings-as-errors
# further arguments are passed in the kubernetes config as "args"
ENTRYPOINT ["dbt","--log-format", "json", "--warn-error", "run"]
```

**Comment by ChenyuLInx** [comment]
Hey @alexrosenfeld10, glad to see that you have the temp solution!
RCA for the issue:
We run our docker release through `main` branch, the base image there got updated to `python3.10` while the support for 3.10 is not on 1.0.latest. So there was a mismatch.
I just released the docker image for `dbt-snowflake` using the correct python [base image](https://github.com/dbt-labs/dbt-core/tree/docker-release-pre-1.1) and you should be able to use 1.0.latest again.

**Comment by alexrosenfeld10** [comment]
Thanks @ChenyuLInx , I'll give that a try.

**Comment by alexrosenfeld10** [comment]
I'm getting the same issue targeting latest still

**Comment by ChenyuLInx** [comment]
@alexrosenfeld10  Sounds good! It might be that you didn't manually pull the latest image? Since they are having the same tag, docker won't pull it for you if there's already one locally. The latest image ID is `1118a8935bb8`.

**Comment by alexrosenfeld10** [comment]
@ChenyuLInx here's my CI job output:

```
10:45:57  + docker build -t my-org.jfrog.io/my-org/my-dbt-project:2022-04-26.141-9da61da-rel -f Dockerfile .
10:45:57  Sending build context to Docker daemon  1.108MB

10:45:57  Step 1/5 : FROM ghcr.io/dbt-labs/dbt-snowflake:1.0.latest
10:45:57   ---> 1882555bde73
10:45:57  Step 2/5 : WORKDIR /usr/my-dbt-project
10:45:58   ---> Running in 178e5d9dcc79
10:45:59  Removing intermediate container 178e5d9dcc79
10:45:59   ---> ef008ccde307
10:45:59  Step 3/5 : COPY . .
10:46:01   ---> 3c7669613a84
10:46:01  Step 4/5 : RUN dbt deps
10:46:01   ---> Running in d3b9b544f857
10:46:07  [91mTraceback (most recent call last):
10:46:07    File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 216, in handle
10:46:07      self.emit(record)
10:46:07    File "/usr/local/lib/python3.10/site-packages/dbt/logger.py", line 467, in emit
10:46:07      super().emit(record)
10:46:07    File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 836, in emit
10:46:07      msg = self.format(record)
10:46:07    File "/usr/local/lib/python3.10/site-packages/dbt/logger.py", line 454, in format
10:46:07      msg = super().format(record)
10:46:07    File "/usr/local/lib/python3.10/site-packages/logbook/handlers.py", line 195, in format
```

**Comment by alexrosenfeld10** [comment]
I'm going to try building with 1.0.1 as the target explicitly

**Comment by alexrosenfeld10** [comment]
1.0.1 seems to build just fine

**Comment by dschneiderch** [comment]
I get the same error running dbt list. I cloned the dbt-core repo this morning and built the docker image for bigquery.
I then pulled ghcr.io/dbt-labs/dbt-bigquery:latest and that works fine.

**Comment by ChenyuLInx** [comment]
@alexrosenfeld10  Glad to hear that 1.0.1 works fine.

My guess is that somehow the 1.0.latest on you side is still pulling the previous image.
> 10:45:57  Step 1/5 : FROM ghcr.io/dbt-labs/dbt-snowflake:1.0.latest
10:45:57   ---> 1882555bde73

I am assuming the second line is the docker image ID and it is different from the 1.0.latest ID I got on my side. Images specified `latest` requires manual docker pull to get the latest.

**Comment by ChenyuLInx** [comment]
@dschneiderch  That error is caused by dbt is running with python3.10 but not using the later version of code where we started supporting 3.10. [This](https://github.com/dbt-labs/dbt-core/commit/c808c76da1b911459884cdcaf59b3d8f4e8d9b07) is the change I made to release that workable `ghcr.io/dbt-labs/dbt-bigquery` image.

**Comment by alexrosenfeld10** [comment]
@ChenyuLInx I agree, you're right. I'll close this out.
