### ISSUE TITLE
[CT-771] [Bug] fail to get dep from git subfolder

### ISSUE THREAD

**Issue by Jaxing** [dbt-labs/dbt-core#5401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following dependency:

```
  - git: "https://github.com/dbt-labs/dbt-labs-experimental-features.git"
    subdirectory: "materialized-views"
    revision: 0.0.1
```

and I get this error:

```
07:27:54  Running with dbt=1.1.1
07:27:57  Encountered an error:
Error checking out spec='None' for repo https://github.com/dbt-labs/dbt-labs-experimental-features.git
Cloning into '2963123b880a59a367b95ce4e726ff25'...
fatal: cannot change to 'https://github.com/dbt-labs/dbt-labs-experimental-features.git': No such file or directory
error: failed to initialize sparse-checkout
```

My guess is that this is because it only tries to clone the materialized folder but some goes wrong along the way.

### Expected Behavior

I expect that it should be able to download only the necessary package.

### Steps To Reproduce

Add this to you packages:

```
  - git: "https://github.com/dbt-labs/dbt-labs-experimental-features.git"
    subdirectory: "materialized-views"
    revision: 0.0.1
```
run dbt deps

### Environment

```markdown
- OS:Ubuntu 20.04
- Python: Python 3.8.12
- dbt:

Core:
  - installed: 1.1.1
  - latest:    1.1.1 - Up to date!

Plugins:
  - bigquery: 1.1.0 - Up to date!
  - postgres: 1.1.1 - Up to date!
```
```


### What database are you using dbt with?

bigquery

### Additional Context

_No response_

**Comment by leahwicz** [comment]
@Jaxing this works for me with `1.1.1`-
```
19:00:29  Running with dbt=1.1.1
19:00:32  Installing https://github.com/dbt-labs/dbt-labs-experimental-features.git
19:00:33    Installed from revision 0.0.1
19:00:33     and subdirectory materialized-views
```

packages.yml
```
packages:
  - git: "https://github.com/dbt-labs/dbt-labs-experimental-features.git"
    subdirectory: "materialized-views"
    revision: 0.0.1
```

Could you run with debug enabled to see if anything else more useful is displayed? `dbt -d deps`

**Comment by Jaxing** [comment]
@leahwicz I get this

```

============================== 2022-06-23 06:45:13.194482 | 3ab05e78-cd01-41b3-81ff-689a3a2e5b81 ==============================
06:45:13.194495 [info ] [MainThread]: Running with dbt=1.1.1
06:45:13.195063 [debug] [MainThread]: running dbt with arguments {'debug': True, 'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/home/jesper/.dbt', 'send_anonymous_usage_stats': True, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'which': 'deps', 'rpc_method': 'deps', 'indirect_selection': 'eager'}
06:45:13.195578 [debug] [MainThread]: Tracking: tracking
06:45:13.241706 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f39a09fbaf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f39a09fbc70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f39a09fb640>]}
06:45:13.243603 [debug] [MainThread]: Set downloads directory='/tmp/dbt-downloads-_93liczp'
06:45:13.244764 [debug] [MainThread]: Making package index registry request: GET https://hub.getdbt.com/api/v1/index.json
06:45:13.427111 [debug] [MainThread]: Response from registry index: GET https://hub.getdbt.com/api/v1/index.json 200
06:45:13.428197 [debug] [MainThread]: Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json
06:45:13.544276 [debug] [MainThread]: Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json 200
06:45:13.601543 [debug] [MainThread]:   Subdirectory specified: materialized-views, using sparse checkout.
06:45:13.602507 [debug] [MainThread]: Executing "git --version"
06:45:13.612803 [debug] [MainThread]: STDOUT: "b'git version 2.25.1\n'"
06:45:13.613729 [debug] [MainThread]: STDERR: "b''"
06:45:13.615313 [debug] [MainThread]: Executing "git clone --depth 1 --filter=blob:none --sparse https://github.com/dbt-labs/dbt-labs-experimental-features.git 2963123b880a59a367b95ce4e726ff25"
06:45:13.633727 [debug] [MainThread]: STDOUT: "b''"
06:45:13.634818 [debug] [MainThread]: STDERR: "b"Cloning into '2963123b880a59a367b95ce4e726ff25'...\nfatal: cannot change to 'https://github.com/dbt-labs/dbt-labs-experimental-features.git': No such file or directory\nerror: failed to initialize sparse-checkout\n""
06:45:13.635863 [debug] [MainThread]: command return code=1
06:45:13.641772 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f39a09fb640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f39a0944550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f39a0944790>]}
06:45:13.642618 [debug] [MainThread]: Flushing usage events
06:45:14.079076 [error] [MainThread]: Encountered an error:
Error checking out spec='None' for repo https://github.com/dbt-labs/dbt-labs-experimental-features.git
Cloning into '2963123b880a59a367b95ce4e726ff25'...
fatal: cannot change to 'https://github.com/dbt-labs/dbt-labs-experimental-features.git': No such file or directory
error: failed to initialize sparse-checkout
06:45:14.084030 [debug] [MainThread]: Traceback (most recent call last):
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/clients/git.py", line 65, in clone
    result = run_cmd(cwd, clone_cmd, env={"LC_ALL": "C"})
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/clients/system.py", line 434, in run_cmd
    raise dbt.exceptions.CommandResultError(cwd, cmd, proc.returncode, out, err)
dbt.exceptions.CommandResultError: Got a non-zero returncode running: ['/usr/bin/git', 'clone', '--depth', '1', '--filter=blob:none', '--sparse', 'https://github.com/dbt-labs/dbt-labs-experimental-features.git', '2963123b880a59a367b95ce4e726ff25']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/main.py", line 191, in handle_and_check
    task, res = run_from_args(parsed)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/main.py", line 238, in run_from_args
    results = task.run()
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/task/deps.py", line 56, in run
    final_deps = resolve_packages(packages, self.config)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/deps/resolver.py", line 131, in resolve_packages
    target = final[package].resolved().fetch_metadata(config, renderer)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/deps/base.py", line 86, in fetch_metadata
    self._cached_metadata = self._fetch_metadata(project, renderer)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/deps/git.py", line 93, in _fetch_metadata
    path = self._checkout()
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/deps/git.py", line 79, in _checkout
    dir_ = git.clone_and_checkout(
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/clients/git.py", line 137, in clone_and_checkout
    _, err = clone(
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/clients/git.py", line 67, in clone
    _raise_git_cloning_error(repo, revision, exc)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/clients/git.py", line 37, in _raise_git_cloning_error
    bad_package_spec(repo, revision, stderr)
  File "/home/jesper/anaconda3/envs/py-38/lib/python3.8/site-packages/dbt/exceptions.py", line 708, in bad_package_spec
    raise InternalException(scrub_secrets(msg, env_secrets()))
dbt.exceptions.InternalException: Error checking out spec='None' for repo https://github.com/dbt-labs/dbt-labs-experimental-features.git
Cloning into '2963123b880a59a367b95ce4e726ff25'...
fatal: cannot change to 'https://github.com/dbt-labs/dbt-labs-experimental-features.git': No such file or directory
error: failed to initialize sparse-checkout
```

**Comment by Jaxing** [comment]
I'm also using vscode, but can't remember if I use the built-in terminal for this or not, will try on my native terminal on Monday.

**Comment by Jaxing** [comment]
It's not working from my normal terminal either. I'm using zsh if that could matter?
I'm also running **git 2.25.1**.

**Comment by jtcohen6** [comment]
I believe this is indeed an issue with git 2.25.1. We were seeing the same error with the same git version over in https://github.com/dbt-labs/dbt-labs-experimental-features/issues/25.

@Jaxing Could you try upgrading to a newer version of `git`? That should resolve the issue.

### Update

git v2.25 added support for sparse checkouts, which is why we document and encode it as the minimum requirement:

https://github.com/dbt-labs/dbt-core/blob/d5608dca322c63f1a894174b1f280ae55a217ab8/core/dbt/clients/git.py#L49-L54

https://docs.getdbt.com/docs/building-a-dbt-project/package-management#project-subdirectories

Given that we know 2.25.1 is incompatible, let's find the _real_ minimum working version, and update the requirement in both places.

**Comment by Jaxing** [comment]
Thanks I'll try that.
If someone else runs into this issue I had to add gits PPA to be able to update the verison beyond 2.25.1
```
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

**Comment by Jaxing** [comment]
Updating the version to 2.37 works and seems to be the only version that is available for ubuntu20.04 on git-core/ppa https://launchpad.net/~git-core/+archive/ubuntu/ppa

**Comment by leahwicz** [comment]
Thanks all! Just to summarize the solution here as I close out the issue is that for Ubuntu 20.04, you need to use `git` version 2.37 and the instructions on how to do that are in an above comment
