### ISSUE TITLE
[CT-1020] [Bug] In python models, `dbt.source`, `dbt.ref` doesn't work with multi part names

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-core#5634]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Following the steps:
- get a Jaffle shop dbt project
- configured dbt_project.yml to point to my snowflake
- successfully created a sql staging model and ran it
  ```sql
   select * from {{ source('jaffle_shop', 'orders')}}
  ```
- error trying to implement a python staging model
  ```python
  def model(dbt, session):
      dbt.config(
          materialized='table'
      )
      df = dbt.source("jaffle_shop", "customers")
      
      return df
  ```
Error message
```
19:29:35  Database Error in model stg_jaffle_shop__customers (models/staging/stg_jaffle_shop__customers.py)
19:29:35    100357 (P0000): Python Interpreter Error:
19:29:35    Traceback (most recent call last):
19:29:35      File "_udf_code.py", line 84, in main
19:29:35      File "_udf_code.py", line 9, in model
19:29:35    TypeError: <lambda>() takes 1 positional argument but 2 were given
19:29:35     in function STG_JAFFLE_SHOP__CUSTOMERS__DBT_SP with handler main
```

### Expected Behavior

Run without error

### Steps To Reproduce

See Behavior section

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Which database adapter are you using with dbt?

snowflake

**Comment by ChenyuLInx** [comment]
This is because when we implement the lambda function, we made it only allow 1 argument instead of arbitrary at 
https://github.com/dbt-labs/dbt-core/blob/4d6208be6464a48a078dd8000ae6c29d8d7a42ce/core/dbt/include/global_project/macros/python_model/python.sql#L72-L77
The fix should just modify the lambda function to something like
```python
lambda *args: source(*args, dbt_load_df_function=load_df_function)
```
