### ISSUE TITLE
[CT-1041] python model was not found when dbt run

### ISSUE THREAD

**Issue by ericwijaya001** [dbt-labs/dbt-core#5657]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Python model can't be run

### Expected Behavior

model from python can be run

### Steps To Reproduce

# config.yml
version: 2

models:
  - name: cleaning_join_model
    description: cleaning join model pake pandas
    
    config:
      materialized: table
      tags: ['python']

-- cleaned_join_model.sql
select * 
from {{ ref('cleaning_join_model') }}

# cleaning_join_model.py
def model(dbt, session):  
    join_model_df = dbt.ref("join_model")
    # print(join_model_df.shape[0])
    join_model_df = join_model_df[join_model_df['hash'].notna()]
    # print(join_model_df.shape[0])    
    return join_model_df

There is no problem with join_model.sql because join_model can be executed and the table already appears in the database

### Relevant log output

```shell
07:20:58  Running with dbt=1.2.0
07:20:58  Unable to do partial parsing because a project config has changed
07:21:00  [WARNING]: Did not find matching node for patch with name 'cleaning_join_model' in the 'models' section of file 'models\config.yml'
Traceback (most recent call last):
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\main.py", line 192, in handle_and_check
    task, res = run_from_args(parsed)
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\main.py", line 239, in run_from_args
    results = task.run()
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\task\runnable.py", line 451, in run
    self._runtime_initialize()
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\task\runnable.py", line 159, in _runtime_initialize
    super()._runtime_initialize()
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\task\runnable.py", line 92, in _runtime_initialize
    self.load_manifest()
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\task\runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\parser\manifest.py", line 219, in get_full_manifest
    manifest = loader.load()
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\parser\manifest.py", line 391, in load
    self.process_refs(self.root_project.project_name)
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\parser\manifest.py", line 830, in process_refs
    _process_refs_for_node(self.manifest, current_project, node)
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\parser\manifest.py", line 1234, in _process_refs_for_node
    disabled=(isinstance(target_model, Disabled)),
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\parser\manifest.py", line 943, in invalid_ref_fail_unless_test
    disabled=disabled,
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\exceptions.py", line 631, in ref_target_not_found
    raise_compiler_error(msg, model)
  File "C:\users\eric\appdata\local\programs\python\python37\lib\site-packages\dbt\exceptions.py", line 445, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in model cleaned_join_model (models\cleaned_join_model.sql)
  Model 'model.coba.cleaned_join_model' (models\cleaned_join_model.sql) depends on a node named 'cleaning_join_model' which was not found
07:21:01  Encountered an error:
Compilation Error in model cleaned_join_model (models\cleaned_join_model.sql)
  Model 'model.coba.cleaned_join_model' (models\cleaned_join_model.sql) depends on a node named 'cleaning_join_model' which was not found
```

### Environment

```markdown
- OS: Windows 11
- Python: 3.7.5
- dbt: dbt-core==1.2.0
```

**Comment by jaypeedevlin** [comment]
Hey Eric, I hope you don't mind me jumping in.  Python models aren't supported in dbt 1.2, they're in the 1.3 beta: https://github.com/dbt-labs/dbt-core/releases/tag/v1.3.0b1

**Comment by jtcohen6** [comment]
@ericwijaya001 Glad to see you're trying out the new beta capabilities around Python models!

@jaypeedevlin is spot on, you just need to install the beta prerelease of v1.3:
```
pip install dbt-<youradapter>~=1.3.0b1
```
Where `youradapter` is one of `snowflake`, `spark`, or `bigquery`.

Going to close this issue in the meantime.
