### ISSUE TITLE
[CT-1073] [Bug] "No jinja in python model code is allowed" error from string

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/dbt-core#5706]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In converting jaffle_shop from SQL to Python, I ran `mv stg_customers.sql stg_customers.py` and commented out the SQL code by putting it in a string. This looked like: 

```python
sql = """
with source as (
    
    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_payments') }}

),

renamed as (

    select
        id as payment_id,
        order_id,
        payment_method,

        -- `amount` is currently stored in cents, so we convert it to dollars
        amount / 100 as amount

    from source

)

select * from renamed
""".strip()

print(sql)

def model(dbt, session):

    payments_renames = {"id": "payment_id"}

    raw_payments = dbt.ref('raw_payments')
    raw_payments = raw_payments.to_pandas() # see https://github.com/dbt-labs/dbt-core/issues/5646

    payments = raw_payments.rename(columns=payments_renames)
    # -- `amount` is currently stored in cents, so we convert it to dollars
    payments["amount"] /= 100

    return payments
```

To my surprise, this is met with an error:

```bash
@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop/pandas_jaffle_shop (cody/snowy ✗) $ dbt run 
20:28:40  Running with dbt=1.3.0-b1
20:28:41  Unable to do partial parsing because a project config has changed
20:28:42  Encountered an error:
Parsing Error in model stg_customers (models/staging/stg_customers.py)
  No jinja in python model code is allowed
20:28:42  Traceback (most recent call last):
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 494, in catch_jinja
    yield
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 8, in top-level template code
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'ref' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/models.py", line 137, in verify_python_model_code
    rendered_python = get_rendered(
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 499, in catch_jinja
    raise UndefinedMacroException(str(e), node) from e
dbt.exceptions.UndefinedMacroException: Compilation Error in model stg_customers (models/staging/stg_customers.py)
  'ref' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/codyspace/dbt-core/core/dbt/main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "/workspaces/codyspace/dbt-core/core/dbt/main.py", line 191, in handle_and_check
    task, res = run_from_args(parsed)
  File "/workspaces/codyspace/dbt-core/core/dbt/main.py", line 238, in run_from_args
    results = task.run()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 453, in run
    self._runtime_initialize()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 161, in _runtime_initialize
    super()._runtime_initialize()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 94, in _runtime_initialize
    self.load_manifest()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/manifest.py", line 219, in get_full_manifest
    manifest = loader.load()
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/manifest.py", line 349, in load
    self.parse_project(
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/manifest.py", line 473, in parse_project
    parser.parse_file(block)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/base.py", line 414, in parse_file
    self.parse_node(file_block)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/base.py", line 388, in parse_node
    self.render_update(node, config)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/models.py", line 193, in render_update
    verify_python_model_code(node)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/models.py", line 145, in verify_python_model_code
    raise ParsingException("No jinja in python model code is allowed", node=node)
dbt.exceptions.ParsingException: Parsing Error in model stg_customers (models/staging/stg_customers.py)
  No jinja in python model code is allowed
```

### Expected Behavior

I would not really expect my Python code to be inspected for Jinja -- what if I really do want to use Jinja within my Python code for some reason? -- and I would expect this to be able to run. 

Perhaps it could be spun as a feature and not a bug to keep you focused on transformation code? 

### Steps To Reproduce

Try the above.

### Relevant log output

```shell
See above.


@lostmygithubaccount ➜ /workspaces/codyspace/jaffle_shop/pandas_jaffle_shop (cody/snowy ✗) $ dbt run 
20:28:40  Running with dbt=1.3.0-b1
20:28:41  Unable to do partial parsing because a project config has changed
20:28:42  Encountered an error:
Parsing Error in model stg_customers (models/staging/stg_customers.py)
  No jinja in python model code is allowed
20:28:42  Traceback (most recent call last):
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 494, in catch_jinja
    yield
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 8, in top-level template code
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/vscode/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'ref' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/models.py", line 137, in verify_python_model_code
    rendered_python = get_rendered(
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/workspaces/codyspace/dbt-core/core/dbt/clients/jinja.py", line 499, in catch_jinja
    raise UndefinedMacroException(str(e), node) from e
dbt.exceptions.UndefinedMacroException: Compilation Error in model stg_customers (models/staging/stg_customers.py)
  'ref' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/codyspace/dbt-core/core/dbt/main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "/workspaces/codyspace/dbt-core/core/dbt/main.py", line 191, in handle_and_check
    task, res = run_from_args(parsed)
  File "/workspaces/codyspace/dbt-core/core/dbt/main.py", line 238, in run_from_args
    results = task.run()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 453, in run
    self._runtime_initialize()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 161, in _runtime_initialize
    super()._runtime_initialize()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 94, in _runtime_initialize
    self.load_manifest()
  File "/workspaces/codyspace/dbt-core/core/dbt/task/runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/manifest.py", line 219, in get_full_manifest
    manifest = loader.load()
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/manifest.py", line 349, in load
    self.parse_project(
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/manifest.py", line 473, in parse_project
    parser.parse_file(block)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/base.py", line 414, in parse_file
    self.parse_node(file_block)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/base.py", line 388, in parse_node
    self.render_update(node, config)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/models.py", line 193, in render_update
    verify_python_model_code(node)
  File "/workspaces/codyspace/dbt-core/core/dbt/parser/models.py", line 145, in verify_python_model_code
    raise ParsingException("No jinja in python model code is allowed", node=node)
dbt.exceptions.ParsingException: Parsing Error in model stg_customers (models/staging/stg_customers.py)
  No jinja in python model code is allowed
```

### Environment

```markdown
- OS: Linux
- Python: 3.8 (for snowpark)
- dbt: 1.3 via main branches
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

feel free to reach out to me :)

**Comment by anupkalburgi** [comment]
Ran into the same issue. Happy to provide more info if it helps.

**Comment by lostmygithubaccount** [comment]
hi @anupkalburgi, sorry I missed this! it's a known issue and something we'll get around to fixing or providing a clearer error message for. we'll leave this open for others to find if they run into it

**Comment by FishPhd** [comment]
Anyone have a workaround for this? We store some functions with double braces notation. Essentially can't reference it now because of this

**Comment by derycck** [comment]
I faced the same problem while doing a data transformation with pandas lib using dictionary comprehension.
The line that generated this 'No jinja' error was this:
`.astype({**{k:'Int64' for k in ['POP_ESTIMADA_IND', 'QT_MAT_IND']}})`
This line is part of a data transformation using chained methods.

The bug only disappeared when I replaced this line with an approach without using dictionary comprehension, as below:
`.astype({'POP_ESTIMADA_IND':'Int64', 'QT_MAT_IND':'Int64'})`
