### ISSUE TITLE
[CT-1250] [Bug] Raised UndefinedMacroException when try to use macros in section where

### ISSUE THREAD

**Issue by was-av** [dbt-labs/dbt-core#5940]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

UndefinedMacroException was raised when try to use macros in section where

### Expected Behavior

Macros place rendered part of query

### Steps To Reproduce

1. Create macros at_weekend.sql
```
{% macro at_weekend(column_name) %}
    extract(isodow from {{ column_name }}) NOT between 1 and 5
{% endmacro %}
```

2. Create source with test

```
version: "2"
sources:
  - name: s1
     tables: 
      - name: t1
        tests:
         - not_null: 
              name: my_test
              where: "{{ at_weekend('created_at') }}"     
```    

4. Run test`dbt test -s my_test`

### Relevant log output

```shell
12:43:19  Running with dbt=1.2.1
12:43:19  Encountered an error:
Compilation Error
  'at_weekend' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
12:43:19  Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 494, in catch_jinja
    yield
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 526, in render_template
    return template.render(ctx)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 178, in render
    return self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 135, in quoted_native_concat
    head = list(islice(nodes, 2))
  File "<template>", line -1, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'at_weekend' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 191, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 238, in run_from_args
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 451, in run
    self._runtime_initialize()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 159, in _runtime_initialize
    super()._runtime_initialize()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 92, in _runtime_initialize
    self.load_manifest()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 219, in get_full_manifest
    manifest = loader.load()
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 377, in load
    patcher.construct_sources()
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/sources.py", line 72, in construct_sources
    for test in self.get_source_tests(patched):
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/sources.py", line 206, in get_source_tests
    yield self.parse_source_test(
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/sources.py", line 253, in parse_source_test
    node = schema_parser._parse_generic_test(
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 288, in _parse_generic_test
    builder = TestBuilder(
  File "/usr/local/lib/python3.10/site-packages/dbt/parser/generic_test_builders.py", line 260, in __init__
    value = get_rendered(value, render_ctx, native=True)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 571, in get_rendered
    return render_template(template, ctx, node)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 525, in render_template
    with catch_jinja(node):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 499, in catch_jinja
    raise UndefinedMacroException(str(e), node) from e
dbt.exceptions.UndefinedMacroException: Compilation Error
  'at_weekend' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```

### Environment

```markdown
- OS: Description:    Debian GNU/Linux 11 (bullseye)
- Python: Python 3.10.6
- dbt: 1.2.1
```

### Which database adapter are you using with dbt?

postgres

**Comment by jtcohen6** [comment]
Previous conversation about this:

https://github.com/dbt-labs/dbt-core/issues/3580#issuecomment-929125142
https://github.com/dbt-labs/dbt-core/issues/4103#issuecomment-948567484
https://github.com/dbt-labs/dbt-core/issues/5259#issuecomment-1129310833

**Comment by jtcohen6** [comment]
@was-av Thanks for opening! Sorry it's taken me this long to swing back around and leave a more detailed comment.

This has been a common point of confusion for many users now. I left a more detailed comment on a recent related discussion: https://github.com/dbt-labs/dbt-core/discussions/6236#discussioncomment-4177272

And I've opened a PR to update our docs, both to document this limitation and to demonstrate a known workaround: https://github.com/dbt-labs/docs.getdbt.com/pull/2418

In the meantime, I'm going to close this issue as a duplicate.
