### ISSUE TITLE
[CT-1260] [Bug] Could not set use_colors in profiles.yml as Jinja template

### ISSUE THREAD

**Issue by sadahry** [dbt-labs/dbt-core#5948]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Write `config.use_colors` on profiles.yml with Jinja template like `"{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}"`, then error occurred.

Other templates also could not be applied.

### Expected Behavior

Enable to use `as_bool` on config.use_colors .

### Steps To Reproduce

1.Write it on profiles.yml,

```
config:
  use_colors: "{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}"
```

2.Call `dbt debug`

### Relevant log output

```shell
07:18:56  Encountered an error:
"{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}" is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['use_colors']:
    {'oneOf': [{'type': 'boolean'}, {'type': 'null'}]}

On instance['use_colors']:
    "{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}"
07:18:56  jsonschema.exceptions.ValidationError: "{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}" is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['use_colors']:
    {'oneOf': [{'type': 'boolean'}, {'type': 'null'}]}

On instance['use_colors']:
    "{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/xxxx/lib/python3.10/site-packages/dbt/main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "/xxxx/lib/python3.10/site-packages/dbt/main.py", line 191, in handle_and_check
    task, res = run_from_args(parsed)
  File "/xxxx/lib/python3.10/site-packages/dbt/main.py", line 238, in run_from_args
    results = task.run()
  File "/xxxx/lib/python3.10/site-packages/dbt/task/debug.py", line 113, in run
    self.test_configuration()
  File "/xxxx/lib/python3.10/site-packages/dbt/task/debug.py", line 285, in test_configuration
    profile_status = self._load_profile()
  File "/xxxx/lib/python3.10/site-packages/dbt/task/debug.py", line 256, in _load_profile
    profile: Profile = Profile.render_from_args(self.args, renderer, profile_name)
  File "/xxxx/lib/python3.10/site-packages/dbt/config/profile.py", line 428, in render_from_args
    return cls.from_raw_profiles(
  File "/xxxx/lib/python3.10/site-packages/dbt/config/profile.py", line 394, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "/xxxx/lib/python3.10/site-packages/dbt/config/profile.py", line 352, in from_raw_profile_info
    return cls.from_credentials(
  File "/xxxx/lib/python3.10/site-packages/dbt/config/profile.py", line 258, in from_credentials
    UserConfig.validate(user_config)
  File "/xxxx/lib/python3.10/site-packages/hologram/__init__.py", line 989, in validate
    raise ValidationError.create_from(error) from error
hologram.ValidationError: "{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}" is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['use_colors']:
    {'oneOf': [{'type': 'boolean'}, {'type': 'null'}]}

On instance['use_colors']:
    "{{ env_var('SNOWFLAKE_USE_COLORS', 'True') | as_bool }}"

make: *** [debug] Error 2
```

### Environment

```markdown
% dbt debug
07:22:18  Running with dbt=1.2.1
dbt version: 1.2.1
python version: 3.10.4
os info: macOS-12.4-arm64-arm-64bit
```

**Comment by jtcohen6** [comment]
@sadahry Thanks for opening!

We don't support Jinja rendering within the `config` dictionary ("UserConfig") that can be defined in `profiles.yml` today.

As with [all global configs](https://docs.getdbt.com/reference/global-configs), it is possible to set it via env var to override that setting, using the naming convention prefixed with `DBT_`:
```
$ DBT_USE_COLORS=1 dbt run
```

What's the motivation for making this conditional on another environment variable (`SNOWFLAKE_USE_COLORS`)?
