### ISSUE TITLE
[CT-1469] [Bug] Define Python Version when Installing Dependencies

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-core#6203]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We don't currently define the version of python to use when installing dependencies so it just uses what's in the PATH of the runner.  This recently updated to Python 3.11 which we don't officially support.  This is causing some dependency installation failures.

### Expected Behavior

Dependencies install without failure.

### Steps To Reproduce

Run the `main.yml` action.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0/x64/bin/dbt", line 33, in <module>
    sys.exit(load_entry_point('dbt-core==1.2.2', 'console_scripts', 'dbt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/bin/dbt", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/dbt/main.py", line 2, in <module>
    from dbt.logger import log_cache_events, log_manager
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/dbt/logger.py", line 16, in <module>
    from dbt.dataclass_schema import dbtClassMixin
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/dbt/dataclass_schema.py", line 15, in <module>
    from mashumaro import DataClassDictMixin
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/__init__.py", line 4, in <module>
    from mashumaro.serializer.json import DataClassJSONMixin
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/serializer/json.py", line 28, in <module>
    class DataClassJSONMixin(DataClassDictMixin):
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/serializer/base/dict.py", line 16, in __init_subclass__
    builder.add_from_dict()
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/serializer/base/metaprogramming.py", line 270, in add_from_dict
    pre_deserialize = self.get_declared_hook(__PRE_DESERIALIZE__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/serializer/base/metaprogramming.py", line 255, in get_declared_hook
    if not is_dataclass_dict_mixin(cls):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/meta/helpers.py", line 247, in is_dataclass_dict_mixin
    return type_name(t) == DataClassDictMixinPath
           ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/meta/helpers.py", line 93, in type_name
    elif is_generic(t) and not is_type_origin:
         ^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/mashumaro/meta/helpers.py", line 161, in is_generic
    raise NotImplementedError
NotImplementedError
Error: Process completed with exit code 1.
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by mzw4** [comment]
This is still an issue for me when running the `dbt` cli command with Python 3.11 and dbt-core 1.3.1

```
$ dbt                                                                                                                                                                                       Py mesh-data 14:23:32
Traceback (most recent call last):
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/bin/dbt", line 5, in <module>
    from dbt.main import main
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/dbt/main.py", line 3, in <module>
    from dbt.logger import log_cache_events, log_manager
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/dbt/logger.py", line 17, in <module>
    from dbt.dataclass_schema import dbtClassMixin
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/dbt/dataclass_schema.py", line 37, in <module>
    class dbtClassMixin(DataClassDictMixin, JsonSchemaMixin):
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/mashumaro/mixins/dict.py", line 16, in __init_subclass__
    builder.add_from_dict()
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/mashumaro/core/meta/builder.py", line 419, in add_from_dict
    dialects_feature = self.is_code_generation_option_enabled(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/mashumaro/core/meta/builder.py", line 594, in is_code_generation_option_enabled
    type_name(ancestor)
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/mashumaro/core/meta/helpers.py", line 150, in type_name
    elif is_generic(t) and not is_type_origin:
         ^^^^^^^^^^^^^
  File "/Users/mzw/opt/anaconda3/envs/mesh-data/lib/python3.11/site-packages/mashumaro/core/meta/helpers.py", line 217, in is_generic
    raise NotImplementedError
NotImplementedError
```
