### ISSUE TITLE
[CT-1480] [Bug] dbt_utils install fails when long paths are not enabled for the file system

### ISSUE THREAD

**Issue by bakerbryce** [dbt-labs/dbt-core#6229]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt_utils package fails to install with a 'file does not exist' error. This is caused by long file paths encountered when extracting the dbt_utils package. This issue is unique to Windows Server 2019 where some versions do not have Win32 long paths enabled by default.

Details and workaround documented here:
https://discourse.getdbt.com/t/error-installing-dbt-utils-package-on-azure-devops-self-hosted-agent/5007

### Expected Behavior

dbt_utils will install cleanly on Windows 

### Steps To Reproduce

Attempt to install dbt packages using `dbt deps` while LongPathsEnabled is not set to true in Windows.

### Relevant log output

```shell
09:08:52  Running with dbt=1.2.1
09:08:52  Installing dbt-labs/dbt_utils
09:08:53  Encountered an error:
[Errno 2] No such file or directory: 'dbt_packages\\dbt-utils-0.9.2\\integration_tests\\data\\schema_tests\\data_test_mutually_exclusive_ranges_with_gaps_zero_length.csv'
09:08:53  Traceback (most recent call last):
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\main.py", line 191, in handle_and_check
    task, res = run_from_args(parsed)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\main.py", line 238, in run_from_args
    results = task.run()
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\task\deps.py", line 67, in run
    package.install(self.config, renderer)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\deps\registry.py", line 74, in install
    connection_exception_retry(download_untar_fn, 5)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\utils.py", line 616, in _connection_exception_retry
    return fn()
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\deps\registry.py", line 86, in download_and_untar
    system.untar_package(tar_path, deps_path, package_name)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\site-packages\dbt\clients\system.py", line 478, in untar_package
    tarball.extractall(dest_dir)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\tarfile.py", line 2040, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\tarfile.py", line 2081, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\tarfile.py", line 2154, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "D:\AzureDevOps\_work\_tool\Python\3.10.0\x64\lib\tarfile.py", line 2195, in makefile
    with bltn_open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'dbt_packages\\dbt-utils-0.9.2\\integration_tests\\data\\schema_tests\\data_test_mutually_exclusive_ranges_with_gaps_zero_length.csv'
```

### Environment

```markdown
- OS: Windows Server 2019
- Python: 3.10.0
- dbt: 1.2.2
- dbt_utils: 0.9.2
```

### Additional Context

**All details and workaround documented here**:
https://discourse.getdbt.com/t/error-installing-dbt-utils-package-on-azure-devops-self-hosted-agent/5007

**Possible fix**: modify dbt package extract code to use relative child directory during extract rather than absolute paths so that long paths aren't encountered.

**Comment by jtcohen6** [comment]
@bakerbryce Ugh, this is annoying. Thanks for opening the issue, and the linked discourse post, to document this as a known bug. We're unlikely to prioritize a fix for something this specific, especially given it has a halfway-decent workaround.

End users of `dbt-utils` have no need to install the `integration_tests`, which is where the offending file lives. Unfortunately, the current infrastructure of the dbt Hub (downloading GitHub-hosted tarballs) doesn't enable us to download a subset of a repo / exclude specific files. Some prior conversation about that in this issue: https://github.com/dbt-labs/dbt-core/issues/4868

**Comment by simonepm** [comment]
I see this is stale, by the way long paths are still an issue as of today, not only in dbt_utils integration_tests, but also at core if you need long names for your models.

The workaround proposed invite to set:

`Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1;`

But this is not always a possibility, as the access to the registry can be restricted.

Replacing the 'open' occurrences would be a more robust solution:

```
if os == "windows":
    model_path = u"\\\\?\\"+os.path.abspath(model_path)
with open(model_path) as ...
```
