### ISSUE TITLE
[Regression] TypeError: '_MISSING_TYPE' object is not callable

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/dbt-core#6451]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Basic operations like `dbt compile` and `dbt run` create the same error below. 

```terminal
 ~/De/dbt/dbt_env │ main *12  dbt compile                                           2 х │ 3s │ dbt Py 
23:53:53  Encountered an error:
'_MISSING_TYPE' object is not callable
23:53:53  Traceback (most recent call last):
  File "/Users/sung/Desktop/dbt/core/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/Users/sung/Desktop/dbt/core/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/sung/Desktop/dbt/core/dbt/main.py", line 225, in run_from_args
    task = parsed.cls.from_args(args=parsed)
  File "/Users/sung/Desktop/dbt/core/dbt/task/base.py", line 181, in from_args
    return super().from_args(args)
  File "/Users/sung/Desktop/dbt/core/dbt/task/base.py", line 103, in from_args
    config = cls.ConfigType.from_args(args)
  File "/Users/sung/Desktop/dbt/core/dbt/config/runtime.py", line 264, in from_args
    return cls.from_parts(
  File "/Users/sung/Desktop/dbt/core/dbt/config/runtime.py", line 81, in from_parts
    get_relation_class_by_name(profile.credentials.type)
  File "/Users/sung/Desktop/dbt/core/dbt/adapters/base/relation.py", line 56, in get_default_quote_policy
    return cls._get_field_named("quote_policy").default_factory()
TypeError: '_MISSING_TYPE' object is not callable
```

### Expected/Previous Behavior

I don't see this error at all.

### Steps To Reproduce

1. Run a dbt project(I used snowflake) with the `main` branch version of `dbt-core`
2. Run `dbt run` and see the error output

### Relevant log output

```shell
~/De/dbt/dbt_env │ main *12  dbt compile                                           2 х │ 3s │ dbt Py 
23:53:53  Encountered an error:
'_MISSING_TYPE' object is not callable
23:53:53  Traceback (most recent call last):
  File "/Users/sung/Desktop/dbt/core/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/Users/sung/Desktop/dbt/core/dbt/main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/sung/Desktop/dbt/core/dbt/main.py", line 225, in run_from_args
    task = parsed.cls.from_args(args=parsed)
  File "/Users/sung/Desktop/dbt/core/dbt/task/base.py", line 181, in from_args
    return super().from_args(args)
  File "/Users/sung/Desktop/dbt/core/dbt/task/base.py", line 103, in from_args
    config = cls.ConfigType.from_args(args)
  File "/Users/sung/Desktop/dbt/core/dbt/config/runtime.py", line 264, in from_args
    return cls.from_parts(
  File "/Users/sung/Desktop/dbt/core/dbt/config/runtime.py", line 81, in from_parts
    get_relation_class_by_name(profile.credentials.type)
  File "/Users/sung/Desktop/dbt/core/dbt/adapters/base/relation.py", line 56, in get_default_quote_policy
    return cls._get_field_named("quote_policy").default_factory()
TypeError: '_MISSING_TYPE' object is not callable
```

### Environment

```markdown
- OS: os info: macOS-13.0-x86_64-i386-64bit
- Python: 3.8.9
- dbt (working version): 1.4.0-a1
- dbt (regression version): 1.4.0-b1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @sungchun12 !

Glad we were able to resolve this quickly chatting in Slack.

For anyone else stumbling upon this: our solution was to pull the latest changes from `main` branches of local copies of both `dbt-snowflake` and `dbt-core`.
