### ISSUE TITLE
[CT-1907] [Bug] dbt run cli hanging on BigQuery connection (windows 10)

### ISSUE THREAD

**Issue by dom-devel** [dbt-labs/dbt-core#6734]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a relatively small DBT project ~ 23 models. 

When trying to run `dbt run` or primarily a small segment of the project `dbt run --models analytics_dashboard --full-refresh`

The connection to BigQuery hangs and never progresses probably ~80% of the time. (Although this varies from day to day).

```

============================== 2023-01-25 19:45:37.830580 | ee699e45-84b3-471e-b2ef-ec877239124b ==============================
[0m19:45:37.830580 [info ] [MainThread]: Running with dbt=1.2.0
[0m19:45:37.839924 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': 'C:\\Users\\{username}\\.dbt', 'send_anonymous_usage_stats': True, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'select': ['analytics_dashboard'], 'full_refresh': True, 'which': 'run', 'rpc_method': 'run', 'indirect_selection': 'eager'}
[0m19:45:37.841875 [debug] [MainThread]: Tracking: tracking
[0m19:45:37.844202 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9D3B8A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9D3B8B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9D3B8BB0>]}
[0m19:45:38.403002 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 2 files changed.
[0m19:45:38.406899 [debug] [MainThread]: Partial parsing: updated file: customer_dbt://models\analytics_dashboard\_analytics_db_daily_visibility_rolling_14.sql
[0m19:45:38.407874 [debug] [MainThread]: Partial parsing: updated file: customer_dbt://models\analytics_dashboard\_analytics_db_daily_visibility_rolling_56.sql
[0m19:45:38.488601 [debug] [MainThread]: 1603: static parser failed on analytics_dashboard\_analytics_db_daily_visibility_rolling_14.sql
[0m19:45:38.567877 [debug] [MainThread]: 1602: parser fallback to jinja rendering on analytics_dashboard\_analytics_db_daily_visibility_rolling_14.sql
[0m19:45:38.576609 [debug] [MainThread]: 1603: static parser failed on analytics_dashboard\_analytics_db_daily_visibility_rolling_56.sql
[0m19:45:38.600741 [debug] [MainThread]: 1602: parser fallback to jinja rendering on analytics_dashboard\_analytics_db_daily_visibility_rolling_56.sql
[0m19:45:38.631541 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.content_dashboard

[0m19:45:38.655901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ee699e45-84b3-471e-b2ef-ec877239124b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9DE43AC0>]}
[0m19:45:38.695404 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ee699e45-84b3-471e-b2ef-ec877239124b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9D3F6F10>]}
[0m19:45:38.697103 [info ] [MainThread]: Found 26 models, 0 tests, 0 snapshots, 0 analyses, 293 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[0m19:45:38.698641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ee699e45-84b3-471e-b2ef-ec877239124b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9D3F6FD0>]}
[0m19:45:38.702655 [info ] [MainThread]: 
[0m19:45:38.705588 [debug] [MainThread]: Acquiring new bigquery connection "master"
[0m19:45:38.707541 [debug] [ThreadPool]: Acquiring new bigquery connection "list_customer-project-live"
[0m19:45:38.709492 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m19:45:39.118546 [debug] [ThreadPool]: Acquiring new bigquery connection "list_customer-project-live_us_warehouse"
[0m19:45:39.120268 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m19:45:39.552305 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ee699e45-84b3-471e-b2ef-ec877239124b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9D3D4130>]}
[0m19:45:39.555792 [info ] [MainThread]: Concurrency: 4 threads (target='prod')
[0m19:45:39.562813 [info ] [MainThread]: 
[0m19:45:39.591095 [debug] [Thread-1  ]: Began running node model.customer_dbt._analytics_db_raw_daily
[0m19:45:39.593999 [info ] [Thread-1  ]: 1 of 4 START incremental model us_warehouse._analytics_db_raw_daily ...... [RUN]
[0m19:45:39.602042 [debug] [Thread-1  ]: Acquiring new bigquery connection "model.customer_dbt._analytics_db_raw_daily"
[0m19:45:39.603969 [debug] [Thread-1  ]: Began compiling node model.customer_dbt._analytics_db_raw_daily
[0m19:45:39.604945 [debug] [Thread-1  ]: Compiling model.customer_dbt._analytics_db_raw_daily
[0m19:45:39.717113 [debug] [Thread-1  ]: Writing injected SQL for node "model.customer_dbt._analytics_db_raw_daily"
[0m19:45:39.721902 [debug] [Thread-1  ]: finished collecting timing info
[0m19:45:39.724258 [debug] [Thread-1  ]: Began executing node model.customer_dbt._analytics_db_raw_daily
[0m19:45:39.934600 [debug] [Thread-1  ]: Opening a new connection, currently in state init
[0m19:45:40.388610 [debug] [Thread-1  ]: Writing runtime SQL for node "model.customer_dbt._analytics_db_raw_daily"
[0m19:45:40.391893 [debug] [Thread-1  ]: On model.customer_dbt._analytics_db_raw_daily: /* {"app": "dbt", "dbt_version": "1.2.0", "profile_name": "example_profile_name", "target_name": "prod", "node_id": "model.customer_dbt._analytics_db_raw_daily"} */
```

When running the compiled query in BigQuery it takes approximately 5-10 seconds to run.

There are never any failure logs or anything other than just the silent failure of a run most of the time.

**Best guess**

I'd guess the connection is somehow silently dropping and maybe dbt doesn't try to reconnect it? If I toggle my WiFi network on and off mid-run, it will realise the disconnect, attempt to reconnect, succeed, run a query and then drop again.

```
[0m19:56:30.703452 [debug] [Thread-1  ]: BigQuery adapter: Retry attempt 1 of 1 after error: ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)))
[0m19:56:30.706022 [warn ] [Thread-1  ]: BigQuery adapter: Reopening connection after ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)))
[0m19:56:40.652438 [debug] [Thread-1  ]: finished collecting timing info
[0m19:56:40.660239 [debug] [Thread-1  ]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'ee699e45-84b3-471e-b2ef-ec877239124b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D9DCFC430>]}
[0m19:56:40.662192 [info ] [Thread-1  ]: 1 of 4 OK created incremental model customer_dbt._analytics_db_raw_daily . [[32mCREATE TABLE (498.8k rows, 44.7 MB processed)[0m in 661.06s]
[0m19:56:40.803961 [debug] [Thread-1  ]: Finished running node model.customer_dbt._analytics_db_raw_daily
[0m19:56:40.806808 [debug] [Thread-3  ]: Began running node model.customer_dbt._analytics_db_raw_daily_part2
```

### Expected Behavior

It shouldn't hang it should instead attempt to reconnect. (Or provide additional logging output).

### Steps To Reproduce

1. Environment:
- Windows 10
- dbt 1.2.0
- python 3.8.5
- ConEmu for shell

2. Generate a basic DBT project with some queries which run on BigQuery.

But it's not a consistent problem, so I suspect it's going to be hard to re-create :(

### Environment

```markdown
- OS: Windows 10
- Python: 3.8.5
- dbt:1.2.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @dom-devel !

80% is really high 😰 

Unfortunately, I think you're right that this could be a hard one for us to reproduce.

An idea for you:
- we just released a new version of dbt-bigquery earlier today: `dbt-bigquery==1.4.0`

This version has a [new way to handle connection retries](https://github.com/dbt-labs/dbt-bigquery/blob/v1.4.0/CHANGELOG.md?plain=1#L20) for BigQuery ([#230](https://github.com/dbt-labs/dbt-bigquery/pull/230))

Are you in a position you could try upgrade to `dbt-bigquery==1.4.0` and see if it changes anything for you?

**Comment by SergeyMatskevich** [comment]
I have the similar problem with dbt for bigquery:

From time to time the run even dbt debug takes 7 minutes to check where 99% of time it checks the connection.

![Screenshot 2023-11-28 at 20 11 04](https://github.com/dbt-labs/dbt-core/assets/1967072/d2e882f5-b641-460a-af49-65454b307c3d)

**Comment by dbeatty10** [comment]
Could you share your environment details @SergeyMatskevich ?

Example:

OS: Ubuntu 20.04
Python: 3.9.12 (via `python3 --version`)
dbt-core: 1.5.1 (via `dbt --version`)
dbt-bigquery: 1.5.3 (via `dbt --version`)

Do you notice anything that is different when it takes a long time? For example, do you see anything in your `logs/dbt.log` file that is different between when it is "slow" and when it is "fast"?

Is it possible you are experiencing an unstable internet connection when it is "slow"?

**Comment by SergeyMatskevich** [comment]
Hello, 

Thank you for going back to me!

My setup is:

OS: Mac Os 14.1.1 (23B81)
Python: 3.8.3 
dbt-core: 1.7.3 
dbt-bigquery: 1.7.2 

So I've run the `dbt build` with -d to see where the issue is. Here are two examples for yesterday's and today's run.

It is fast when the time between these two lines less then 10 seconds:

```
[0m17:20:08.682442 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m17:20:10.212892 [debug] [ThreadPool]: Re-using an available connection from the pool (some connections data here)
```

It is slow when the time between these two lines is around 7 minutes (and it is always 7 minutes):

```
[0m09:39:51.663813 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m09:47:25.522677 [debug] [ThreadPool]: Re-using an available connection from the pool (some connections data here)

```

**Comment by SergeyMatskevich** [comment]
@dbeatty10 hello!

Here it what I found as stack trace after I aborted execution with `control` + `c`

[0m20:41:09.285666 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 244, in wrapper
    return func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 284, in wrapper
    return func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/main.py", line 625, in run
    results = task.run()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/runnable.py", line 474, in run
    result = self.execute_with_hooks(selected_uids)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/runnable.py", line 434, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/run.py", line 446, in before_run
    self.create_schemas(adapter, required_schemas)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/runnable.py", line 572, in create_schemas
    for ls_future in as_completed(list_futures):
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 244, in as_completed
    waiter.event.wait(wait_timeout)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()

**Comment by dbeatty10** [comment]
Thanks for this stacktrace @SergeyMatskevich !

The part that sticks out to me is:
```
File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/run.py", line 446, in before_run
self.create_schemas(adapter, required_schemas)
```

I'm assuming you got this when doing either a `dbt run` or a `dbt build`?

If so, is there any chance you could do it with a `dbt debug` as well to see if the stack trace looks the same or different?

**Comment by SergeyMatskevich** [comment]
@dbeatty10  Sure

Here is a stacktrace after `dbt debug`:

[0m07:52:22.663609 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/cli/main.py", line 444, in debug
    results = task.run()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/debug.py", line 153, in run
    connection_status = self.test_connection()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/debug.py", line 472, in test_connection
    connection_result = self.attempt_connection(self.profile)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/task/debug.py", line 450, in attempt_connection
    adapter.debug_query()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/impl.py", line 922, in debug_query
    self.execute("select 1 as id")
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/base/impl.py", line 310, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 514, in execute
    query_job, iterator = self.raw_execute(sql, limit=limit)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 467, in raw_execute
    client = conn.handle
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/contracts/connection.py", line 90, in handle
    self._handle.resolve(self)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/contracts/connection.py", line 114, in resolve
    return self.opener(connection)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 400, in open
    handle = cls.get_bigquery_client(connection.credentials)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 381, in get_bigquery_client
    creds = cls.get_credentials(profile_credentials)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 376, in get_credentials
    return cls.get_google_credentials(profile_credentials)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 338, in get_google_credentials
    credentials, _ = get_bigquery_defaults(scopes=profile_credentials.scopes)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/dbt/adapters/bigquery/connections.py", line 85, in get_bigquery_defaults
    credentials, _ = google.auth.default(scopes=scopes)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/auth/_default.py", line 651, in <lambda>
    lambda: _get_gcloud_sdk_credentials(quota_project_id=quota_project_id),
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/auth/_default.py", line 242, in _get_gcloud_sdk_credentials
    project_id = _cloud_sdk.get_project_id()
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/auth/_cloud_sdk.py", line 106, in get_project_id
    project = _run_subprocess_ignore_stderr(
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/site-packages/google/auth/_cloud_sdk.py", line 88, in _run_subprocess_ignore_stderr
    output = subprocess.check_output(command, stderr=devnull)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/sergey_matskevich/miniconda3/lib/python3.8/subprocess.py", line 1011, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
