### ISSUE TITLE
[CT-1935] [Regression] Error when running any DBT command in version 1.4.0

### ISSUE THREAD

**Issue by chleech** [dbt-labs/dbt-core#6770]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

I just upgraded to dbt-snowflake v1.4.0 using home brew. After the installation was completed

```
>> dbt --version
```

Gave me
```
21:45:32  Encountered an error:
deprecated() got an unexpected keyword argument 'name'
```

I've tried uninstalling everything as well and re-installing the snowflake adapter by following the steps [here](https://docs.getdbt.com/docs/get-started/homebrew-install#installing-with-homebrew), but it still gave me the same error output.

### Expected/Previous Behavior

`dbt` commands work

### Steps To Reproduce

1. Install dbt-snowflake 1.4.0
```
>> brew install dbt-snowflake@1.4.0
```

2. After successful installation
```
>> dbt run
```

3. Error output
(same as above)
```
...
TypeError: deprecated() got an unexpected keyword argument 'name'
```

### Relevant log output

```shell
21:45:32  Encountered an error:
deprecated() got an unexpected keyword argument 'name'
21:45:32  Traceback (most recent call last):
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/main.py", line 176, in handle_and_check
    parsed = parse_args(args)
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/main.py", line 1203, in parse_args
    parsed = p.parse_args(args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1825, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2067, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2007, in consume_optional
    take_action(action, args, option_string)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/main.py", line 74, in __call__
    formatter.add_text(dbt.version.get_version_information())
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/version.py", line 27, in get_version_information
    plugin_version_msg = _get_plugins_msg(installed)
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/version.py", line 107, in _get_plugins_msg
    for name, version_s in _get_dbt_plugins_info():
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/version.py", line 214, in _get_dbt_plugins_info
    mod = importlib.import_module(f"dbt.adapters.{plugin_name}.__version__")
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/adapters/snowflake/__init__.py", line 2, in <module>
    from dbt.adapters.snowflake.connections import SnowflakeConnectionManager  # noqa
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 17, in <module>
    import snowflake.connector
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/snowflake/connector/__init__.py", line 16, in <module>
    from .connection import SnowflakeConnection
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/snowflake/connector/connection.py", line 25, in <module>
    from . import errors, proxy
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/snowflake/connector/errors.py", line 18, in <module>
    from .telemetry_oob import TelemetryService
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/snowflake/connector/telemetry_oob.py", line 20, in <module>
    from .vendored import requests
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/snowflake/connector/vendored/requests/__init__.py", line 119, in <module>
    from ..urllib3.contrib import pyopenssl
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/opt/homebrew/Cellar/dbt-snowflake/1.4.0/libexec/lib/python3.9/site-packages/OpenSSL/crypto.py", line 3224, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
```

### Environment

```markdown
- OS: macOS Monterey
- Python: `Python 3.9.14` (using pyenv) 
- dbt (working version): 1.3.1
- dbt (regression version): 1.4.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @chleech !

Ultimately, we'll need to fix this over in [homebrew-dbt](https://github.com/dbt-labs/homebrew-dbt), and you can track along with this issue:
- https://github.com/dbt-labs/homebrew-dbt/issues/268

**Comment by jtcohen6** [comment]
@chleech Thanks for opening. This appears to be an issue with the Homebrew installation of `dbt-snowflake` in particular. We're tracking that in this issue: https://github.com/dbt-labs/homebrew-dbt/issues/268

In the meantime, you can try installing `dbt-snowflake` via `pip` instead:
```bash
$ python3 -m venv env
$ source env/bin/activate
$ pip install dbt-snowflake
...
Successfully installed Jinja2-3.1.2 asn1crypto-1.5.1 betterproto-1.2.5 charset-normalizer-2.1.1 cryptography-38.0.4 dbt-core-1.4.1 dbt-snowflake-1.4.0 filelock-3.9.0 grpclib-0.4.3 h2-4.1.0 hpack-4.0.0 hyperframe-6.0.1 jaraco.classes-3.2.3 keyring-23.13.1 mashumaro-3.3.1 more-itertools-9.0.0 multidict-6.0.4 oscrypto-1.3.0 pathspec-0.10.3 pyOpenSSL-22.1.0 pycryptodomex-3.17 pyjwt-2.6.0 snowflake-connector-python-2.8.1 stringcase-1.2.0 typing-extensions-4.4.0
$ dbt --version
Core:
  - installed: 1.4.1
  - latest:    1.4.1 - Up to date!

Plugins:
  - snowflake: 1.4.0 - Up to date!
```
