### ISSUE TITLE
[CT-2072] [Bug] Windows 10 / UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1120

### ISSUE THREAD

**Issue by kolyadin** [dbt-labs/dbt-core#6919]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt run -s model_name

dbt fatal error with:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1120: character maps to <undefined>07:52:09  Encountered an error:
'charmap' codec can't decode byte 0x98 in position 1120: character maps to <undefined>

### Expected Behavior

dbt run -s model_name
===

dbt running models

### Steps To Reproduce

1. Windows 10 Enterprise Version 22H2
2. Python 3.10.10
3. pip install dbt-core
4. dbt run -s model_name

### Relevant log output

```shell
07:52:08  Running with dbt=1.2.0
Traceback (most recent call last):
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\main.py", line 129, in main
    results, succeeded = handle_and_check(args)
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\main.py", line 192, in handle_and_check
    task, res = run_from_args(parsed)
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\main.py", line 239, in run_from_args
    results = task.run()
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\task\runnable.py", line 451, in run
    self._runtime_initialize()
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\task\runnable.py", line 159, in _runtime_initialize
    super()._runtime_initialize()
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\task\runnable.py", line 92, in _runtime_initialize
    self.load_manifest()
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\task\runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\parser\manifest.py", line 217, in get_full_manifest
    loader = cls(config, projects, macro_hook)
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\parser\manifest.py", line 185, in __init__
    self.manifest.state_check = self.build_manifest_state_check()
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\parser\manifest.py", line 740, in build_manifest_state_check
    project_hashes[name] = FileHash.from_contents(fp.read())
  File "C:\Users\ERoman01\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1120: character maps to <undefined>07:52:09  Encountered an error:
'charmap' codec can't decode byte 0x98 in position 1120: character maps to <undefined>
```

### Environment

```markdown
- OS: Windows 10 Enterprise Version 22H2
- Python: Python 3.10.10
- dbt: 1.2.0
```

### Which database adapter are you using with dbt?

postgres

**Comment by jtcohen6** [comment]
It looks like the error is being tripped in this step:
https://github.com/dbt-labs/dbt-core/blob/5b3fbe7c570b1da09dda3e5aeb8fffdf1a2c93cf/core/dbt/parser/manifest.py#L735-L740

@kolyadin It sounds like you may have some non-standard characters in your `dbt_project.yml`? Possibly the result of copy-pasting some code from elsewhere?

**Comment by kolyadin** [comment]
@jtcohen6 yes. It was some cyrillyc symbols in dbt_project.yml but it was in comments

**Comment by jtcohen6** [comment]
Ah, okay. If you remove the Cyrillic, does the error go away?

I'm surprising that Python can't handle those. We might just need to specify an encoding on lines 739-740 linked above. It seems like, if folks want to drop lengthy project-level commentaries in Old Church Slavonic, they should be able to.

**Comment by kolyadin** [comment]
@jtcohen6 yes) After removing line with cyrillic comments all works just fine.
So we can use cyrillis comments in *.sql model files, but cant in yml.

All this *hit only in windows

**Comment by gshank** [comment]
In the test utilities we had to open a file for writing with encoding="utf-8" or things would break on Windows. Perhaps the probably isn't reading the file, but that it's being written out with a non-utf-8 codepage?

**Comment by henry0905** [comment]
Hello, for your information, I have the same issue when running the dbt seed containing Chinese characters, for example: "**支付宝**" (Alipay).
`'charmap' codec can't encode characters in position 10-14: character maps to <undefined>`.
Could you please provide an estimated timeline for the release of the bug fix?

**Comment by dbeatty10** [comment]
@kolyadin as described [here](https://github.com/dbt-labs/dbt-core/issues/7835#issuecomment-1592928647), does setting the following environment variable allow Cyrillic to be used successfully?

```shell
export PYTHONIOENCODING=utf8
```
