### ISSUE TITLE
[Bug] error using inline compile with newline characters in jinja strings 

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-core#7207]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When passing raw SQL to the new `dbt compile --inline` command, the compiler does not properly handle newline characters within jinja blocks: 

Without newline characters:
```stdout
❯ dbt compile --inline "select {{ dbt_utils.group_by(5) }}"
14:35:24  Running with dbt=1.5.0-b4
14:35:24  Found 3 models, 5 tests, 1 snapshot, 1 analysis, 420 macros, 0 operations, 1 seed file, 1 source, 1 exposure, 0 metrics, 0 groups
14:35:24  
14:35:24  Concurrency: 2 threads (target='postgres')
14:35:24  
14:35:24  Compiled node 'inline_query' is:
select group by 1,2,3,4,5
14:35:24  Done.
```

With newline characters:
```stdout
❯ dbt compile --inline "select {{\n dbt_utils.group_by(5) \n}}"
14:35:34  Running with dbt=1.5.0-b4
Traceback (most recent call last):
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/clients/jinja.py", line 514, in catch_jinja
    yield
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/clients/jinja.py", line 541, in get_template
    return env.from_string(template_source, globals=ctx)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 9
  line 1
    select {{\n dbt_utils.group_by(5) \n}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/bin/dbt", line 8, in <module>
    sys.exit(cli())
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 92, in wrapper
    return func(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/cli/requires.py", line 175, in wrapper
    return func(*args, **kwargs)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/cli/main.py", line 271, in compile
    results = task.run()
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/task/runnable.py", line 420, in run
    self._runtime_initialize()
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/task/compile.py", line 118, in _runtime_initialize
    sql_node = block_parser.parse_remote(self.args.inline, "inline_query")
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/parser/sql.py", line 48, in parse_remote
    return self.parse_node(contents)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/parser/base.py", line 395, in parse_node
    self.render_update(node, config)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/parser/base.py", line 371, in render_update
    context = self.render_with_context(node, config)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/parser/base.py", line 240, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/clients/jinja.py", line 584, in get_rendered
    template = get_template(
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/clients/jinja.py", line 541, in get_template
    return env.from_string(template_source, globals=ctx)
  File "/Users/daveconnors/.pyenv/versions/3.9.16/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/daveconnors/dev/sandbox/tmp-sqlfluff-demo/env/lib/python3.9/site-packages/dbt/clients/jinja.py", line 517, in catch_jinja
    raise CompilationError(str(e), node) from e
dbt.exceptions.CompilationError: Compilation Error in sql operation inline_query (from remote system.sql)
  unexpected char '\\' at 9
    line 1
      select {{\n dbt_utils.group_by(5) \n}}
```

Same SQL written in a model file with the newlines:
```sql
-- in models/new_line_macro.sql

{{
    dbt_utils.group_by(5)
}}
```
```
❯ dbt compile -s new_line_macro    
14:41:56  Running with dbt=1.5.0-b4
14:41:56  Found 4 models, 5 tests, 1 snapshot, 1 analysis, 420 macros, 0 operations, 1 seed file, 1 source, 1 exposure, 0 metrics, 0 groups
14:41:56  
14:41:56  Concurrency: 2 threads (target='postgres')
14:41:56  
14:41:56  Compiled node 'new_line_macro' is:
group by 1,2,3,4,5
14:41:56  Done.
```

### Expected Behavior

New lines should not affect the jinja rendering!

### Steps To Reproduce

1. pass in Jinja-SQL without newlines to `dbt compile --inline` , see rendered sql
2. pass in same Jinja-SQL with newlines inside Jinja block `{{ }}` , see error
3. paste same Jinja-SQL with newlines into a model file, compile `dbt compile -s model_name` see same result as step 1

### Environment

```markdown
- OS: Mac
- Python: Python 3.9.16


❯ dbt --version
Core:
  - installed: 1.5.0-b4
  - latest:    1.4.5    - Ahead of latest version!

Plugins:
  - postgres: 1.5.0b4 - Ahead of latest version!
```
```


### Which database adapter are you using with dbt?

postgres

### Additional Context

_No response_

**Comment by dbeatty10** [comment]
Thanks for trying this out and reporting this bug @dave-connors-3 🙌

**Comment by jtcohen6** [comment]
Hmm, I'm not sure if this is actually a `bug` we want/need to resolve! This fails independently of using `dbt compile --inline`. The same behavior exists in older versions, too:

```sql
-- models/any_model.sql

select {{\n dbt_utils.group_by(5) \n}}
```
```
$ dbt compile
15:47:06  Running with dbt=1.4.3
15:47:06  Unable to do partial parsing because of a version mismatch
15:47:07  Encountered an error:
Compilation Error in model my_model (models/my_model.sql)
  unexpected char '\\' at 9
    line 1
      select {{\n dbt_utils.group_by(5) \n}}
```

**Comment by jtcohen6** [comment]
Offhand, I'm not sure!

**Comment by dave-connors-3** [comment]
@jtcohen6 -- is there something different about actually having `return`s (i.e. in the test file i included above vs. the hardcoded newlines you added to your test case? My understanding is that the `raw_code` that ends up in the manifest would contain the `\n` characters, but is still able to parse it to the correct `compiled_code`

**Comment by jtcohen6** [comment]
Ahh - I wonder if this has to do with encoding!

When we read files, we expect to decode them from UTF-8:
https://github.com/dbt-labs/dbt-core/blob/73ff49720021334bd793e55d9d1a198a85ccef5d/core/dbt/clients/system.py#L98

I don't see us doing that for `--inline` at all. By the time we get [here[(https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/task/compile.py#L118), it appears that the string contents have already been escaped:
```python
ipdb> self.args.inline
'select {{\\n dbt_utils.group_by(5) \\n}}'
ipdb> self.args.inline.encode("utf-8")
b'select {{\\n dbt_utils.group_by(5) \\n}}'
ipdb> self.args.inline.encode("utf-8").decode("utf-8")
'select {{\\n dbt_utils.group_by(5) \\n}}'
```

Is this why we required that [SQL inputs for `dbt-RPC` be base64-encoded](https://github.com/dbt-labs/dbt-rpc/blob/c305bfc6cb1bd5861e364a202ba82804f20528b2/dbt_rpc/task/sql_commands.py#L64-L79)? Probably :)

I wonder if there's a way we can handle this within `dbt-core`, while still allowing users the convenience of passing in a human-friendly string! Perhaps with a custom [`click.ParamType`](https://click.palletsprojects.com/en/8.1.x/api/#click.ParamType)? Should we accept _either_ a human-friendly string, or safer bytes (UTF-8 encoded)?

**Comment by jtcohen6** [comment]
@aranke nice!! that's even better :)
