### ISSUE TITLE
[CT-2497] [Bug] dbt-core 1.5.0 breakage with dbt-utils 1.0.0

### ISSUE THREAD

**Issue by mshunk-eqr** [dbt-labs/dbt-core#7473]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After upgrading to dbt-core 1.5.0, running `dbt deps`, with our only package being dbt-utils revision 1.0.0, produces the following error included in "Relevant log output". Downgrading to dbt-core 1.4.6 solves the issue. 

### Expected Behavior

`dbt deps` should run successfully

### Steps To Reproduce

with package dependency in packages.yml
```
packages:
  - git: "https://github.com/dbt-labs/dbt-utils.git"
    revision: 1.0.0
```

`$ dbt deps`

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/python-venvs/rebuild3.8/bin/dbt", line 5, in <module>
    from dbt.main import main
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/main.py", line 12, in <module>
    import dbt.task.run as run_task
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/task/run.py", line 8, in <module>
    from dbt.node_runners import ModelRunner, RPCExecuteRunner
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/node_runners.py", line 5, in <module>
    from dbt.contracts.results import RunModelResult, collect_timing_info, \
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/contracts/results.py", line 4, in <module>
    from dbt.contracts.graph.manifest import COMPILE_RESULT_NODE_CONTRACT
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/contracts/graph/manifest.py", line 2, in <module>
    from dbt.contracts.graph.parsed import PARSED_NODE_CONTRACT, \
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/contracts/graph/parsed.py", line 5, in <module>
    import dbt.clients.jinja
  File "/home/user/python-venvs/rebuild3.8/lib/python3.8/site-packages/dbt/clients/jinja.py", line 7, in <module>
    import jinja2._compat
ModuleNotFoundError: No module named 'jinja2._compat'
```

### Environment

```markdown
- OS: Ubuntu 18.04
- Python: 3.8.0
- dbt:1.5.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@mshunk-eqr I have a sneaking suspicion that you may be running an _older_ version of `dbt-core`, rather than v1.5 — which did change the application's CLI entrypoint from `dbt.main` to `dbt.cli.main`.

- Could you try running `dbt --version` and `which dbt`?
- How do you install dbt?

**Comment by gshank** [comment]
I think you must have 0.15 of dbt, not 1.5.0

**Comment by mshunk-eqr** [comment]
I dug into the process that is handling our dependencies and it appears something caused us to install 0.14.3 rather than the latest version. This issue arose hours after 1.5.0 released so a bad assumption was made on my part. 

I will investigate further and update if I find anything interesting on the cause.
