### ISSUE TITLE
[CT-2505] [Regression] IndexError: list index out of range in dbt build

### ISSUE THREAD

**Issue by johnpkennedy** [dbt-labs/dbt-core#7483]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

I just upgraded to dbt 1.5. 

When I do the following:

```
dbt build
```

I get this `IndexError` exception:

```
19:29:28  Running with dbt=1.5.0
19:29:30  Found 453 models, 4529 tests, 4 snapshots, 0 analyses, 1329 macros, 2 operations, 10 seed files, 174 sources, 2 exposures, 0 metrics, 0 groups
19:29:30  
19:29:30  
19:29:30  Finished running  in 0 hours 0 minutes and 0.02 seconds (0.02s).
19:29:30  Encountered an error:
list index out of range
19:29:30  Traceback (most recent call last):
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 190, in exception_handler
    yield
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor = connection.handle.cursor()
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/contracts/connection.py", line 94, in handle
    self._handle.resolve(self)
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/contracts/connection.py", line 118, in resolve
    return self.opener(connection)
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 249, in open
    connect=connect_method_factory.get_connect_method(),
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 102, in get_connect_method
    "region": self.credentials.host.split(".")[2],
IndexError: list index out of range
```

### Expected/Previous Behavior

`dbt build` works normally

### Steps To Reproduce

Run `dbt build`

### Relevant log output

```shell
============================== 15:35:51.438795 | 8e454d26-b926-4cab-9105-f326cb0a8a18 ==============================
[0m15:35:51.438795 [info ] [MainThread]: Running with dbt=1.5.0
[0m15:35:51.442810 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': '/Users/john/Projects/maple-data/dbt/logs', 'profiles_dir': '/Users/johnkennedy/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'False'}
[0m15:35:51.597782 [debug] [MainThread]: checksum: 4568eb639a77b8fcb3a1f4a07856f42b1ff63f1376652889143968e1dbdafbda, vars: {}, profile: , target: , version: 1.5.0
[0m15:35:52.141330 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m15:35:52.141722 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m15:35:53.332999 [info ] [MainThread]: Found 453 models, 4529 tests, 4 snapshots, 0 analyses, 1329 macros, 2 operations, 10 seed files, 174 sources, 2 exposures, 0 metrics, 0 groups
[0m15:35:53.738635 [info ] [MainThread]: 
[0m15:35:53.740079 [debug] [MainThread]: Acquiring new redshift connection 'master'
[0m15:35:53.752678 [debug] [ThreadPool]: Acquiring new redshift connection 'list_warehouse'
[0m15:35:53.760415 [debug] [ThreadPool]: Using redshift connection "list_warehouse"
[0m15:35:53.760703 [debug] [ThreadPool]: On list_warehouse: select distinct nspname from pg_namespace
[0m15:35:53.760841 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m15:35:53.761002 [debug] [ThreadPool]: Redshift adapter: Error running SQL: select distinct nspname from pg_namespace
[0m15:35:53.761130 [debug] [ThreadPool]: Redshift adapter: Rolling back transaction.
[0m15:35:53.761251 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m15:35:53.761395 [debug] [ThreadPool]: Redshift adapter: Error running SQL: macro list_schemas
[0m15:35:53.761513 [debug] [ThreadPool]: Redshift adapter: Rolling back transaction.
[0m15:35:53.761623 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m15:35:53.762128 [debug] [MainThread]: Connection 'master' was properly closed.
[0m15:35:53.762247 [debug] [MainThread]: Connection 'list_warehouse' was properly closed.
[0m15:35:53.762375 [info ] [MainThread]: 
[0m15:35:53.762548 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.02 seconds (0.02s).
[0m15:35:53.762774 [error] [MainThread]: Encountered an error:
list index out of range
[0m15:35:53.768563 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 190, in exception_handler
    yield
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor = connection.handle.cursor()
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/contracts/connection.py", line 94, in handle
    self._handle.resolve(self)
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/contracts/connection.py", line 118, in resolve
    return self.opener(connection)
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 249, in open
    connect=connect_method_factory.get_connect_method(),
  File "/Users/john/.local/share/virtualenvs/dbt--3QRDvUu/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 102, in get_connect_method
    "region": self.credentials.host.split(".")[2],
IndexError: list index out of range
```

### Environment

```markdown
- OS: macOS 13.2.1
- Python: Python 3.10.11
- dbt (working version): 1.4.6
- dbt (regression version):  1.5.0
```

### Which database adapter are you using with dbt?

redshift

**Comment by jeremyyeo** [comment]
Hey @johnpkennedy - I believe this is the same as this issue in the dbt-redshift repo: https://github.com/dbt-labs/dbt-redshift/issues/419

**Comment by dbeatty10** [comment]
Thanks for reporting this @johnpkennedy !

Yes, agreed @jeremyyeo 👍

I'm going to close this as covered by https://github.com/dbt-labs/dbt-redshift/issues/419 which will be fixed in the next patch release of dbt-redshift.
