### ISSUE TITLE
[CT-2516] [Bug] Upgrade to 1.5.0 generates "TypeError: argument of type 'PosixPath' is not iterable" on model runs.

### ISSUE THREAD

**Issue by christopherekfeldt** [dbt-labs/dbt-core#7495]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We just upgraded our poetry packages for dbt-core and dbt-bigquery to 1.5.0.

When running: poetry run dbt --version everything works fine. But when calling a model like:

poetry run dbt run -s model_name
poetry run dbt build -s model_name

We get a new error never seen before.

### Expected Behavior

That the models get built as prior with the normal CLI output.

### Steps To Reproduce

1. Update pyproject.toml with setting dbt-core & dbt-bigquery versions to "1.5.0"
2. run "poetry update"
3. run "poetry run dbt --version"
4. Verify that it outputs the correct versions
![image](https://user-images.githubusercontent.com/17338299/235943843-93f8b61c-fbdf-4012-9afc-88b1b8ef9e68.png)
5. run "poetry run dbt run -s name_of_model" 

### Relevant log output

```shell
14:13:06  Running with dbt=1.5.0
14:13:49  Encountered an error:
argument of type 'PosixPath' is not iterable
14:13:49  Traceback (most recent call last):
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 215, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/manifest.py", line 227, in get_full_manifest
    manifest = loader.load()
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/manifest.py", line 386, in load
    self.parse_project(
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/manifest.py", line 539, in parse_project
    hook_parser.parse_file(file_block)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/hooks.py", line 120, in parse_file
    self.parse_node(hook)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/base.py", line 394, in parse_node
    self.render_update(node, config)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/base.py", line 370, in render_update
    context = self.render_with_context(node, config)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/base.py", line 240, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/clients/jinja.py", line 591, in get_rendered
    return render_template(template, ctx, node)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/clients/jinja.py", line 546, in render_template
    return template.render(ctx)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: argument of type 'PosixPath' is not iterable
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt: 1.5.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by jtcohen6** [comment]
@christopherekfeldt Thanks for opening! I'm going to label this as a potential `regression` for v1.5.

It's weird that this is happening _during_ project parsing. Based on the error message and occurrence, I'd guess that you're accessing a flag that's being passed in, and trying to loop over it (?).

Educated guesses - any chance you're doing one of the following?
- Referencing the [`invocation_args_dict`](https://docs.getdbt.com/reference/dbt-jinja-functions/flags#invocation_args_dict) context variable somewhere in your project
- Have a package installed that's doing this, i.e. [`dbt_artifacts`](https://github.com/brooklyn-data/dbt_artifacts/blob/139ebf87a4b56197196e5827c1af75ef9c1de8fe/macros/upload_invocations.sql#L66)

**Comment by christopherekfeldt** [comment]
No I don't think so. I searched it and found nothing in our project reflecting "invocation_args_dict".

These are the packages specified in our packages.yml:

packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0

  - package: dbt-labs/codegen
    version: 0.9.0

  - package: elementary-data/elementary
    version: 0.7.5

  - package: calogica/dbt_expectations
    version: 0.8.5

On the last part my answer is no, we only have one project dir and a common profile in our dbt root folder.
The only connection to dbt apart from installing the tools dbt-core and dbt-bigquery with Poetry is the tool sqlfluff-templater-dbt = "2.0.3" which we use for pre-commit together with sqlfluff. But can't see how that is correlated with the parsing of the project.

**Comment by joellabes** [comment]
Heads up that the elementary package uses the invocation_args_dict variable: 

https://github.com/elementary-data/dbt-data-reliability/blob/0.7.5/macros/edr/dbt_artifacts/upload_dbt_invocation.sql#L55-L90

**Comment by christopherekfeldt** [comment]
Okay, commented out all packages besides dbt-utils and removed dbt_packages/ folder and rerun "poetry run dbt deps".

Getting the same output still when running dbt compile/run/build -s model_name

**Comment by jtcohen6** [comment]
> Heads up that the elementary package uses the invocation_args_dict variable:

That felt like a promising lead! However:
- I tried installing the package into an empty project, and I was able to run everything without a problem.
- It sounds like @christopherekfeldt removed the package, and is still seeing the same error

On looking again at the stacktrace, I'm now seeing that the error seems to crop up during _hook_ parsing:
```
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/manifest.py", line 539, in parse_project
    hook_parser.parse_file(file_block)
  File "/mnt/c/git/bica-dbt/dbt/.venv/lib/python3.8/site-packages/dbt/parser/hooks.py", line 120, in parse_file
    self.parse_node(hook)
```

@christopherekfeldt Do you have any `on-run-start` or `on-run-end` hooks defined in `dbt_project.yml`? Do any of them make use of [the `flags` variable](https://docs.getdbt.com/reference/dbt-jinja-functions/flags)?
