### ISSUE TITLE
[CT-2579] CREATE VIEW is only supported with v1 tables.

### ISSUE THREAD

**Issue by massivedfish** [dbt-labs/dbt-core#7620]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

1. env conda python=3.9 dbt-spark=1.2.1/1.5.0   
2. dbt init    method: thrift.    
3. dbt debug pass 
4. dbt run  error 
error: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: CREATE VIEW is only supported with v1 tables.

question: i don't understand  this question  and i use other project is pass. 
 

other project: dbt  pip dependence dbt-core==1.2.1 dbt-spark==1.2.0 "dbt-spark[PyHive]" pyspark==3.1.3  is pass。 

### Expected Behavior

i want understand this  and resolve this   thanks 

### Steps To Reproduce

en: mac 
  1. conda python 3.9 
  2. pip install dbt-spark & "dbt-spark[PyHive]"
  3. dbt debug pass 
  4. dbt run     ......   error. 
  
en: windows 
  1. conda python 3.9 
  2. pip install dbt-spark & "dbt-spark[PyHive]"
  3. dbt debug pass 
  4. dbt run     ......   error. 

### Relevant log output

```shell
2 of 2 ERROR creating view model mds_demo.my_second_dbt_model .................. [ERROR in 0.35s]
22:56:33  
22:56:33  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 5.21 seconds (5.21s).
22:56:33  
22:56:33  Completed with 1 error and 0 warnings:
22:56:33  
22:56:33  Runtime Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)
22:56:33    Database Error
22:56:33      org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: CREATE VIEW is only supported with v1 tables.
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:362)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:264)
22:56:33      	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties(SparkOperation.scala:78)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties$(SparkOperation.scala:62)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:43)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:264)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:259)
22:56:33      	at java.security.AccessController.doPrivileged(Native Method)
22:56:33      	at javax.security.auth.Subject.doAs(Subject.java:422)
22:56:33      	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:273)
22:56:33      	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22:56:33      	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:56:33      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22:56:33      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22:56:33      	at java.lang.Thread.run(Thread.java:750)
22:56:33      Caused by: org.apache.spark.sql.AnalysisException: CREATE VIEW is only supported with v1 tables.
22:56:33      	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog.org$apache$spark$sql$catalyst$analysis$ResolveSessionCatalog$$parseV1Table(ResolveSessionCatalog.scala:595)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog$$anonfun$apply$1.applyOrElse(ResolveSessionCatalog.scala:517)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog$$anonfun$apply$1.applyOrElse(ResolveSessionCatalog.scala:48)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$3(AnalysisHelper.scala:90)
22:56:33      	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:74)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:90)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:223)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog.apply(ResolveSessionCatalog.scala:48)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.ResolveSessionCatalog.apply(ResolveSessionCatalog.scala:39)
22:56:33      	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:216)
22:56:33      	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
22:56:33      	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
22:56:33      	at scala.collection.immutable.List.foldLeft(List.scala:89)
22:56:33      	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:213)
22:56:33      	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:205)
22:56:33      	at scala.collection.immutable.List.foreach(List.scala:392)
22:56:33      	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:205)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:198)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:192)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:155)
22:56:33      	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:183)
22:56:33      	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
22:56:33      	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:183)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:176)
22:56:33      	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:230)
22:56:33      	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:175)
22:56:33      	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:73)
22:56:33      	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
22:56:33      	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
22:56:33      	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
22:56:33      	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
22:56:33      	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:73)
22:56:33      	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:71)
22:56:33      	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:63)
22:56:33      	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:98)
22:56:33      	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
22:56:33      	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
22:56:33      	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
22:56:33      	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
22:56:33      	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
22:56:33      	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
22:56:33      	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:326)
22:56:33      	... 16 more
22:56:33
```

### Environment

```markdown
-mac m1  14  os 13  and win 12700cpu win11 

-python: 3.9  

-dbt: 1.2.1 or 1.5 

-spark 1.2.1 or 1.5
```

### Which database adapter are you using with dbt?

spark

### Additional Context

22:56:27  Running with dbt=1.2.1
22:56:27  Partial parse save file not found. Starting full parse.
22:56:28  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 293 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
22:56:28  
22:56:31  Concurrency: 1 threads (target='dev')
22:56:31  
22:56:31  1 of 2 START table model mds_demo.my_first_dbt_model ........................... [RUN]
22:56:33  1 of 2 OK created table model mds_demo.my_first_dbt_model ...................... [OK in 1.50s]
22:56:33  2 of 2 START view model mds_demo.my_second_dbt_model ........................... [RUN]
22:56:33  2 of 2 ERROR creating view model mds_demo.my_second_dbt_model .................. [ERROR in 0.35s]
22:56:33  
22:56:33  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 5.21 seconds (5.21s).

**Comment by massivedfish** [comment]
done-
answer: spark version is not supply v2 table  and this is  not friended  for dbt , I build hadoop and hive spark   and try dbt run 
that  is successful
