### ISSUE TITLE
[CT-2608] Got typeError when running sqlfluff after upgrading to dbt-core v1.4

### ISSUE THREAD

**Issue by amorqiu** [dbt-labs/dbt-core#7731]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
INFO:__main__:Getting list of modified models
INFO:__main__:Got 1 modified models
INFO:__main__:Starting sqlfluff fix on xxxx(model_name)
==== finding fixable violations ====
=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 989, in fix
    _paths_fix(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 787, in _paths_fix
    result: LintingResult = linter.lint_paths(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1206, in lint_paths
    for i, linted_file in enumerate(runner.run(expanded_paths, fix), start=1):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 106, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 59, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 42, in iter_rendered
    for fname in self.linter.templater.sequence_files(
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 277, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 149, in dbt_manifest
    self.dbt_manifest = ManifestLoader.get_full_manifest(self.dbt_config)
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 111, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
  File "/usr/local/lib/python3.9/site-packages/dbt/config/runtime.py", line 263, in from_args
    project, profile = cls.collect_parts(args)
  File "/usr/local/lib/python3.9/site-packages/dbt/config/runtime.py", line 205, in collect_parts
    cli_vars: Dict[str, Any] = parse_cli_vars(getattr(args, "vars", "{}"))
  File "/usr/local/lib/python3.9/site-packages/dbt/config/utils.py", line 16, in parse_cli_vars
    return parse_cli_yaml_string(var_string, "vars")
  File "/usr/local/lib/python3.9/site-packages/dbt/config/utils.py", line 21, in parse_cli_yaml_string
    cli_vars = yaml_helper.load_yaml_text(var_string)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/yaml_helper.py", line 56, in load_yaml_text
    return safe_load(contents)
  File "/usr/local/lib/python3.9/site-packages/dbt/clients/yaml_helper.py", line 51, in safe_load
    return yaml.load(contents, Loader=SafeLoader)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.9/site-packages/yaml/cyaml.py", line 26, in __init__
    CParser.__init__(self, stream)
  File "yaml/_yaml.pyx", line 288, in yaml._yaml.CParser.__init__
TypeError: a string or stream input is required
INFO:__main__:Linting errors found, run the fix script or modify your files manually

### Expected Behavior

expected no error and showing where linting error is

### Steps To Reproduce

Running this `dbt scripts/sqlfluff.py '--method' 'fix' --state target-prod --path (model_name)` should only return linting errors but now it's returning _```
TypeError: a string or stream input is required
INFO:__main__:Linting errors found, run the fix script or modify your files manually
```_

### Relevant log output

_No response_

### Environment

```markdown
- OS: macOS Ventura 13.3.1
- Python:3.6.8
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

bigquery

**Comment by jtcohen6** [comment]
@amorqiu @moleary-gsa Thanks for reporting!

Here's the deal: The latest version of `sqlfluff-templater-dbt` is compatible with dbt-core v1.5, but it does not seem backward compatible with older versions.

Relevant bit from the stracktrace:
```
  File "/workspaces/forcasting/.venv/lib/python3.10/site-packages/sqlfluff_templater_dbt/templater.py", line 111, in dbt_config
    self.dbt_config = DbtRuntimeConfig.from_args(
  File "/workspaces/forcasting/.venv/lib/python3.10/site-packages/dbt/config/runtime.py", line 263, in from_args
    project, profile = cls.collect_parts(args)
  File "/workspaces/forcasting/.venv/lib/python3.10/site-packages/dbt/config/runtime.py", line 205, in collect_parts
    cli_vars: Dict[str, Any] = parse_cli_vars(getattr(args, "vars", "{}"))
  File "/workspaces/forcasting/.venv/lib/python3.10/site-packages/dbt/config/utils.py", line 16, in parse_cli_vars
    return parse_cli_yaml_string(var_string, "vars")
  File "/workspaces/forcasting/.venv/lib/python3.10/site-packages/dbt/config/utils.py", line 21, in parse_cli_yaml_string
    cli_vars = yaml_helper.load_yaml_text(var_string)
...
  File "yaml/_yaml.pyx", line 288, in yaml._yaml.CParser.__init__
TypeError: a string or stream input is required
```

Here's where SQLFluff is preparing the config to pass into `dbt-core`:

- [`dbt_config`](https://github.com/sqlfluff/sqlfluff/blob/d93338915615c3770887d87df692ebabb81cdba1/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py#L98-L122)
- [`_get_cli_vars`](https://github.com/sqlfluff/sqlfluff/blob/d93338915615c3770887d87df692ebabb81cdba1/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py#L242-L247)

The relevant codepath in `dbt-core` changed quite a bit between v1.4 and v1.5. The related changes in `sqlfluff` were in https://github.com/sqlfluff/sqlfluff/pull/4828, and perhaps specifically this comment: https://github.com/sqlfluff/sqlfluff/pull/4828/files#r1181276005.

The simplest move here might be to ask the sqlfluff folks to require `dbt-core>=1.5.0` for the latest versions of `sqlfluff-templater-dbt`. In the meantime, you could try installing an older version for use with dbt-core v1.4.
