### ISSUE TITLE
[CT-2762] [Bug] json output can not be parsed

### ISSUE THREAD

**Issue by qrtt1** [dbt-labs/dbt-core#7987]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

```
(venv) (⎈ |kind-kind:default)(base) ➜  jaffle_shop git:(main) ✗ dbt --version
Core:
  - installed: 1.5.2
  - latest:    1.5.2 - Up to date!

Plugins:
  - duckdb: 1.5.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```
```
(venv) (⎈ |kind-kind:default)(base) ➜  jaffle_shop git:(main) ✗ dbt list --output json | jq ".name"
parse error: Invalid numeric literal at line 1, column 2
--- Logging error ---
Traceback (most recent call last):
  File "/Users/qrtt1/miniforge3/lib/python3.10/logging/__init__.py", line 1104, in emit
    self.flush()
  File "/Users/qrtt1/miniforge3/lib/python3.10/logging/__init__.py", line 1084, in flush
    self.stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/Users/qrtt1/Downloads/jaffle_shop/venv/bin/dbt", line 8, in <module>
    sys.exit(cli())
  File "/Users/qrtt1/Downloads/jaffle_shop/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/qrtt1/Downloads/jaffle_shop/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/qrtt1/Downloads/jaffle_shop/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/qrtt1/Downloads/jaffle_shop/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
```

### Expected Behavior

```
(venv) (⎈ |kind-kind:default)(base) ➜  jaffle_shop git:(main) ✗ dbt --version
Core:
  - installed: 1.4.6
  - latest:    1.5.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - duckdb: 1.4.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

```
(venv) (⎈ |kind-kind:default)(base) ➜  jaffle_shop git:(main) ✗ dbt list --output json | jq ".name"
"revenue"
"customers"
"orders"
"stg_customers"
"stg_orders"
"stg_payments"
"raw_customers"
"raw_orders"
"raw_payments"
"accepted_values_orders_status__placed__shipped__completed__return_pending__returned"
"accepted_values_stg_orders_status__placed__shipped__completed__return_pending__returned"
"accepted_values_stg_payments_payment_method__credit_card__coupon__bank_transfer__gift_card"
"not_null_customers_customer_id"
"not_null_orders_amount"
"not_null_orders_bank_transfer_amount"
"not_null_orders_coupon_amount"
"not_null_orders_credit_card_amount"
"not_null_orders_customer_id"
"not_null_orders_gift_card_amount"
"not_null_orders_order_id"
"not_null_stg_customers_customer_id"
"not_null_stg_orders_order_id"
"not_null_stg_payments_payment_id"
"relationships_orders_customer_id__customer_id__ref_customers_"
"unique_customers_customer_id"
"unique_orders_order_id"
"unique_stg_customers_customer_id"
"unique_stg_orders_order_id"
"unique_stg_payments_payment_id"
```

### Steps To Reproduce

1. In dbt 1.5
2. run dbt list in jaffle_shop example
3. see extra log with the json output

### Relevant log output

```shell
(venv) (⎈ |kind-kind:default)(base) ➜  jaffle_shop git:(main) ✗ dbt list --output json | head
11:40:24  Running with dbt=1.5.2
11:40:25  Registered adapter: duckdb=1.5.0
11:40:25  Found 5 models, 20 tests, 0 snapshots, 0 analyses, 314 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 1 metric, 0 groups
{"name": "revenue", "resource_type": "metric", "package_name": "jaffle_shop", "original_file_path": "models/revenue.yml", "unique_id": "metric.jaffle_shop.revenue", "tags": ["piperider"], "config": {"enabled": true, "group": null}, "depends_on": {"macros": [], "nodes": ["model.jaffle_shop.orders"]}}
{"name": "customers", "resource_type": "model", "package_name": "jaffle_shop", "original_file_path": "models/customers.sql", "unique_id": "model.jaffle_shop.customers", "alias": "customers", "config": {"enabled": true, "alias": null, "schema": null, "database": null, "tags": ["piperider"], "meta": {}, "group": null, "materialized": "table", "incremental_strategy": null, "persist_docs": {}, "quoting": {}, "column_types": {}, "full_refresh": null, "unique_key": null, "on_schema_change": "ignore", "grants": {}, "packages": [], "docs": {"show": true, "node_color": null}, "contract": {"enforced": false}, "post-hook": [], "pre-hook": []}, "tags": ["piperider"], "depends_on": {"macros": [], "nodes": ["model.jaffle_shop.stg_customers", "model.jaffle_shop.stg_orders", "model.jaffle_shop.stg_payments"]}}
{"name": "orders", "resource_type": "model", "package_name": "jaffle_shop", "original_file_path": "models/orders.sql", "unique_id": "model.jaffle_shop.orders", "alias": "orders", "config": {"enabled": true, "alias": null, "schema": null, "database": null, "tags": ["piperider"], "meta": {}, "group": null, "materialized": "table", "incremental_strategy": null, "persist_docs": {}, "quoting": {}, "column_types": {}, "full_refresh": null, "unique_key": null, "on_schema_change": "ignore", "grants": {}, "packages": [], "docs": {"show": true, "node_color": null}, "contract": {"enforced": false}, "post-hook": [], "pre-hook": []}, "tags": ["piperider"], "depends_on": {"macros": [], "nodes": ["model.jaffle_shop.stg_orders", "model.jaffle_shop.stg_payments"]}}
{"name": "stg_customers", "resource_type": "model", "package_name": "jaffle_shop", "original_file_path": "models/staging/stg_customers.sql", "unique_id": "model.jaffle_shop.stg_customers", "alias": "stg_customers", "config": {"enabled": true, "alias": null, "schema": null, "database": null, "tags": ["piperider"], "meta": {}, "group": null, "materialized": "view", "incremental_strategy": null, "persist_docs": {}, "quoting": {}, "column_types": {}, "full_refresh": null, "unique_key": null, "on_schema_change": "ignore", "grants": {}, "packages": [], "docs": {"show": true, "node_color": null}, "contract": {"enforced": false}, "post-hook": [], "pre-hook": []}, "tags": ["piperider"], "depends_on": {"macros": [], "nodes": ["seed.jaffle_shop.raw_customers"]}}
{"name": "stg_orders", "resource_type": "model", "package_name": "jaffle_shop", "original_file_path": "models/staging/stg_orders.sql", "unique_id": "model.jaffle_shop.stg_orders", "alias": "stg_orders", "config": {"enabled": true, "alias": null, "schema": null, "database": null, "tags": ["piperider"], "meta": {}, "group": null, "materialized": "view", "incremental_strategy": null, "persist_docs": {}, "quoting": {}, "column_types": {}, "full_refresh": null, "unique_key": null, "on_schema_change": "ignore", "grants": {}, "packages": [], "docs": {"show": true, "node_color": null}, "contract": {"enforced": false}, "post-hook": [], "pre-hook": []}, "tags": ["piperider"], "depends_on": {"macros": [], "nodes": ["seed.jaffle_shop.raw_orders"]}}
{"name": "stg_payments", "resource_type": "model", "package_name": "jaffle_shop", "original_file_path": "models/staging/stg_payments.sql", "unique_id": "model.jaffle_shop.stg_payments", "alias": "stg_payments", "config": {"enabled": true, "alias": null, "schema": null, "database": null, "tags": ["piperider"], "meta": {}, "group": null, "materialized": "view", "incremental_strategy": null, "persist_docs": {}, "quoting": {}, "column_types": {}, "full_refresh": null, "unique_key": null, "on_schema_change": "ignore", "grants": {}, "packages": [], "docs": {"show": true, "node_color": null}, "contract": {"enforced": false}, "post-hook": [], "pre-hook": []}, "tags": ["piperider"], "depends_on": {"macros": [], "nodes": ["seed.jaffle_shop.raw_payments"]}}
{"name": "raw_customers", "resource_type": "seed", "package_name": "jaffle_shop", "original_file_path": "seeds/raw_customers.csv", "unique_id": "seed.jaffle_shop.raw_customers", "alias": "raw_customers", "config": {"enabled": true, "alias": null, "schema": null, "database": null, "tags": [], "meta": {}, "group": null, "materialized": "seed", "incremental_strategy": null, "persist_docs": {}, "quoting": {}, "column_types": {}, "full_refresh": null, "unique_key": null, "on_schema_change": "ignore", "grants": {}, "packages": [], "docs": {"show": true, "node_color": null}, "contract": {"enforced": false}, "quote_columns": null, "post-hook": [], "pre-hook": []}, "tags": [], "depends_on": {"macros": []}}
```

### Environment

```markdown
- OS: OSX (`kern.version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000`)
- Python 3.10.6
- dbt: 1.5.2
- adapter: duckdb
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

**Comment by jtcohen6** [comment]
Hey @qrtt1! Two things going on here:
1. Starting in v1.5, `list` will include `info`-level logging by default. You can disable this (return to previous default behavior) by passing either the `--quiet` or `--log-level warn` flags in addition. This is called out in the [v1.5 upgrade guide](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5#behavior-changes).
2. It's possible that you have a parsing error. I'd recommend setting `--log-format json` as well, so that it will be intelligible to `jq`.

Give this a try:
```
dbt --log-format json --log-level warn list --output json | jq ".name"
```

**Comment by qrtt1** [comment]
@jtcohen6 thanks the `--quiet` is very useful in my case.

**Comment by dbeatty10** [comment]
Awesome @qrtt1 ! Since it sounds like this is working for you, I'm going to close this.

I've opened https://github.com/dbt-labs/dbt-core/issues/7994 for further discussion to see if we do (or don't) want to automatically set `--quiet` whenever `--output json`.
