### ISSUE TITLE
[CT-2852] [v1.6 pre-regression] `dbt show` swallows database errors

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#8166]
### Previous behavior (v1.5)

```
$ dbt show --inline 'slect asdlkjfsld;j'
12:33:08  Running with dbt=1.5.2
12:33:08  Registered adapter: postgres=1.5.2
12:33:08  Unable to do partial parsing because of a version mismatch
12:33:09  Found 7 models, 0 tests, 0 snapshots, 0 analyses, 307 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 1 group
12:33:09
12:33:09  Concurrency: 5 threads (target='postgres')
12:33:09
12:33:09  Encountered an error:
Runtime Error
  Database Error in sql operation inline_query (from remote system.sql)
    syntax error at or near "slect"
    LINE 2: slect asdlkjfsld;j
            ^
```

### Current behavior (v1.6.0rc1)

```
$ dbt show --inline 'slect asdlkjfsld;j'
12:32:16  Running with dbt=1.6.0-rc1
12:32:17  Registered adapter: postgres=1.6.0-rc1
12:32:17  Found 7 models, 0 sources, 0 exposures, 0 metrics, 349 macros, 1 group, 0 semantic models
12:32:17
12:32:17  Concurrency: 5 threads (target='postgres')
12:32:17
12:32:17  Encountered an error:
'NoneType' object has no attribute 'print_table'
12:32:17  Traceback (most recent call last):
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 219, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 259, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/main.py", line 398, in show
    results = task.run()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/task/runnable.py", line 485, in run
    self.task_end_messages(result.results)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/task/show.py", line 85, in task_end_messages
    table.print_table(output=output, max_rows=None)
AttributeError: 'NoneType' object has no attribute 'print_table'
```

### Context

- We'll need to backport the fix for this to `1.6.latest`, for inclusion in v1.6 RC2/final
- This behavior affects both `dbt show --inline` and `dbt show --select` specific models.
- This doesn't currently affect the dbt Cloud IDE, which pulls the error message out of the debug-level logs. Still, we should fix this for everyone.

**Comment by jtcohen6** [comment]
@aranke I'm going to assign you since you're currently on support rotation, and given your familiarity with the `dbt show` implementation

**Comment by MichelleArk** [comment]
Worth noting that this is a regression since 1.6.0rc1. 1.6.0b8 was working as expected: 

```sh
❯ dbt show --inline 'slect asdlkjfsld;j' --project-dir ~/src/jaffle_shop
19:20:17  Running with dbt=1.6.0-b8
19:20:17  target not specified in profile 'postgres', using 'default'
19:20:17  Registered adapter: postgres=1.7.0-a1
19:20:17  Unable to do partial parsing because of a version mismatch
19:20:18  Found 8 models, 20 tests, 0 snapshots, 0 analyses, 349 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
19:20:18  
19:20:18  Concurrency: 1 threads (target='default')
19:20:18  
19:20:18  Encountered an error:
Runtime Error
  Database Error in sql_operation inline_query (from remote system.sql)
    syntax error at or near "slect"
    LINE 2: slect asdlkjfsld;j
            ^
```

**Comment by MichelleArk** [comment]
Root cause is this `return` statement within a `finally` clause: https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/task/runnable.py#L386

From: https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions
> If the finally clause executes a [break](https://docs.python.org/3/reference/simple_stmts.html#break), [continue](https://docs.python.org/3/reference/simple_stmts.html#continue) or [return](https://docs.python.org/3/reference/simple_stmts.html#return) statement, exceptions are not re-raised.

Will put up a fix shortly!
