### ISSUE TITLE
[Feature] Give node information when raising ValidationError

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-core#8276]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

https://github.com/dbt-labs/dbt-core/pull/6025 added validation errors for materializations.  This is useful, however they don't tell you which node the error was found in, which can make for a fun needle-in-haystack operation as found by [this slack user](https://getdbt.slack.com/archives/CBSQTAPLG/p1690955453824599).

This feature would be to include the node in the error message

### Describe alternatives you've considered

Searching manually

### Who will this benefit?

Folks who misconfigure things by accident.

### Are you interested in contributing this feature?

YES!

**Comment by graciegoheen** [comment]
Thanks for opening! I was able to reproduce this locally and agree that it would be clearer to specify _which_ node has the inappropriate materialization in the error message.

**Comment by dbeatty10** [comment]
### Reprex
[Here's](https://github.com/dbt-labs/dbt-core/issues/8634#issuecomment-1716629812) one reproduction case (which was reported in duplicate issue https://github.com/dbt-labs/dbt-core/issues/8634).

Interestingly, dbt 1.3 included the path to the relevant file within the error message, but >=1.4 does not.

**Comment by dbeatty10** [comment]
The final piece of code that builds the error message is here:
https://github.com/dbt-labs/dbt-core/blob/3f5ebe81b9039b33a57b9aa8b1f5cb1edcd8790f/core/dbt/exceptions.py#L153

**Comment by jeremyyeo** [comment]
Another case of "point users to the exact file on error" but I don't think it's specifically a `ValidationError`.

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table
```

```sql
-- models/foo.sql
{{ config(materialized=-'table') }}

select 1 id
```

```sh
$ dbt run
21:51:14  Running with dbt=1.6.3
21:51:16  Registered adapter: snowflake=1.6.2
21:51:17  Encountered an error:
bad operand type for unary -: 'str'
21:51:17  Traceback (most recent call last):
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/cli/requires.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/cli/requires.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/cli/requires.py", line 219, in wrapper
    return func(*args, **kwargs)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/cli/requires.py", line 246, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/manifest.py", line 315, in get_full_manifest
    manifest = loader.load()
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/manifest.py", line 474, in load
    self.parse_project(
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/manifest.py", line 670, in parse_project
    parser.parse_file(block)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/base.py", line 466, in parse_file
    self.parse_node(file_block)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/base.py", line 427, in parse_node
    self.render_update(node, config)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/models.py", line 360, in render_update
    super().render_update(node, config)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/base.py", line 403, in render_update
    context = self.render_with_context(node, config)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/parser/base.py", line 263, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/clients/jinja.py", line 600, in get_rendered
    rendered = render_template(template, ctx, node)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/dbt/clients/jinja.py", line 546, in render_template
    return template.render(ctx)
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/jeremy/src/dbt-basic/venv_dbt_1.6.latest/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: bad operand type for unary -: 'str'
```

You can read in our internal Slack [thread](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1695834206827339) - a user probably accidentally added a negative to a string somewhere but hard to know exactly where when you have very many files.

**Comment by dbeatty10** [comment]
### Acceptance criteria

We should do one of the following:
1. Restore the same / similar error message as was in dbt 1.3 (as described in #8634), or
2. Replace `at path []` with `at path ["snapshots/model_b.sql"]`, or
3. Replace `Parsing Error` with `Parsing Error in snapshots/model_b.sql` (as described in #9033)

And add functional tests, of course 😎

### Reproduction cases

These can be used to help design the functional tests:
- https://github.com/dbt-labs/dbt-core/issues/8634#issuecomment-1716629812
- https://github.com/dbt-labs/dbt-core/issues/9033
