### ISSUE TITLE
[CT-2948] [Regression] Visible stack trace when using `control+c`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#8338]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Starting in dbt-core 1.5.0, there's a long stack trace when using `control+c`:

```
22:57:10  1 of 4 START sql table model dbt_dbeatty.my_model_1 ............................ [RUN]
^C
22:57:11  CANCEL query model.my_project.my_model_1 ....................................... [CANCEL]
22:57:12  1 of 4 OK created sql table model dbt_dbeatty.my_model_1 ....................... [SUCCESS 1 in 1.55s]
22:57:12  
22:57:12  Exited because of keyboard interrupt
22:57:12  
22:57:12  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
22:57:12  
22:57:12  Finished running  in 0 hours 0 minutes and 3.55 seconds (3.55s).
22:57:12  Encountered an error:

22:57:12  Traceback (most recent call last):
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 215, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 250, in wrapper
    return func(*args, **kwargs)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/main.py", line 568, in run
    results = task.run()
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/task/runnable.py", line 448, in run
    result = self.execute_with_hooks(selected_uids)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/task/runnable.py", line 406, in execute_with_hooks
    res = self.execute_nodes()
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/task/runnable.py", line 352, in execute_nodes
    self.run_queue(pool)
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/task/runnable.py", line 260, in run_queue
    node = self.job_queue.get()
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/graph/queue.py", line 125, in get
    _, node_id = self.inner.get(block=block, timeout=timeout)
  File "/Users/dbeatty/.pyenv/versions/3.8.13/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "/Users/dbeatty/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Expected/Previous Behavior

But in dbt-core 1.4, it exits without a long stack trace:

```
22:56:25  1 of 4 START sql table model dbt_dbeatty.my_model_1 ............................ [RUN]
^C
22:56:27  CANCEL query model.my_project.my_model_1 ....................................... [CANCEL]
22:56:27  CANCEL query list_analytics_dev_dbt_dbeatty .................................... [CANCEL]
22:56:27  1 of 4 OK created sql table model dbt_dbeatty.my_model_1 ....................... [SUCCESS 1 in 1.64s]
22:56:27  
22:56:27  Exited because of keyboard interrupt.
22:56:27  
22:56:27  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
22:56:27  
22:56:27  Finished running  in 0 hours 0 minutes and 4.31 seconds (4.31s).
22:56:27  ctrl-c
```

### Steps To Reproduce

1. `dbt run` with a sufficient number of models so they don't finish too quickly
2. While it is running, do `Control+C`

### Environment

```markdown
- dbt (working version): 1.4.x
- dbt (regression version): 1.5.x
```

### Additional Context

Once we track down the origin of the regression please update the ticket description with a link to the commit origin and let EM know. Thank you!

This was discovered when researching fixes for https://github.com/dbt-labs/dbt-redshift/issues/553

**Comment by graciegoheen** [comment]
From refinement meeting:
- still seeing this in 1.6
- for keyboard interrupt

**Comment by peterallenwebb** [comment]
@graciegoheen @dbeatty10 I actually like that we have this backtrace on Ctrl-C. It allowed me to zero in on a performance issue, since a user was able to provide information about what dbt was doing when they hit Ctrl-C.

If we thinks this looks sloppy or unprofessional, I don't have a problem changing the behavior back, but I like the way it is now.

**Comment by dbeatty10** [comment]
Thanks for that insight @peterallenwebb ! 🧠

If the full stack trace was still visible in `logs/dbt.log` but not in standard out, would that still be helpful enough for your use case?

**Comment by dbeatty10** [comment]
### Proposed acceptance criteria
- Full stack trace is visible within logs (i.e., `logs/dbt.log`)
- Standard out has a short error message without the full stack trace (see below)

#### Logs

```
22:57:12  Traceback (most recent call last):
  File "/Users/dbeatty/projects/environments/snowflake_1.5/lib/python3.8/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
...
  File "/Users/dbeatty/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

#### Standard out
```
...
22:56:27  1 of 4 OK created sql table model dbt_dbeatty.my_model_1 ....................... [SUCCESS 1 in 1.64s]
22:56:27  
22:56:27  Exited because of keyboard interrupt.
22:56:27  
22:56:27  Done. PASS=0 WARN=0 ERROR=0 SKIP=0 TOTAL=0
22:56:27  
22:56:27  Finished running  in 0 hours 0 minutes and 4.31 seconds (4.31s).
22:56:27  ctrl-c
```
