### ISSUE TITLE
[CT-2990] [Bug] Docker build with dbt_third_party=dbt-sqlserver creates non-executable image

### ISSUE THREAD

**Issue by raginjason** [dbt-labs/dbt-core#8406]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Building a `dbt-sqlserver` image works, but will not execute because it is missing `libodbc.so.2` from the `libodbc1` package. Once `libodbc1` is installed, `msodbcsql18` or similar will need to be installed in order to actually connect to SQL Server.

### Expected Behavior

A `dbt-sqlserver` image that can connect to SQL Server without error 

### Steps To Reproduce

Note that the dbt version here is older because dbt-sqlserver [will not work with the latest version of dbt](https://github.com/dbt-msft/dbt-sqlserver/issues/421).

1. Build third party docker image with `dbt-sqlserver`:
```
cd docker
docker  build \
  --tag dbt-sqlserver:1.4.3 \
  --target dbt-third-party \
  --build-arg dbt_third_party='dbt-sqlserver==1.4.3' \
  --build-arg dbt_core_ref='dbt-core@v1.4.6' \
  .
```
2. Create a skeleton `profiles.yml`:
```
dev:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      trust_cert: true
      server: localhost
      port: 1433
      database: MyDB
      user: sa
      password: secret
      schema: dbo
```
3. Create a skeleton `dbt_project.yml`:
```
name: "reporting"
config-version: 2
version: "0.1"

profile: dev
```
4. Run a `dbt ls` through the image created:
```
docker run \
--mount type=bind,source=.,target=/usr/app \
--mount type=bind,source=./profiles.yml,target=/root/.dbt/profiles.yml \
dbt-sqlserver:1.4.3 \
ls
```

### Relevant log output

```shell
20:48:35  Encountered an error:
libodbc.so.2: cannot open shared object file: No such file or directory
20:48:35  Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/main.py", line 233, in run_from_args
    task = parsed.cls.from_args(args=parsed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/task/base.py", line 163, in from_args
    return super().from_args(args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/task/base.py", line 98, in from_args
    config = cls.ConfigType.from_args(args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/runtime.py", line 263, in from_args
    project, profile = cls.collect_parts(args)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/runtime.py", line 207, in collect_parts
    profile = cls.collect_profile(args=args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/runtime.py", line 229, in collect_profile
    profile = cls._get_rendered_profile(args, profile_renderer, profile_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/runtime.py", line 200, in _get_rendered_profile
    return Profile.render_from_args(args, profile_renderer, profile_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/profile.py", line 428, in render_from_args
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/profile.py", line 394, in from_raw_profiles
    return cls.from_raw_profile_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/profile.py", line 348, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/config/profile.py", line 181, in _credentials_from_profile
    cls = load_plugin(typename)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/adapters/factory.py", line 202, in load_plugin
    return FACTORY.load_plugin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbt/adapters/factory.py", line 57, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/dbt/adapters/sqlserver/__init__.py", line 3, in <module>
    from dbt.adapters.sqlserver.sql_server_adapter import SQLServerAdapter
  File "/usr/local/lib/python3.11/site-packages/dbt/adapters/sqlserver/sql_server_adapter.py", line 13, in <module>
    from dbt.adapters.sqlserver.sql_server_connection_manager import SQLServerConnectionManager
  File "/usr/local/lib/python3.11/site-packages/dbt/adapters/sqlserver/sql_server_connection_manager.py", line 10, in <module>
    import pyodbc
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
```

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Python: 3.11.2
- dbt: 1.4.6

Docker image python:3.11.2-slim-bullseye
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Seems like adding `apt-get update && apt-get install -y --no-install-recommends libodbc1` gets things to work (i.e. `dbt ls` executes properly) but to be a useful image it will need the MS ODBC drivers (i.e. `msodbcsql18`) as well. Without that package, this is the next error that would be encountered when trying to do anything to the database:

```
21:14:59  Running with dbt=1.4.6
21:14:59  Unable to do partial parsing because env vars used in profiles.yml have changed
21:15:01  Found 31 models, 104 tests, 0 snapshots, 6 analyses, 437 macros, 0 operations, 0 seed files, 13 sources, 0 exposures, 0 metrics
21:15:01
21:15:01
21:15:01  Finished running  in 0 hours 0 minutes and 0.04 seconds (0.04s).
21:15:01  Encountered an error:
Database Error
  ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 18 for SQL Server' : file not found (0) (SQLDriverConnect)")
  ```

My proposal would be to create a specific `dbt-sqlserver` target and add whatever additional packages are required to it, similar to how `dbt-spark` is built. If this is acceptable/desirable, I can contribute code for this.

**Comment by dbeatty10** [comment]
Thanks for reaching out @raginjason !

Maintaining adapter-specific requirements like `libodbc1` and `msodbcsql18` is out of the scope within dbt-core, so I'm going to close this issue as "not planned".

There's a couple alternative paths you could take instead:
1. Open a similar issue to this one at https://github.com/dbt-msft/dbt-sqlserver
2. Create your own Docker image

Seems worthwhile to at least try the first one and use the second one as a workaround as-needed.

**Comment by raginjason** [comment]
@dbeatty10 I understand the concern and can see how it may not fit in the purview of dbt, but aren't there adapter-specific requirements for `dbt-spark`? Or is the issue that `dbt-sqlserver` is not part of the core project?
