### ISSUE TITLE
[CT-3029] [Bug] dbt docs generate gives an error with gitlab runner

### ISSUE THREAD

**Issue by wlphung** [dbt-labs/dbt-core#8491]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We recently upgraded to dbt 1.5.4 from dbt 0.18.1. We have a gitlab job that runs after each PR is merged, it copies all content in our repo and pastes to an external dbt docs website (This is the same website that appears when you run `dbt docs serve`, except instead of having to run it on terminal, the website is available to anyone without having to run the command.) 

Our gitlab job has been failing ever since we upgraded to dbtv1.5.4. Our DevOps teams believes there is a bug with dbt-bigquery adapter. The dbt commands fail on gitlab, but when I run the same commands locally on terminal, it passes. I am not sure what's going on. 

The dbt commands are: 
`dbt deps` - passes 
`dbt docs generate` - fails 

### Expected Behavior

I expect the dbt commands to work under Gitlab runner, which copies all warehouse repo content to our self-hosted external dbt docs website. 

### Steps To Reproduce

This is the gitlab job: 

```
pages:
  stage: deploy
  needs: []  # GitLab will generate/deploy dbt docs regardless of other steps in the pipeline.
  only:
    - master

  image: python:3.7

  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"

  script:
    - git fetch
    - git checkout master
    - pip install 'dbt-bigquery==1.5.4' markupsafe==2.0.1 envsubst
    - mkdir ~/.dbt
    - envsubst < $DBT_PROFILE > ~/.dbt/profiles.yml
    - cat $BIGQUERY_SVCACCOUNT > ~/.dbt/bigquery.json
    - cd dbt/analytics
    - 'dbt deps'
    - 'dbt docs generate'
    - mv target ${CI_PROJECT_DIR}/public

  artifacts:
    paths:
      - public
```

### Relevant log output

```shell
Running with gitlab-runner 16.2.0 (782e15da)
  on gitlab-gitlab-runner-ddf6976b4-k6h26 z13QxA6P, system ID: r_MnL3g8OeQI8K
Resolving secrets
00:00
Preparing the "kubernetes" executor
00:00
Using Kubernetes namespace: default
Using Kubernetes executor with image python:3.7 ...
Using attach strategy to execute scripts...
Preparing environment
00:13
Waiting for pod default/runner-z13qxa6p-project-148-concurrent-0-909oktsv to be running, status is Pending
Waiting for pod default/runner-z13qxa6p-project-148-concurrent-0-909oktsv to be running, status is Pending
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
Waiting for pod default/runner-z13qxa6p-project-148-concurrent-0-909oktsv to be running, status is Pending
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
Waiting for pod default/runner-z13qxa6p-project-148-concurrent-0-909oktsv to be running, status is Pending
	ContainersNotReady: "containers with unready status: [build helper]"
	ContainersNotReady: "containers with unready status: [build helper]"
Running on runner-z13qxa6p-project-148-concurrent-0-909oktsv via gitlab-gitlab-runner-ddf6976b4-k6h26...
Getting source from Git repository
00:02
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/wellframe/data-science/warehouse/.git/
Created fresh repository.
Skipping Git checkout
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:37
$ git fetch
$ git checkout master
Switched to a new branch 'master'
branch 'master' set up to track 'origin/master'.
$ pip install 'dbt-bigquery==1.5.4' markupsafe==2.0.1 envsubst
Collecting dbt-bigquery==1.5.4
  Downloading dbt_bigquery-1.5.4-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 kB 2.1 MB/s eta 0:00:00
Collecting markupsafe==2.0.1
  Downloading MarkupSafe-2.0.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (31 kB)
Collecting envsubst
  Downloading envsubst-0.1.5-py2.py3-none-any.whl (4.0 kB)
Collecting google-cloud-dataproc~=5.0
  Downloading google_cloud_dataproc-5.4.3-py2.py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.5/307.5 kB 10.5 MB/s eta 0:00:00
Collecting agate~=1.6.3
  Downloading agate-1.6.3-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.5/100.5 kB 15.8 MB/s eta 0:00:00
Collecting dbt-core~=1.5.0
  Downloading dbt_core-1.5.6-py3-none-any.whl (950 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 950.8/950.8 kB 35.2 MB/s eta 0:00:00
Collecting google-cloud-bigquery~=3.0
  Downloading google_cloud_bigquery-3.11.4-py2.py3-none-any.whl (219 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.6/219.6 kB 27.1 MB/s eta 0:00:00
Collecting google-cloud-storage~=2.4
  Downloading google_cloud_storage-2.10.0-py2.py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 kB 16.7 MB/s eta 0:00:00
Collecting parsedatetime!=2.5,!=2.6,>=2.1
  Downloading parsedatetime-2.4.tar.gz (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting isodate>=0.5.4
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 6.1 MB/s eta 0:00:00
Collecting six>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting leather>=0.3.2
  Downloading leather-0.3.4-py2.py3-none-any.whl (31 kB)
Collecting Babel>=2.0
  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 75.3 MB/s eta 0:00:00
Collecting pytimeparse>=1.1.5
  Downloading pytimeparse-1.1.8-py2.py3-none-any.whl (10.0 kB)
Collecting python-slugify>=1.2.1
  Downloading python_slugify-8.0.1-py2.py3-none-any.whl (9.7 kB)
Collecting networkx<2.8.1,>=2.3
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 65.1 MB/s eta 0:00:00
Collecting packaging>20.9
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 8.1 MB/s eta 0:00:00
Collecting pyyaml>=6.0
  Downloading PyYAML-6.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (670 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.1/670.1 kB 47.0 MB/s eta 0:00:00
Collecting cffi<2.0.0,>=1.9
  Downloading cffi-1.15.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.9/427.9 kB 39.3 MB/s eta 0:00:00
Collecting Jinja2==3.1.2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 20.2 MB/s eta 0:00:00
Collecting werkzeug<3,>=1
  Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 30.5 MB/s eta 0:00:00
Collecting hologram<=0.0.16,>=0.0.14
  Downloading hologram-0.0.16-py3-none-any.whl (11 kB)
Collecting dbt-extractor~=0.4.1
  Downloading dbt_extractor-0.4.1-cp36-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 57.2 MB/s eta 0:00:00
Collecting logbook<1.6,>=1.5
  Downloading Logbook-1.5.3.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 kB 13.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting click<9
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 15.6 MB/s eta 0:00:00
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting sqlparse<0.5,>=0.2.3
  Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 5.5 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 9.9 MB/s eta 0:00:00
Collecting minimal-snowplow-tracker==0.0.2
  Downloading minimal-snowplow-tracker-0.0.2.tar.gz (12 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting mashumaro[msgpack]==3.6
  Downloading mashumaro-3.6-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 10.5 MB/s eta 0:00:00
Collecting pathspec<0.12,>=0.9
  Downloading pathspec-0.11.2-py3-none-any.whl (29 kB)
Collecting colorama<0.4.7,>=0.3.9
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pytz>=2015.7
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 38.9 MB/s eta 0:00:00
Collecting protobuf>=4.0.0
  Downloading protobuf-4.24.1-cp37-abi3-manylinux2014_x86_64.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.4/311.4 kB 32.8 MB/s eta 0:00:00
Collecting requests<3.0.0
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 7.6 MB/s eta 0:00:00
Collecting msgpack>=0.5.6
  Downloading msgpack-1.0.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.7/299.7 kB 27.5 MB/s eta 0:00:00
Collecting proto-plus<2.0.0dev,>=1.15.0
  Downloading proto_plus-1.22.3-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.1/48.1 kB 7.8 MB/s eta 0:00:00
Collecting google-resumable-media<3.0dev,>=0.6.0
  Downloading google_resumable_media-2.5.0-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.7/77.7 kB 12.5 MB/s eta 0:00:00
Collecting python-dateutil<3.0dev,>=2.7.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 29.2 MB/s eta 0:00:00
Collecting google-cloud-core<3.0.0dev,>=1.6.0
  Downloading google_cloud_core-2.3.3-py2.py3-none-any.whl (29 kB)
Collecting grpcio<2.0dev,>=1.47.0
  Downloading grpcio-1.57.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 73.1 MB/s eta 0:00:00
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.11.1-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.5/120.5 kB 18.0 MB/s eta 0:00:00
Collecting grpc-google-iam-v1<1.0.0dev,>=0.12.4
  Downloading grpc_google_iam_v1-0.12.6-py2.py3-none-any.whl (26 kB)
Collecting google-auth<3.0dev,>=1.25.0
  Downloading google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.8/181.8 kB 24.8 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 18.6 MB/s eta 0:00:00
Collecting importlib-metadata
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2
  Downloading googleapis_common_protos-1.60.0-py2.py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 26.0 MB/s eta 0:00:00
Collecting grpcio-status<2.0.dev0,>=1.33.2
  Downloading grpcio_status-1.57.0-py3-none-any.whl (5.1 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 24.6 MB/s eta 0:00:00
Collecting urllib3<2.0
  Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 21.3 MB/s eta 0:00:00
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.5.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32 kB)
Collecting jsonschema>=3.0
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 16.0 MB/s eta 0:00:00
Collecting future
  Downloading future-0.18.3.tar.gz (840 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 50.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting text-unidecode>=1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 kB 13.0 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.8/175.8 kB 27.2 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 19.3 MB/s eta 0:00:00
Collecting werkzeug<3,>=1
  Downloading Werkzeug-2.2.2-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.7/232.7 kB 27.3 MB/s eta 0:00:00
  Downloading Werkzeug-2.2.1-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.4/232.4 kB 29.0 MB/s eta 0:00:00
  Downloading Werkzeug-2.2.0-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.2/232.2 kB 30.5 MB/s eta 0:00:00
  Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 27.0 MB/s eta 0:00:00
Collecting pkgutil-resolve-name>=1.3.10
  Downloading pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 9.6 MB/s eta 0:00:00
Collecting importlib-resources>=1.4.0
  Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting attrs>=17.4.0
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 8.5 MB/s eta 0:00:00
Collecting pyasn1<0.6.0,>=0.4.6
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 13.4 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: minimal-snowplow-tracker, logbook, parsedatetime, future
  Building wheel for minimal-snowplow-tracker (setup.py): started
  Building wheel for minimal-snowplow-tracker (setup.py): finished with status 'done'
  Created wheel for minimal-snowplow-tracker: filename=minimal_snowplow_tracker-0.0.2-py3-none-any.whl size=17814 sha256=cf08d422db414731ee3b5d18104d50d2210fcfe35423c8ffd305cf6e6139723a
  Stored in directory: /root/.cache/pip/wheels/9d/ee/55/8faefee41ca3bccb25152e0159002567575047be7ef1ce8ac1
  Building wheel for logbook (setup.py): started
  Building wheel for logbook (setup.py): finished with status 'done'
  Created wheel for logbook: filename=Logbook-1.5.3-cp37-cp37m-linux_x86_64.whl size=66391 sha256=2ffe5735dc273a989b781debd732f44364a26cde57a92ac12bd06a35b971375a
  Stored in directory: /root/.cache/pip/wheels/95/4b/a3/fc9b9d17a06a956767a8dc74058ba64d4306653df2289094cc
  Building wheel for parsedatetime (setup.py): started
  Building wheel for parsedatetime (setup.py): finished with status 'done'
  Created wheel for parsedatetime: filename=parsedatetime-2.4-py3-none-any.whl size=42774 sha256=59a6cbad9ced236cc3bc744b9815cd8f1125a5d8d95bf208e2e8680ae76438cb
  Stored in directory: /root/.cache/pip/wheels/68/0f/b7/539a31a4068565a53913d7f8cfc6c7521cca2ea091b8a72048
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492035 sha256=f22cf67f531f45da006b7fd12f50ad97df1f9d20e9d2a457e5f16ae64506a4b9
  Stored in directory: /root/.cache/pip/wheels/fa/cd/1f/c6b7b50b564983bf3011e8fc75d06047ddc50c07f6e3660b00
Successfully built minimal-snowplow-tracker logbook parsedatetime future
Installing collected packages: text-unidecode, pytz, pytimeparse, msgpack, logbook, envsubst, zipp, werkzeug, urllib3, typing-extensions, sqlparse, six, pyyaml, python-slugify, pyrsistent, pycparser, pyasn1, protobuf, pkgutil-resolve-name, pathspec, packaging, networkx, markupsafe, idna, grpcio, google-crc32c, future, dbt-extractor, colorama, charset-normalizer, certifi, cachetools, Babel, rsa, requests, python-dateutil, pyasn1-modules, proto-plus, parsedatetime, mashumaro, leather, Jinja2, isodate, importlib-resources, importlib-metadata, googleapis-common-protos, google-resumable-media, cffi, minimal-snowplow-tracker, grpcio-status, google-auth, click, attrs, agate, jsonschema, grpc-google-iam-v1, google-api-core, hologram, google-cloud-core, google-cloud-storage, google-cloud-dataproc, google-cloud-bigquery, dbt-core, dbt-bigquery
Successfully installed Babel-2.12.1 Jinja2-3.1.2 agate-1.6.3 attrs-23.1.0 cachetools-5.3.1 certifi-2023.7.22 cffi-1.15.1 charset-normalizer-3.2.0 click-8.1.7 colorama-0.4.6 dbt-bigquery-1.5.4 dbt-core-1.5.6 dbt-extractor-0.4.1 envsubst-0.1.5 future-0.18.3 google-api-core-2.11.1 google-auth-2.22.0 google-cloud-bigquery-3.11.4 google-cloud-core-2.3.3 google-cloud-dataproc-5.4.3 google-cloud-storage-2.10.0 google-crc32c-1.5.0 google-resumable-media-2.5.0 googleapis-common-protos-1.60.0 grpc-google-iam-v1-0.12.6 grpcio-1.57.0 grpcio-status-1.57.0 hologram-0.0.16 idna-3.4 importlib-metadata-6.7.0 importlib-resources-5.12.0 isodate-0.6.1 jsonschema-4.17.3 leather-0.3.4 logbook-1.5.3 markupsafe-2.0.1 mashumaro-3.6 minimal-snowplow-tracker-0.0.2 msgpack-1.0.5 networkx-2.6.3 packaging-23.1 parsedatetime-2.4 pathspec-0.11.2 pkgutil-resolve-name-1.3.10 proto-plus-1.22.3 protobuf-4.24.1 pyasn1-0.5.0 pyasn1-modules-0.3.0 pycparser-2.21 pyrsistent-0.19.3 python-dateutil-2.8.2 python-slugify-8.0.1 pytimeparse-1.1.8 pytz-2023.3 pyyaml-6.0.1 requests-2.31.0 rsa-4.9 six-1.16.0 sqlparse-0.4.4 text-unidecode-1.3 typing-extensions-4.7.1 urllib3-1.26.16 werkzeug-2.1.2 zipp-3.15.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
$ mkdir ~/.dbt
$ envsubst < $DBT_PROFILE > ~/.dbt/profiles.yml
$ cat $BIGQUERY_SVCACCOUNT > ~/.dbt/bigquery.json
$ cd dbt/analytics
$ dbt deps
19:31:18  Running with dbt=1.5.6
19:31:19  Installing dbt-labs/dbt_utils
19:31:19  Installed from version 1.1.1
19:31:19  Up to date!
$ dbt docs generate
19:31:22  Running with dbt=1.5.6
19:31:23  Encountered an error:
invalid syntax (column.py, line 230)
19:31:23  Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper
    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)
  File "/usr/local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile
    profile_renderer, profile_name, profile_name_override, target_override, threads_override
  File "/usr/local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render
    threads_override=threads_override,
  File "/usr/local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles
    threads_override=threads_override,
  File "/usr/local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info
    profile_data, profile_name, target_name
  File "/usr/local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile
    cls = load_plugin(typename)
  File "/usr/local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin
    return FACTORY.load_plugin(name)
  File "/usr/local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>
    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa
  File "/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230
    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):
                                         ^
SyntaxError: invalid syntax
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1
```

### Environment

```markdown
- OS: MacOS Monterey 12.5.1
- Python: 3.7
- dbt:1.5.4
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

This is the gitlab job: 

![Screen Shot 2023-08-24 at 4 24 37 PM](https://github.com/dbt-labs/dbt-core/assets/143131748/0aa969cf-29a1-4f6b-a2f6-a09b476e6c55)

**Comment by graciegoheen** [comment]
Hi! Thanks for opening. I'm inclined to move this over to the dbt-bigquery repo, since the relevant line of code that's triggering this error is [here](https://github.com/dbt-labs/dbt-bigquery/blob/d7fb235a42780841c82ea5b01a647b3416070afe/dbt/adapters/bigquery/column.py#L230). Is there any reason you think this would instead be a dbt-core bug?

That being said, I think I know what's going on here. It looks like your gitlab runner is using python version `3.7`. In [this PR,](https://github.com/dbt-labs/dbt-bigquery/pull/742) dbt-bigquery dropped support for python 3.7 for both dbt-bigquery 1.4.* and 1.5.*, since it reached end of life on [2023-06-27](https://devguide.python.org/versions/). 

Can you try updating your gitlab runner to use python 3.8 or higher?

Additionally, I'm curious why you're using dbt-bigquery `1.5.4` versus `1.5.5` or `1.5.6` - we typically recommend you use the latest patch of whatever minor version you're on. [1.5.5,](https://github.com/dbt-labs/dbt-bigquery/releases/tag/v1.5.5) for example, flags the requirement for python 3.8 so I think you'd have gotten a clearer error message if you were using the latest of dbt-bigquery `1.5`.

**Comment by graciegoheen** [comment]
I also opened a [docs issue](https://github.com/dbt-labs/docs.getdbt.com/issues/3978) to make python compatibility clearer for earlier versions of dbt-core / dbt adapters :)

**Comment by wlphung** [comment]
Thank you so much for the quick reply!! I thought this was a dbt-core bug because the docs website said dbt-core was compatible with Python 3.7 https://docs.getdbt.com/faqs/core/install-python-compatibility but realize now I should've been looking at dbt-bigquery docs instead. I will update to Python 3.8 and try again. 

We just upgraded to dbtv1.5.4 recently, but will make an update to the latest patch in the next few weeks. 

Thanks for all your help here! I will report back if that fixes the issue

**Comment by wlphung** [comment]
Confirming updating to python 3.8 fixed the issue! Thank you!
