### ISSUE TITLE
[CT-3107] [Bug] nested dependencies not installed when package is a tarball

### ISSUE THREAD

**Issue by adamlopez** [dbt-labs/dbt-core#8621]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

when running `dbt deps` to install a package specified as a tarball, dbt doesn't install nested dependencies (i.e. packages specified in the imported package's `packages.yml` file) as it does when installing a package from local, git or the dbt hub.

### Expected Behavior

consistent behaviour across import methods regarding nested dependencies. dbt should install any dependencies specified in the tarball project's packages.yml file.

### Steps To Reproduce

this can be reproduced by importing the tarball of a package with nested dependencies. In this case, importing dbt_expectations should cause dbt_date to be installed, as its included in the package's dependencies here: https://github.com/calogica/dbt-expectations/blob/0.9.0/packages.yml

Steps:
1. create a `packages.yml` file in a project with the following structure:
``` yaml
packages:
  - tarball: "https://github.com/calogica/dbt-expectations/archive/refs/tags/0.9.0.tar.gz"
    name: "dbt_expectations"
```
2. run `dbt deps`

running dbt deps will only install dbt_expectations:
```
20:08:55  Running with dbt=1.5.6
20:08:55  Installing dbt_expectations
20:08:56  Installed from tarball (url: https://github.com/calogica/dbt-expectations/archive/refs/tags/0.9.0.tar.gz)
```
compare this to installing the same package from dbt hub, with the following `packages.yml`:
``` yaml
packages:
  - package: calogica/dbt_expectations
    version: "0.9.0"
```
```
20:14:24  Running with dbt=1.5.6
20:14:24  Installing calogica/dbt_expectations
20:14:25  Installed from version 0.9.0
20:14:25  Up to date!
20:14:25  Installing calogica/dbt_date
20:14:25  Installed from version 0.8.1
20:14:25  Updated version available: 0.9.1
20:14:25  
20:14:25  Updates available for packages: ['calogica/dbt_date']                 
Update your versions in packages.yml, then run dbt deps
```

### Environment

```markdown
- OS: Mac OS 13.5.2 (22G91)
- Python: 3.9
- dbt: 1.5.6
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reporting this @adamlopez !

I was able to reproduce what you reported for the Tarball URL method and also confirmed that nested dependencies work for all other package installation methods.

See full reproducible example below. Note that all of them except for the Tarball URL method creates two directories:
```
dbt_date                dbt_expectations
```

<details>
<summary>

### Reprex
</summary>

```shell
mkdir -p reprex
cd reprex
cat << EOF > dbt_project.yml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle"

clean-targets:
  - target
  - dbt_packages
  - logs
EOF
```

```shell
cat << EOF > packages.yml
packages:
  # Hub package
  - package: calogica/dbt_expectations
    version: 0.9.0
EOF
dbt clean
dbt deps
echo ""
echo "After Hub package install:"
echo ""
ls dbt_packages
```

```shell
cat << EOF > packages.yml
packages:
  # Git package
  - git: "https://github.com/calogica/dbt-expectations.git"  # git HTTP URL
    revision: 0.9.0  # tag, branch name, or 40-character hash
EOF
dbt clean
dbt deps
echo ""
echo "After Git package install:"
echo ""
ls dbt_packages
```

```shell
cat << EOF > packages.yml
packages:
  # 'Private' package
  - git: "git@github.com:calogica/dbt-expectations.git"  # git SSH URL
    revision: 0.9.0  # tag, branch name, or 40-character hash
EOF
dbt clean
dbt deps
echo ""
echo "After 'Private' package install:"
echo ""
ls dbt_packages
```

```shell
git clone https://github.com/calogica/dbt-expectations.git
cat << EOF > packages.yml
packages:
  # Local package
  - local: dbt-expectations
EOF
dbt clean
dbt deps
echo ""
echo "After Local package install:"
echo ""
ls dbt_packages
```

```shell
cat << EOF > packages.yml
packages:
  # Tarball URL
  - tarball: https://codeload.github.com/calogica/dbt-expectations/tar.gz/0.9.0
    name: 'dbt_expectations'
EOF
dbt clean
dbt deps
echo ""
echo "After Tarball URL install:"
echo ""
ls dbt_packages
```

</details>

**Comment by adamlopez** [comment]
Thanks for confirming the issue @dbeatty10 - what's the usual process for fixing these types of issues? Should I just submit a PR with a fix? (i've looked through the contribution guidelines and submitted a CLA)

**Comment by dbeatty10** [comment]
That would be awesome if you'd be willing to open a PR with a fix @adamlopez 🤩 

Just put `resolves #8621` as the first line of the PR description, and it will automatically link your PR with this issue. All the other relevant details are in the ["Submitting a Pull Request"](https://github.com/dbt-labs/dbt-core/blob/8aaed0e29f9560bc53d9d3e88325a9597318e375/CONTRIBUTING.md#submitting-a-pull-request) of the contributing guide.

**Comment by dbeatty10** [comment]
@adamlopez I just added the `help_wanted` label which signals to the engineering team within dbt Labs that we're reserving this to be solved by a community contributor (you!) 😎

**Comment by Nyakutka** [comment]
Hello, I'm trying to set up environment in our offline(doesn't have access to dbt hub) gitlab ci. So, I use dbt deps with tarball located in our local registry(got from github repo and put to registry). When I run dbt deps with this packages.yml
```
packages:
  - tarball: https://<some_registry>/elementary-data/dbt-data-reliability/tags/0.16.1/dbt-data-reliability-0.16.1.tar.gz
    name: elementary
```
It goes to the hub and download dbt_utils from there
```
 dbt -d deps
13:48:38  Running with dbt=1.8.0
13:48:38  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'False', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'True', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'True', 'log_path': '/workspaces/ubuntu/core-dwh/dwh_tool/mart/logs', 'profiles_dir': '/workspaces/ubuntu/core-dwh/dwh_tool/mart', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt -d deps', 'send_anonymous_usage_stats': 'False'}
13:48:38  Set downloads directory='/tmp/dbt-downloads-pz_bop6r'
13:48:39  Making package index registry request: GET https://hub.getdbt.com/api/v1/index.json
13:48:39  Response from registry index: GET https://hub.getdbt.com/api/v1/index.json 200
13:48:39  Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json
13:48:39  Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json 200
13:48:39  Updating lock file in file path: /workspaces/ubuntu/core-dwh/dwh_tool/mart/package-lock.yml
13:48:40  Set downloads directory='/tmp/dbt-downloads-z72saon9'
13:48:40  Installing elementary
13:48:40  Installed from tarball (url: https://<some_registry>/elementary-data/dbt-data-reliability/tags/0.16.1/dbt-data-reliability-0.16.1.tar.gz)
13:48:40  Installing dbt-labs/dbt_utils
13:48:40  Installed from version 1.3.1
13:48:40  Up to date!
13:48:40  Resource report: {"command_name": "deps", "command_success": true, "command_wall_clock_time": 2.4485245, "process_user_time": 2.041846, "process_kernel_time": 0.174429, "process_mem_max_rss": "90848", "process_in_blocks": "64424", "process_out_blocks": "23592"}
13:48:40  Command `dbt deps` succeeded at 13:48:40.967373 after 2.45 seconds
13:48:40  Flushing usage events
```

When I specify dbt_utils with tarball I get an error:
```
packages:
  - tarball: https://<some_registry>/dbt-labs/dbt-utils/tags/1.3.1/dbt-utils-1.3.1.tar.gz
    name: dbt_utils
  - tarball: https://<some_registry>/elementary-data/dbt-data-reliability/tags/0.16.1/dbt-data-reliability-0.16.1.tar.gz
    name: elementary
```
```
dbt -d deps
13:51:26  Running with dbt=1.8.0
13:51:26  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'False', 'partial_parse': 'True', 'cache_selected_only': 'True', 'profiles_dir': '/workspaces/ubuntu/core-dwh/dwh_tool/mart', 'fail_fast': 'False', 'debug': 'True', 'log_path': '/workspaces/ubuntu/core-dwh/dwh_tool/mart/logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt -d deps', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'False'}
13:51:26  Set downloads directory='/tmp/dbt-downloads-h29jhwq5'
13:51:26  Making package index registry request: GET https://hub.getdbt.com/api/v1/index.json
13:51:27  Response from registry index: GET https://hub.getdbt.com/api/v1/index.json 200
13:51:27  Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json
13:51:27  Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json 200
13:51:27  Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
13:51:27  Traceback (most recent call last):
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 201, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 247, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/cli/main.py", line 446, in deps
    results = task.run()
              ^^^^^^^^^^
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/task/deps.py", line 225, in run
    self.lock()
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/task/deps.py", line 194, in lock
    resolved_deps = resolve_packages(packages, self.project, self.cli_vars)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/deps/resolver.py", line 133, in resolve_packages
    _check_for_duplicate_project_names(resolved, project, renderer)
  File "/workspaces/ubuntu/core-dwh/.venv/lib/python3.11/site-packages/dbt/deps/resolver.py", line 107, in _check_for_duplicate_project_names
    raise DuplicateProjectDependencyError(project_name)
dbt.exceptions.DuplicateProjectDependencyError: Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.

13:51:27  Resource report: {"command_name": "deps", "command_wall_clock_time": 1.8638473, "process_user_time": 2.216992, "process_kernel_time": 0.23498, "process_mem_max_rss": "90648", "process_in_blocks": "61672", "process_out_blocks": "13192", "command_success": false}
13:51:27  Command `dbt deps` failed at 13:51:27.753549 after 1.87 seconds
13:51:27  Flushing usage events
```
How can I use dbt deps with 'offline' environment?
