### ISSUE TITLE
[CT-3119] Getting typeError when trying to run any dbt command with python 3.10 and python 3.11 on dbt-teradata 1.6

### ISSUE THREAD

**Issue by VarunSharma15** [dbt-labs/dbt-core#8640]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I work for teradata, and we were upgrading adapter for v1.6.2
Python installed was 3.10
We are using dbt 1.6.x
Then we tried to run some testcases where we are facing the following error
```
============================================================= short test summary info ============================================================= 
ERROR tests/functional/adapter/constraints/test_constraints.py::
TestIncrementalConstraintsRollback::test__constraints_enforcement_rollback -
TypeError: TeradataCredentials.__init__() takes 1 positional argument but 2 were given
================================================================ 1 error in 12.09s ================================================================ 
```

We tried with sample project also and all dbt commands are failing.
Things are working as expected until v1.5 .
We have not done any changes in any other file. Since there isn't any changes from teradata adapter side, we were thinking if there were some changes on dbt-core level that made this happen. 

We tried it with other python version for example 3.9 at things work fine.
Whereas if we upgrade the python version to 3.11, the same issue occurs.
dbt-teradata 1.5 also had python 3.10 and 3.11 support and everything was working as expected.

### Expected Behavior

All dbt commands should work fine on a sample project and testcases should work fine.

### Steps To Reproduce

1. Clone dbt-teradata
2. Create a python virtual environment (python -m venv env_name)
3. Activate the environment (env_name/scripts/activate)
4. Make changes in setup file at line 48 (with dbt-core==1.6.2)
5. Make changes in requirements_dev.txt ( dbt-core==1.6.2 and dbt-tests-adapter~=1.6.2)
6. install the requirements (pip install -r requirements_dev.txt)
7. Make changes in conftest.py for sever_name, username and password.
8. Try to run some testcase

### Relevant log output

```shell
PS C:\dbt-teradata> python -m pytest .\tests\functional\adapter\constraints\test_constraints.py
=============================================================== test session starts ===============================================================
platform win32 -- Python 3.10.2, pytest-7.2.0, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: C:\dbt-teradata, configfile: pytest.ini
plugins: anyio-3.6.2, pylava-0.3.0, asyncio-0.21.0, benchmark-4.0.0, cov-4.0.0, dotenv-0.5.2, integration-0.2.3, mock-3.10.0, recording-0.12.2      
asyncio: mode=strict
collected 1 item

tests\functional\adapter\constraints\test_constraints.py E                                                                                   [100%]

===================================================================== ERRORS ====================================================================== 
___________________________ ERROR at setup of TestIncrementalConstraintsRollback.test__constraints_enforcement_rollback ___________________________ 

unique_schema = 'dbt_test_16945678340101648523'
project_root = local('C:\\Users\\mt255026\\AppData\\Local\\Temp\\pytest-of-mt255026\\pytest-1\\project0')
profiles_root = local('C:\\Users\\mt255026\\AppData\\Local\\Temp\\pytest-of-mt255026\\pytest-1\\profile0')
profiles_yml = {'config': {'send_anonymous_usage_stats': False}, 'test': {'outputs': {'default': {'host': 'sdt47039.labs.teradata.com', 'log': '0', 
'password': 'mt255026', 'schema': 'dbt_test_16945678340101648523', ...}}, 'target': 'default'}}
dbt_project_yml = {'name': 'test', 'profile': 'test'}, clean_up_logging = None

    @pytest.fixture(scope="class")
    def adapter(
        unique_schema, project_root, profiles_root, profiles_yml, dbt_project_yml, clean_up_logging
    ):
        # The profiles.yml and dbt_project.yml should already be written out
        args = Namespace(
            profiles_dir=str(profiles_root),
            project_dir=str(project_root),
            target=None,
            profile=None,
            threads=None,
        )
        flags.set_from_args(args, {})
>       runtime_config = RuntimeConfig.from_args(args)

C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\tests\fixtures\project.py:279:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\runtime.py:269: in from_args
    project, profile = cls.collect_parts(args)
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\runtime.py:248: in collect_parts
    profile = cls.get_profile(
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\runtime.py:106: in get_profile
    return load_profile(
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\runtime.py:70: in load_profile
    profile = Profile.render(
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py:436: in render
    return cls.from_raw_profiles(
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py:401: in from_raw_profiles
    return cls.from_raw_profile_info(
C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py:355: in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

profile = {'host': 'sdt47039.labs.teradata.com', 'log': '0', 'password': 'mt255026', 'schema': 'dbt_test_16945678340101648523', ...}
profile_name = 'test', target_name = 'default'

    @staticmethod
    def _credentials_from_profile(
        profile: Dict[str, Any], profile_name: str, target_name: str
    ) -> Credentials:
        # avoid an import cycle
        from dbt.adapters.factory import load_plugin

        # credentials carry their 'type' in their actual type, not their
        # attributes. We do want this in order to pick our Credentials class.
        if "type" not in profile:
            raise DbtProfileError(
                'required field "type" not found in profile {} and target {}'.format(
                    profile_name, target_name
                )
            )

        typename = profile.pop("type")
        try:
            cls = load_plugin(typename)
            data = cls.translate_aliases(profile)
            cls.validate(data)
>           credentials = cls.from_dict(data)
E           TypeError: TeradataCredentials.__init__() takes 1 positional argument but 2 were given

C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py:168: TypeError
-------------------------------------------------------------- Captured stdout setup -------------------------------------------------------------- 

=== Test project_root: C:\Users\mt255026\AppData\Local\Temp\pytest-of-mt255026\pytest-1\project0
============================================================= short test summary info ============================================================= 
ERROR tests/functional/adapter/constraints/test_constraints.py::TestIncrementalConstraintsRollback::test__constraints_enforcement_rollback - TypeError: TeradataCredentials.__init__() takes 1 positional argument but 2 were given
================================================================ 1 error in 12.09s ================================================================
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.10, 3.11
- dbt: 1.6.x
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Database adapter :  dbt-teradata 

Some more snippet from Jaffle-shop project

```sh
C:\dbt-teradata> dbt debug
01:23:24  Running with dbt=1.6.0
01:23:24  dbt version: 1.6.0
01:23:24  python version: 3.10.2
01:23:24  python path: C:\Users\mt255026\AppData\Local\Programs\Python\Python310\python.exe
01:23:24  os info: Windows-10-10.0.19045-SP0
01:23:24  Encountered an error:
TeradataCredentials.__init__() takes 1 positional argument but 2 were given
01:23:24  Traceback (most recent call last):
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\cli\requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\cli\requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\cli\main.py", line 425, in debug
    results = task.run()
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\task\debug.py", line 122, in run
    load_profile_status: SubtaskStatus = self._load_profile()
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\task\debug.py", line 210, in _load_profile
    profile: Profile = Profile.render(
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py", line 436, in render
    return cls.from_raw_profiles(
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py", line 401, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py", line 355, in from_raw_profile_info      
    credentials: Credentials = cls._credentials_from_profile(
  File "C:\Users\mt255026\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\config\profile.py", line 168, in _credentials_from_profile  
    credentials = cls.from_dict(data)
  File "<string>", line 185, in from_dict
TypeError: TeradataCredentials.__init__() takes 1 positional argument but 2 were given
```

**Comment by dataders** [comment]
hey @VarunSharma15, definitely an unexpected error to find, especially when it was working before.

I did some poking around and my guess is that it has to do with the method mentioned in the error message `TeradataCredentials.__init__()`. The issue isn't the positional arguments, rather that the method exists at all.

it is currently defined in [/dbt/adapters/teradata/connections.py#L51-L54](https://github.com/Teradata/dbt-teradata/blob/1261b1a8f7a2e904fc33c91c68a5bf8dac156a80/dbt/adapters/teradata/connections.py#L51-L54) and was introduced in https://github.com/Teradata/dbt-teradata/pull/10/

```py
def __init__(self, **kwargs):
  for k, v in kwargs.items():
    setattr(self, k, v)
    self.database = None
```

The PR's usecase seems certainly valid, but the implementation strikes me as:

1. **redundant** the `setattr` loop doesn't make sense bc Dataclasses do this for you
2. **sketchy** bc it's overriding the `Credentials` class which goes back to `dbtClassMixin` which I always try to avoid messing with for performance reasons

My advice would be to drop that method, and refactor `TeradataAdapter.verify_database()` ([/dbt/adapters/teradata/impl.py#L57-L68](https://github.com/Teradata/dbt-teradata/blob/1261b1a8f7a2e904fc33c91c68a5bf8dac156a80/dbt/adapters/teradata/impl.py#L57-L68)) to work differently. Let me know if you need help doing so.

**Comment by VarunSharma15** [comment]
Hi @dataders 

Thank you for the quick response.
Definitely I would go and try to make the changes suggested.
Meanwhile, me and my team have a question that.
Is there any change that came from dbt-core side which might have made this happen?
Because things were good before on all the python versions.

**Comment by dataders** [comment]
> is there any change that came from dbt-core side which might have made this happen ?

my answer is “probably?“. i could go looking if you’d like, but for a very long time serializing our Dataclasses in Python has long been a performance bottleneck that we’ve been chipping away at. Starting w/ using mashumaro, then maintaining our own version of it, to some strange combination.

my guess is there was some such change. I'll ask our engineers to find root cause, but I’m fairly confident that they'll suggest the same remediation ultimately. stay tuned.

i do want to underline again that it's less than ideal that you encounter this issue without warning

**Comment by VarunSharma15** [comment]
Thank you @dataders, if we get some information from dbt-core side that would be great.
We will also look and try to refactor our files.
We appreciate the help and support on this matter.

**Comment by dataders** [comment]
hey @VarunSharma15, if you don't mind, I'd prefer if we continue this discussion over at the just-created https://github.com/Teradata/dbt-teradata/issues/108. The reason being that there's not any action that can be taken by dbt-core at this point.
