### ISSUE TITLE
[CT-3188] [Bug] Referenc to a local repository not working

### ISSUE THREAD

**Issue by RalfKow** [dbt-labs/dbt-core#8786]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am having a monorepository which contains an etl pipeline that extends over multiple databases.

**System**
(Third party source) --> Input data product --> Foundation Data product --> Insight data product

I looked into [Should I have an organisation wide project (a monorepo) or should each work flow have their own? - In-Depth Discussions - dbt Community Forum (getdbt.com)](https://discourse.getdbt.com/t/should-i-have-an-organisation-wide-project-a-monorepo-or-should-each-work-flow-have-their-own/666/2) and there where the repos

[dbt Labs · GitHub](https://github.com/dbt-labs)
[GitHub - dbt-labs/snowplow: Data models for snowplow analytics.](https://github.com/dbt-labs/snowplow)

suggested.

If I set up a project accordingly 

project
- dbt
- - project_1
- - - dbt_project.yaml
- - project_2
- - - dbt_project.yaml
- dbt_project.yaml
- packages.yaml

```yaml
packages:
    # https://github.com/dbt-labs/dbt-utils
  - local: dbt/project_1
  - local: dbt/project_2
```

I get the error
λ poetry run dbt deps
07:56:41  Running with dbt=1.5.1
07:56:41  Installing dbt/project_1
07:56:41  Encountered an error:
[WinError 1314] A required privilege is not held by the client: 'C:\\devsbb\\code\\Test_multirepo\\dbt\\project_1' -> 'dbt_packages\\project_1'
07:56:41  Traceback (most recent call last):
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\cli\requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\cli\requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\cli\requires.py", line 125, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\cli\requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\cli\main.py", line 435, in deps
    results = task.run()
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\task\deps.py", line 81, in run
    package.install(self.project, renderer)
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\deps\local.py", line 64, in install
    system.make_symlink(src_path, dest_path)
  File "C:\Users\u231888\AppData\Local\pypoetry\Cache\virtualenvs\test-multirepo-6Va2XRNg-py3.8\lib\site-packages\dbt\clients\system.py", line 158, in make_symlink
    os.symlink(source, link_path)
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\devsbb\\code\\Test_multirepo\\dbt\\project_1' -> 'dbt_packages\\project_1'

I also found an old post https://github.com/dbt-labs/dbt-core/issues/766

### Expected Behavior

Flawless integration of other dbt_projects in form of packages

My main goal is to maintain multiple dbt_projects in one repo. The problems I challenge are
- How do I provide one doc
- How do I execute pre commit hooks 
- How do I make these dbt_projects accessable in the docker image

### Steps To Reproduce

1. Create a new repository with multiple dbt_projects in poetry 
2. Rund poetry run dbt deps

### Environment

```markdown
- OS:Windows 
- Python:3.8.13
- dbt:1.5.1
```

### Which database adapter are you using with dbt?

postgres, snowflake

**Comment by RalfKow** [comment]
Sorry it was solved with an update to 1.6.4
