### ISSUE TITLE
[CT-3250] [Bug] dbt run --vars  raise a ValueError: unconverted data remains:  07:00

### ISSUE THREAD

**Issue by pengyusong** [dbt-labs/dbt-core#8883]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I want input a string var in dbt run command. but dbt-core will parse the input as datatime, how to avoid this?
dbt run command
`dbt run -s bug--vars "{start_hour: '2023-08-01 01', end_hour: '2023-08-01 07'}"`
the var function use as follows:
`var("end_hour")`

### Expected Behavior

expect result should be run success. but if raise an error:
`unconverted data remains:  07:00
03:22:57  Traceback (most recent call last):
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\cli\requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\cli\requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\cli\requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\cli\requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\cli\requires.py", line 215, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\cli\requires.py", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\manifest.py", line 227, in get_full_manifest
    manifest = loader.load()
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\manifest.py", line 386, in load
    self.parse_project(
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\manifest.py", line 515, in parse_project
    parser.parse_file(block)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\base.py", line 433, in parse_file
    self.parse_node(file_block)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\base.py", line 394, in parse_node
    self.render_update(node, config)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\models.py", line 358, in render_update
    super().render_update(node, config)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\base.py", line 370, in render_update
    context = self.render_with_context(node, config)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\parser\base.py", line 240, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\clients\jinja.py", line 591, in get_rendered
    return render_template(template, ctx, node)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\clients\jinja.py", line 546, in render_template
    return template.render(ctx)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 44, in top-level template code
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\clients\jinja.py", line 330, in __call__
    return self.call_macro(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\clients\jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 9, in template
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\pengyus\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  07:00`

### Steps To Reproduce

1. run any model with a var function for accept a param.

### Environment

```markdown
- OS: Windows 10
- Python: 3.7
- dbt: 1.5
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
@pengyusong Could you give a more detailed example of how you are using the [`var`](https://docs.getdbt.com/reference/dbt-jinja-functions/var) function?

If you can provide a simple but complete example, that will help us try to reproduce what you are describing.

Something like this:

1\. Create this model

`models/bug.sql`

```sql
select {{ var("end_hour") }}::timestamp as my_end_hour
```

2\. Then run this command:
```shell
dbt run -s bug --vars "{start_hour: '2023-08-01 01', end_hour: '2023-08-01 07'}"
```

**Comment by pengyusong** [comment]
model as bellows:
`{{ config(
    materialized='table',
    unique_key=['id'],
    on_schema_change = 'append_new_columns'
    )
}}

select 
  bug.id,
  bug.area,
  bug.name
from 
  {{ source('uniods', 'ods_taas_bug') }} bug 
where 
  bug."record_update_time" < TIMESTAMPTZ '{{ vars_end_hour() }}'
  and bug."record_update_time">= TIMESTAMPTZ '{{ vars_end_hour() }}'`

macrocs as bellows:
`{% macro vars_end_hour() %}
  {% set tmp = var("end_hour") | as_text %}
  {% if modules.re.match('\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', tmp, modules.re.IGNORECASE) %}
  {% set tmp = modules.datetime.datetime.strptime(tmp, '%Y-%m-%d %H:%M:%S') %}
  {% elif modules.re.match('\d{4}-\d{2}-\d{2}', tmp, modules.re.IGNORECASE) %}
  {% set tmp = modules.datetime.datetime.strptime(tmp, '%Y-%m-%d') %}
  {% else %}
  {{ exceptions.raise_compiler_error('var "end_hour" is invalid format')}}
  {% endif %}
  {{ return(tmp.strftime("%Y-%m-%d %H:%M:%S")) }}
{% endmacro %}`

**Comment by graciegoheen** [comment]
Hey! I think you might just have a bug in your macro because the error message you're getting is related to strptime, which you call in your macro. 

Is there a reason you think this is a bug with dbt core? What is your expected behavior?

**Comment by dbeatty10** [comment]
@pengyusong I didn't test this out, but my guess is that the problem is with this section of your code:
```sql
  {% elif modules.re.match('\d{4}-\d{2}-\d{2}', tmp, modules.re.IGNORECASE) %}
  {% set tmp_dt= modules.datetime.datetime.strptime(tmp, '%Y-%m-%d') %}
```

I'm guessing you need to use a pattern like this instead (which starts with `^` and ends with `$`:
```python
'^\d{4}-\d{2}-\d{2}$'
```

https://pythex.org/ and https://regex101.com/ are some helpful websites to test out regular expressions to make sure they match the things you want (but not things you don't want).

**Comment by pengyusong** [comment]
Sorry, my problem. I am Java programmer, beginners of Python and DBT. As i think match will full match.

**Comment by dbeatty10** [comment]
> Why DBT cannot show the exception happed in `vars_end_hour` macro.

Jinja is a templating language quite different from programming languages like Java.

Jinja compiles templates, including macros, into an internal Python code structure to efficiently render the final text output, creating an abstraction layer between the original template code and the execution. This compilation process converts the high-level Jinja syntax into a series of Python function calls that represent the template's logic but don't directly map to the original lines of code. Consequently, when an error occurs within a macro during rendering, the traceback is in the context of the compiled Python functions, not the Jinja source. This discrepancy makes it challenging to pinpoint errors back to the specific lines in the original Jinja macro, as the execution and error-handling are effectively happening one step removed from the source code written by the developer.

If you're interested into diving deep into the gory details of how Jinja works, you can Google for resources like this talk: [Code Generation in Python: Dismantling Jinja](https://www.youtube.com/watch?v=jXlR0Icvvh8)
