### ISSUE TITLE
[CT-3258] [Bug] Compilation step fails with ImportError: cannot import name 'POLLING_PREDICATE' from 'google.api_core.future.polling'

### ISSUE THREAD

**Issue by gmyrianthous** [dbt-labs/dbt-core#8894]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am currently testing `dbt-core` and `dbt-bigquery` v1.6.0 and while compiling one of my projects, I get the following error: 

```
ImportError: cannot import name 'POLLING_PREDICATE' from 'google.api_core.future.polling' 
```

I have tried both v1.6.0 and v1.6.6 but the same error occurs. 

### Expected Behavior

I would expect that compilation step completes successfully. 

### Steps To Reproduce

1. Create a `pyproject.toml` file as follows: 

```
[tool.poetry]
name = "dbt"

[tool.poetry.dependencies]
python = "~3.8.12"
dbt-core = "1.6.6"
dbt-bigquery = "1.6.6"

[tool.poetry.group.dev.dependencies]
sqlfluff = "1.4.5"
sqlfluff-templater-dbt = "1.4.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
2. Generate the lock file and install dependencies
```
poetry lock --no-update 
poetry install
```
3. Run `dbt compile` within the poetry environment
```
poetry run dbt compile --profiles-dir /path/to/profiles --target mytarget
```

### Relevant log output

```shell
10:56:40  Running with dbt=1.6.6
10:56:40  Encountered an error:
cannot import name 'POLLING_PREDICATE' from 'google.api_core.future.polling' (/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/google/api_core/future/polling.py)
10:56:40  Traceback (most recent call last):
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 140, in wrapper
    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/config/runtime.py", line 70, in load_profile
    profile = Profile.render(
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/config/profile.py", line 436, in render
    return cls.from_raw_profiles(
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/config/profile.py", line 401, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/config/profile.py", line 355, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile
    cls = load_plugin(typename)
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/adapters/factory.py", line 212, in load_plugin
    return FACTORY.load_plugin(name)
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/adapters/factory.py", line 58, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "/usr/local/Cellar/python@3.8/3.8.18/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/adapters/bigquery/__init__.py", line 5, in <module>
    from dbt.adapters.bigquery.impl import BigQueryAdapter, GrantTarget, PartitionConfig  # noqa
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/adapters/bigquery/impl.py", line 32, in <module>
    from dbt.adapters.bigquery.python_submissions import (
  File "/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/dbt/adapters/bigquery/python_submissions.py", line 4, in <module>
    from google.api_core.future.polling import POLLING_PREDICATE
ImportError: cannot import name 'POLLING_PREDICATE' from 'google.api_core.future.polling' (/Users/gmyrianthous/virtualenvs/analytics-venv/lib/python3.8/site-packages/google/api_core/future/polling.py)
```
```


### Environment

```markdown
- OS: OSX
- Python: 3.8.12
- dbt: 1.6.0/1.6.6
```

### Which database adapter are you using with dbt?

bigquery

**Comment by gmyrianthous** [comment]
This issue seems to be specific to the bigquery adapter, so I have created a new issue under `dbt-bigquery` repo -> https://github.com/dbt-labs/dbt-bigquery/issues/979
