### ISSUE TITLE
[CT-3292] [Bug] Basic ref macro override results in File "<template>", line 12 SyntaxError: keyword argument repeated: tags

### ISSUE THREAD

**Issue by arseniecily** [dbt-labs/dbt-core#8946]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have this override of the ref macro in a file in the macros/ folder of my dbt project. 

```
{%- macro ref(table_name) -%}

    {% set relation = builtins.ref(table_name) %}
    {% do return(relation) %}

{%- endmacro -%}
```

When I try to run any model using `dbt run --models xxx` this results in the error below:

```
Encountered an error:
keyword argument repeated: tags (<template>, line 12)
```

if I delete the file then dbt models run as expected.

### Expected Behavior

Expecting dbt to run successfully since the ref macro override is returning the same relation as the built-in ref macro.

### Steps To Reproduce

dbt-core==1.6.6
dbt-refshift==1.6.2
Python 3.9.13

In your dbt project put the code below in a source.sql file in the macros/ folder:
```
{%- macro ref(table_name) -%}

    {% set relation = builtins.ref(table_name) %}
    {% do return(relation) %}

{%- endmacro -%}
```
then run `dbt run --models some_model_with_ref`

### Relevant log output

```shell
(base) username@User % dbt run --models daily_interest_report
14:18:40  Running with dbt=1.6.6
14:18:40  Registered adapter: redshift=1.6.2
14:18:40  Unable to do partial parsing because profile has changed
14:18:41  Encountered an error:
keyword argument repeated: tags (<template>, line 12)
14:18:41  Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 219, in wrapper
    return func(*args, **kwargs)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 246, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/manifest.py", line 316, in get_full_manifest
    manifest = loader.load()
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/manifest.py", line 475, in load
    self.parse_project(
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/manifest.py", line 671, in parse_project
    parser.parse_file(block)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/base.py", line 466, in parse_file
    self.parse_node(file_block)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/base.py", line 427, in parse_node
    self.render_update(node, config)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/models.py", line 360, in render_update
    super().render_update(node, config)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/base.py", line 403, in render_update
    context = self.render_with_context(node, config)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/parser/base.py", line 263, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/clients/jinja.py", line 592, in get_rendered
    template = get_template(
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/clients/jinja.py", line 541, in get_template
    return env.from_string(template_source, globals=ctx)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 766, in compile
    return self._compile(source, filename)
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/dbt/clients/jinja.py", line 107, in _compile
    return super()._compile(source, filename)  # type: ignore
  File "/Users/username/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 704, in _compile
    return compile(source, filename, "exec")  # type: ignore
  File "<template>", line 12
SyntaxError: keyword argument repeated: tags
```

### Environment

```markdown
- OS: MacOS Ventura 13.6
- Python: 3.9.13
- dbt: Core 1.6.6
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

Have also tried overriding the source macro with the same result: 

```
{%- macro source(source_name, table_name) -%}

    {% set rel = builtins.source(source_name, table_name) %}
    {{ rel }}

{%- endmacro -%}
```

and 

```
{%- macro source(source_name, table_name) -%}

    {% set rel = builtins.source(source_name, table_name) %}
    {% do return(rel) %}

{%- endmacro -%}
```

**Comment by dbeatty10** [comment]
Thanks for opening this @arseniecily.

Could you help me try to reproduce this?

I used the following files, but this doesn't appear to be enough to trigger the error that you reported. Perhaps there's some interaction effect with `tags` you have within your project? Could you try tweaking these files to get it to raise an error?

1\. Create these files:

`seeds/my_seed.csv`

```csv
id
1
```

`models/my_model.sql`

```sql
select * from {{ ref("my_seed") }}
```

`macros/ref.sql`

```sql
{%- macro ref(table_name) -%}

    {% set relation = builtins.ref(table_name) %}
    {% do return(relation) %}

{%- endmacro -%}
```

2\. Run the project:

```shell
dbt seed
dbt run --models my_model
```

**Comment by arseniecily** [comment]
Tried to reproduce the error and found that in the config of one of the dbt models the 'tags' parameter was defined twice. It did not cause any error while running dbt and only surfaced when trying to override ref or source macros for some reason. 
Thanks!
