### ISSUE TITLE
[Bug] Unhandled exception for failing `on-run-*` hooks in `source freshness`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#9511]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

_follow up to https://github.com/dbt-labs/dbt-core/pull/9366_

Failing hooks in `source freshness` lead to an unhandled exception

### Expected Behavior

The exception is handled, as it is for other commands

### Steps To Reproduce

1. Create a simple project that defines a source with `freshness` + `loaded_at_field`
2. In the project file:
```yml
# dbt_project.yml
flags:
  source_freshness_run_project_hooks: true

on-run-start:
  "select fake_column from table_does_not_exist"
```
3. `dbt source freshness`

### Relevant log output

```shell
$ dbt source freshness
12:11:06  Running with dbt=1.8.0-a1
12:11:06  Registered adapter: postgres=1.8.0-a1
12:11:06  Unable to do partial parsing because a project config has changed
12:11:07  Found 1 operation, 1 source, 521 macros
12:11:07
12:11:08
12:11:08  Running 1 on-run-start hook
12:11:08  1 of 1 START hook: my_dbt_project.on-run-start.0 ............................... [RUN]
12:11:08  Database error while running on-run-start
12:11:08  Concurrency: 5 threads (target='dev')
12:11:08
12:11:08  1 of 1 START freshness of my_src.my_tbl ........................................ [RUN]
12:11:08  1 of 1 WARN freshness of my_src.my_tbl ......................................... [WARN in 0.04s]
12:11:08
12:11:08  Finished running 1 source in 0 hours 0 minutes and 0.32 seconds (0.32s).
12:11:08  Encountered an error:
'BaseResult' object has no attribute 'node'
12:11:08  Traceback (most recent call last):
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 97, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 175, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 204, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 251, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/requires.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/cli/main.py", line 789, in freshness
    results = task.run()
  File "/Users/jerco/dev/product/dbt-core/core/dbt/task/runnable.py", line 524, in run
    result.write(self.result_path())
  File "/Users/jerco/dev/product/dbt-core/core/dbt/artifacts/schemas/freshness/v3/freshness.py", line 67, in write
    FreshnessExecutionResultArtifact.from_result(self).write(path)
  File "/Users/jerco/dev/product/dbt-core/core/dbt/artifacts/schemas/freshness/v3/freshness.py", line 110, in from_result
    processed = [process_freshness_result(r) for r in base.results]
  File "/Users/jerco/dev/product/dbt-core/core/dbt/artifacts/schemas/freshness/v3/freshness.py", line 110, in <listcomp>
    processed = [process_freshness_result(r) for r in base.results]
  File "/Users/jerco/dev/product/dbt-core/core/dbt/artifacts/schemas/freshness/v3/freshness.py", line 119, in process_freshness_result
    unique_id = result.node.unique_id
AttributeError: 'BaseResult' object has no attribute 'node'
```

### Environment

```markdown
- OS: 13.4.1
- Python: 3.10.11
- dbt: 1.8.0-a1
```

**Comment by aranke** [comment]
@jtcohen6 I tried your fix locally and observed the following:
1. ✅ The error is surfaced in the CLI
2. ❓ The hook isn't written to `run_results.json`

Is behavior 2 to be expected?

Relevant logs

```bash
❯ dbt source freshness
22:24:43  Running with dbt=1.8.0-b1
22:24:43  Registered adapter: duckdb=1.7.2
22:24:43  Found 5 models, 3 seeds, 1 operation, 20 data tests, 1 source, 515 macros
22:24:43  
22:24:43  
22:24:43  Running 1 on-run-start hook
22:24:43  1 of 1 START hook: jaffle_shop.on-run-start.0 .................................. [RUN]
22:24:43  Database error while running on-run-start
22:24:43  Concurrency: 24 threads (target='dev')
22:24:43  
22:24:43  1 of 1 START freshness of external_source.flights .............................. [RUN]
22:24:43  1 of 1 WARN freshness of external_source.flights ............................... [WARN in 0.11s]
22:24:43  
22:24:43  Finished running 1 source in 0 hours 0 minutes and 0.18 seconds (0.18s).
22:24:43  
22:24:43    on-run-start failed, error:
 Catalog Error: Table with name table_does_not_exist does not exist!
Did you mean "system.information_schema.tables"?
LINE 2: select fake_column from table_does_not_exist
                                ^
22:24:43  Done.
```

```bash
❯ jq . target/run_results.json
{
  "metadata": {
    "dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v6.json",
    "dbt_version": "1.8.0b1",
    "generated_at": "2024-03-14T17:32:16.885851Z",
    "invocation_id": "2bb39861-2af7-44eb-a343-3a8c57f94611",
    "env": {}
  },
  "results": [
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2024-03-14T17:32:16.808945Z",
          "completed_at": "2024-03-14T17:32:16.808947Z"
        },
        {
          "name": "execute",
          "started_at": "2024-03-14T17:32:16.830234Z",
          "completed_at": "2024-03-14T17:32:16.872467Z"
        }
      ],
      "thread_id": "Thread-3 (worker)",
      "execution_time": 0.06602787971496582,
      "adapter_response": {
        "_message": "INSERT 113",
        "code": "INSERT",
        "rows_affected": 113
      },
      "message": "INSERT 113",
      "failures": null,
      "unique_id": "seed.jaffle_shop.raw_payments",
      "compiled": null,
      "compiled_code": null,
      "relation_name": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2024-03-14T17:32:16.808757Z",
          "completed_at": "2024-03-14T17:32:16.808759Z"
        },
        {
          "name": "execute",
          "started_at": "2024-03-14T17:32:16.826311Z",
          "completed_at": "2024-03-14T17:32:16.873314Z"
        }
      ],
      "thread_id": "Thread-2 (worker)",
      "execution_time": 0.0670621395111084,
      "adapter_response": {
        "_message": "INSERT 99",
        "code": "INSERT",
        "rows_affected": 99
      },
      "message": "INSERT 99",
      "failures": null,
      "unique_id": "seed.jaffle_shop.raw_orders",
      "compiled": null,
      "compiled_code": null,
      "relation_name": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2024-03-14T17:32:16.808555Z",
          "completed_at": "2024-03-14T17:32:16.808558Z"
        },
        {
          "name": "execute",
          "started_at": "2024-03-14T17:32:16.809550Z",
          "completed_at": "2024-03-14T17:32:16.873645Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.07144284248352051,
      "adapter_response": {
        "_message": "INSERT 100",
        "code": "INSERT",
        "rows_affected": 100
      },
      "message": "INSERT 100",
      "failures": null,
      "unique_id": "seed.jaffle_shop.raw_customers",
      "compiled": null,
      "compiled_code": null,
      "relation_name": null
    }
  ],
  "elapsed_time": 0.15845298767089844,
  "args": {
    "introspect": true,
    "quiet": false,
    "warn_error_options": {
      "include": [],
      "exclude": []
    },
    "printer_width": 80,
    "defer": false,
    "use_colors": true,
    "write_json": true,
    "project_dir": "/Users/karanke/workspace/jaffle_shop_duckdb",
    "version_check": true,
    "log_format_file": "debug",
    "log_file_max_bytes": 10485760,
    "favor_state": false,
    "print": true,
    "log_level_file": "debug",
    "show_resource_report": false,
    "invocation_command": "dbt seed",
    "partial_parse": true,
    "profiles_dir": "/Users/karanke/workspace/jaffle_shop_duckdb",
    "vars": {},
    "enable_legacy_logger": false,
    "send_anonymous_usage_stats": true,
    "show": false,
    "cache_selected_only": false,
    "select": [],
    "partial_parse_file_diff": true,
    "exclude": [],
    "use_colors_file": true,
    "log_format": "default",
    "source_freshness_run_project_hooks": true,
    "macro_debugging": false,
    "populate_cache": true,
    "log_level": "info",
    "indirect_selection": "eager",
    "static_parser": true,
    "strict_mode": false,
    "which": "seed",
    "log_path": "/Users/karanke/workspace/jaffle_shop_duckdb/logs"
  }
}
```

**Comment by graciegoheen** [comment]
I am surprised that the failing hook isn't written to the run_results - how are similar errors typically handled?

**Comment by aranke** [comment]
It looks like `on-run-start` errors for `dbt run` aren't written to `run_results.json`, so I'll maintain this behavior for `dbt source freshness` for now.

Do we want to keep this behavior, or should we create a follow-up ticket to fix this?

**Comment by jtcohen6** [comment]
Just chatted about this with @aranke. I agree that it's surprising behavior, and also outside the scope of the fix for this bug, so @aranke said he would open a new issue. The thing I'm not sure about is exactly how hook nodes should be included in the `results` dictionary of `run_results.json` / `sources.json` — especially the latter, which is currently `Union[SourceFreshnessOutput, SourceFreshnessRuntimeError]`.

The ability to `dbt retry` from point of failures (including failed hooks!) makes sense. This also feels related to another issue, which is that hooks should actually participate in the DAG in the sense of `on-run-start` hooks preventing subsequent DAG nodes from running (marking them `Skipped`):
- https://github.com/dbt-labs/dbt-core/issues/7387
