### ISSUE TITLE
[Regression] installation does not work without distutils, deprecated in python 3.12

### ISSUE THREAD

**Issue by jim-baker-fulcrum** [dbt-labs/dbt-core#9705]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Per the instructions in https://docs.getdbt.com/docs/core/pip-install
```
python3 -m venv dbt-env
source dbt-env/bin/activate   
python -m pip install dbt-bigquery
```
This installs fine; my personal output is captured in relevant log output below.  However, the install won't work because it is still reliant on dsitutils: 
```
(dbt-env) wrongjim:[chaos]~
>> dbt --version
Traceback (most recent call last):
  File "/Users/wrongjim/dbt-env/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/Users/wrongjim/dbt-env/lib/python3.12/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wrongjim/dbt-env/lib/python3.12/site-packages/dbt/cli/main.py", line 25, in <module>
    from dbt.task.build import BuildTask
  File "/Users/wrongjim/dbt-env/lib/python3.12/site-packages/dbt/task/build.py", line 6, in <module>
    from .test import TestRunner as test_runner
  File "/Users/wrongjim/dbt-env/lib/python3.12/site-packages/dbt/task/test.py", line 1, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
(dbt-env) wrongjim:[chaos]~
>> 
```
distutils was deprecated in python 3.12 per https://docs.python.org/3.11/distutils/

### Expected/Previous Behavior

DBT should run on the current stable version of python.  While we're at it, now would be a great time to just start supporting homebrew again.  

### Steps To Reproduce

See steps in Current Behavior section

### Relevant log output

```shell
output of the  -m pip install dbt-bigquery command

(dbt-env) wrongjim:[chaos]~
>> python -m pip install dbt-bigquery
Requirement already satisfied: dbt-bigquery in ./dbt-env/lib/python3.12/site-packages (1.7.6)
Requirement already satisfied: dbt-core~=1.7.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-bigquery) (1.7.8)
Requirement already satisfied: google-cloud-bigquery~=3.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-bigquery) (3.17.2)
Requirement already satisfied: google-cloud-storage~=2.4 in ./dbt-env/lib/python3.12/site-packages (from dbt-bigquery) (2.14.0)
Requirement already satisfied: google-cloud-dataproc~=5.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-bigquery) (5.9.2)
Requirement already satisfied: google-api-core>=2.11.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-bigquery) (2.17.1)
Requirement already satisfied: agate~=1.7.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (1.7.1)
Requirement already satisfied: Jinja2~=3.1.2 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (3.1.3)
Requirement already satisfied: mashumaro~=3.9 in ./dbt-env/lib/python3.12/site-packages (from mashumaro[msgpack]~=3.9->dbt-core~=1.7.0->dbt-bigquery) (3.12)
Requirement already satisfied: logbook<1.6,>=1.5 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (1.5.3)
Requirement already satisfied: click<9,>=8.0.2 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (8.1.7)
Requirement already satisfied: networkx<4,>=2.3 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (3.2.1)
Requirement already satisfied: colorama<0.5,>=0.3.9 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.4.6)
Requirement already satisfied: pathspec<0.12,>=0.9 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.11.2)
Requirement already satisfied: isodate<0.7,>=0.6 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.6.1)
Requirement already satisfied: sqlparse<0.5,>=0.2.3 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.4.4)
Requirement already satisfied: dbt-extractor~=0.5.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.5.1)
Requirement already satisfied: minimal-snowplow-tracker~=0.0.2 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.0.2)
Requirement already satisfied: dbt-semantic-interfaces~=0.4.2 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (0.4.4)
Requirement already satisfied: jsonschema>=3.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (4.21.1)
Requirement already satisfied: packaging>20.9 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (23.2)
Requirement already satisfied: protobuf>=4.0.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (4.25.3)
Requirement already satisfied: pytz>=2015.7 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (2024.1)
Requirement already satisfied: pyyaml>=6.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (4.10.0)
Requirement already satisfied: cffi<2.0.0,>=1.9 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (3.6)
Requirement already satisfied: requests<3.0.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (2.31.0)
Requirement already satisfied: urllib3~=1.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-core~=1.7.0->dbt-bigquery) (1.26.18)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in ./dbt-env/lib/python3.12/site-packages (from google-api-core>=2.11.0->dbt-bigquery) (1.62.0)
Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in ./dbt-env/lib/python3.12/site-packages (from google-api-core>=2.11.0->dbt-bigquery) (2.28.1)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in ./dbt-env/lib/python3.12/site-packages (from google-cloud-bigquery~=3.0->dbt-bigquery) (2.4.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in ./dbt-env/lib/python3.12/site-packages (from google-cloud-bigquery~=3.0->dbt-bigquery) (2.7.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in ./dbt-env/lib/python3.12/site-packages (from google-cloud-bigquery~=3.0->dbt-bigquery) (2.8.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in ./dbt-env/lib/python3.12/site-packages (from google-cloud-dataproc~=5.0->dbt-bigquery) (1.23.0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in ./dbt-env/lib/python3.12/site-packages (from google-cloud-dataproc~=5.0->dbt-bigquery) (0.13.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in ./dbt-env/lib/python3.12/site-packages (from google-cloud-storage~=2.4->dbt-bigquery) (1.5.0)
Requirement already satisfied: Babel>=2.0 in ./dbt-env/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core~=1.7.0->dbt-bigquery) (2.14.0)
Requirement already satisfied: leather>=0.3.2 in ./dbt-env/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core~=1.7.0->dbt-bigquery) (0.4.0)
Requirement already satisfied: parsedatetime!=2.5,>=2.1 in ./dbt-env/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core~=1.7.0->dbt-bigquery) (2.6)
Requirement already satisfied: python-slugify>=1.2.1 in ./dbt-env/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core~=1.7.0->dbt-bigquery) (8.0.4)
Requirement already satisfied: pytimeparse>=1.1.5 in ./dbt-env/lib/python3.12/site-packages (from agate~=1.7.0->dbt-core~=1.7.0->dbt-bigquery) (1.1.8)
Requirement already satisfied: pycparser in ./dbt-env/lib/python3.12/site-packages (from cffi<2.0.0,>=1.9->dbt-core~=1.7.0->dbt-bigquery) (2.21)
Requirement already satisfied: importlib-metadata~=6.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-semantic-interfaces~=0.4.2->dbt-core~=1.7.0->dbt-bigquery) (6.11.0)
Requirement already satisfied: more-itertools<11.0,>=8.0 in ./dbt-env/lib/python3.12/site-packages (from dbt-semantic-interfaces~=0.4.2->dbt-core~=1.7.0->dbt-bigquery) (10.2.0)
Requirement already satisfied: pydantic<3,>=1.10 in ./dbt-env/lib/python3.12/site-packages (from dbt-semantic-interfaces~=0.4.2->dbt-core~=1.7.0->dbt-bigquery) (2.6.2)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in ./dbt-env/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-dataproc~=5.0->dbt-bigquery) (1.62.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in ./dbt-env/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-dataproc~=5.0->dbt-bigquery) (1.62.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./dbt-env/lib/python3.12/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core>=2.11.0->dbt-bigquery) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./dbt-env/lib/python3.12/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core>=2.11.0->dbt-bigquery) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in ./dbt-env/lib/python3.12/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core>=2.11.0->dbt-bigquery) (4.9)
Requirement already satisfied: six in ./dbt-env/lib/python3.12/site-packages (from isodate<0.7,>=0.6->dbt-core~=1.7.0->dbt-bigquery) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./dbt-env/lib/python3.12/site-packages (from Jinja2~=3.1.2->dbt-core~=1.7.0->dbt-bigquery) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in ./dbt-env/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core~=1.7.0->dbt-bigquery) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./dbt-env/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core~=1.7.0->dbt-bigquery) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in ./dbt-env/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core~=1.7.0->dbt-bigquery) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in ./dbt-env/lib/python3.12/site-packages (from jsonschema>=3.0->dbt-core~=1.7.0->dbt-bigquery) (0.18.0)
Requirement already satisfied: msgpack>=0.5.6 in ./dbt-env/lib/python3.12/site-packages (from mashumaro[msgpack]~=3.9->dbt-core~=1.7.0->dbt-bigquery) (1.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in ./dbt-env/lib/python3.12/site-packages (from requests<3.0.0->dbt-core~=1.7.0->dbt-bigquery) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in ./dbt-env/lib/python3.12/site-packages (from requests<3.0.0->dbt-core~=1.7.0->dbt-bigquery) (2024.2.2)
Requirement already satisfied: zipp>=0.5 in ./dbt-env/lib/python3.12/site-packages (from importlib-metadata~=6.0->dbt-semantic-interfaces~=0.4.2->dbt-core~=1.7.0->dbt-bigquery) (3.17.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in ./dbt-env/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core>=2.11.0->dbt-bigquery) (0.5.1)
Requirement already satisfied: annotated-types>=0.4.0 in ./dbt-env/lib/python3.12/site-packages (from pydantic<3,>=1.10->dbt-semantic-interfaces~=0.4.2->dbt-core~=1.7.0->dbt-bigquery) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in ./dbt-env/lib/python3.12/site-packages (from pydantic<3,>=1.10->dbt-semantic-interfaces~=0.4.2->dbt-core~=1.7.0->dbt-bigquery) (2.16.3)
Requirement already satisfied: text-unidecode>=1.3 in ./dbt-env/lib/python3.12/site-packages (from python-slugify>=1.2.1->agate~=1.7.0->dbt-core~=1.7.0->dbt-bigquery) (1.3)
(dbt-env) wrongjim:[chaos]~
>>
```

### Environment

```markdown
- OS: MacOS 14.3.1 / bash shell
- Python: 3.12
- dbt (working version): 
- dbt (regression version):
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
> DBT should run on the current stable version of python.

We agree! See here for details of our upcoming plans: https://github.com/dbt-labs/dbt-core/issues/9007#issuecomment-1967148140

Quick summary:
> Python 3.12 support will be included with upcoming `dbt-core` releases `1.7.9` and `1.8.0b1`.

There may be additional work for dbt-bigquery to support Python 3.12, and you can follow along here: https://github.com/dbt-labs/dbt-adapters/issues/57

So I'm going to close this issue as covered by those above. Please reach out if 3.12 doesn't work for you after those have been resolved and released to PyPI.

> While we're at it, now would be a great time to just start supporting homebrew again.

We stopped supporting Homebrew as an installation method starting in version 1.6. This following discussion has our rationale:

[Installing dbt Core: saying goodbye to brew and hello to "bundles"](https://github.com/dbt-labs/dbt-core/discussions/8277)
