### ISSUE TITLE
[Bug] Getting TypeError when running any dbt command

### ISSUE THREAD

**Issue by tobiascadee** [dbt-labs/dbt-core#9761]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am getting this error when running any dbt command on dbt-redshift 1.7.4 and dbt-core 1.7.10:
`Traceback (most recent call last):
  File "/opt/homebrew/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/main.py", line 13, in <module>
    from dbt.cli import requires, params as p
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/requires.py", line 1, in <module>
    import dbt.tracking
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/tracking.py", line 103, in <module>
    emitter = TimeoutEmitter()
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/tracking.py", line 53, in __init__
    super().__init__(
TypeError: Emitter.__init__() got an unexpected keyword argument 'buffer_size'`

### Expected Behavior

for the dbt command to execute

### Steps To Reproduce

1. environment with python 3.10.13 and dbt-resddhift 1.7.4 and dbt-core 1.7.10
2. run dbt deps (or any dbt command)

### Environment

```markdown
- OS: macOS 14.4
- Python: 3.10.13
- dbt: 1.7.10
```

### Which database adapter are you using with dbt?

redshift

**Comment by dbeatty10** [comment]
Thanks for reaching out @tobiascadee.

This looks similar to https://github.com/dbt-labs/dbt-core/issues/8719#issuecomment-1829521510.

Are you using Meltano, by any chance? If not, are you somehow installing [`snowplow-python-tracker`](https://pypi.org/project/snowplow-tracker) separately from dbt?

**Comment by tobiascadee** [comment]
Seems like the issue was resolved!
